### ISSUE TITLE
[Feature request] Is it possible to get support for NLLB models?

### ISSUE THREAD

**Issue by mark-beshara** [xenova/transformers.js#101]
Want to start off by saying thanks for working so hard on such a great repo!

Like the title says was hoping to see if we could get support for NLLB models, specifically I was trying to pull [facebook/nllb-200-distilled-600M.](https://huggingface.co/facebook/nllb-200-distilled-600M) 

I can't convert w/ quantization (keeps freezing after a certain point indefinitely) and when I try to convert it without quantization the task becomes an issue, since it writes it to to model/path/translation/..., but when you try to access the model with the pipeline it tries to find model/path/seq2seq-lm-with-past/....I cant overwrite the directory name since it then can't find a specific converted file so it seems like in general conversion for this model is broken.

**Comment by mark-beshara** [comment]
> Sure, that looks simple enough to add. I'll get around to doing it once v2.0.0 releases, as it will make the process a > whole lot easier :)

Thank you sounds good!

> This might be related to https://github.com/huggingface/optimum/issues/1012, as optimum (the library which does the conversion) kills the program if memory usage gets too high.

Weird that it would run out of memory though the machine I'm using is running w/ 64 gb ram (doing this on CPU), so not sure why that would be an issue unless the process is internally capping the memory usage or somehow this is being done on GPU? 

> This is related to this change in optimum: https://github.com/huggingface/optimum/commit/f7f1ef1d9d8e6fbadb5df9051e4c3685ec4ebc93 which uses canonical pipeline names for the export. For now, you should be able to override it by specifying --task seq2seq-lm-with-past in the conversion script, but this will be fixed in version 2.0.0, since it automatically detects the task and exports the correct model.

Yeah I tried that too, but weirdly running `--task seq2seq-lm-with-past` causes a `KeyError: 'seq2seq-lm'`, since it's not mapped but I just realized you had the same issue in huggingface/optimum#991, I should probably open an issue there for that.

**Comment by xenova** [comment]
I think I've got it working - just need to do some extra testing. Can you send some example python code and expected output, so that I can test the usage is the same and that the outputs are correct 👍

**Comment by mark-beshara** [comment]
Alright glad one of us made progress lol, I was able to get it to convert to onnx, but can't get it to load in JS.

Here's some demo code from a space on huggingface: https://huggingface.co/spaces/Narrativaai/NLLB-Translator/blob/main/app.py that demos how to use it in a pipeline. It takes a source and target language (supported languages can be found here: https://huggingface.co/spaces/Narrativaai/NLLB-Translator/blob/main/langs.py).

**Comment by xenova** [comment]
> Alright glad one of us made progress lol, I was able to get it to convert to onnx, but can't get it to load in JS.

Haha yeah - Neither the tokenizer nor model is currently supported in the main branch 😅  so, no worries haha. I'll let you know how and when you can test it

> Here's some demo code from a space on huggingface: https://huggingface.co/spaces/Narrativaai/NLLB-Translator/blob/main/app.py that demos how to use it in a pipeline. It takes a source and target language (supported languages can be found here: https://huggingface.co/spaces/Narrativaai/NLLB-Translator/blob/main/langs.py).

Great! That's exactly what I was looking for. Unfortunately, JS doesn't have a super nice way to pass and parse keyword arguments, but I'll get something working (so that the usage is near-identical).

I'll keep you updated 👍

**Comment by mark-beshara** [comment]
Yeah unfortunately my JS ability is non-existent lol so I'm gonna leave this to the experts (you), but sounds good.

Appreciate all the effort and the quick replies!

**Comment by xenova** [comment]
Got it working :) I don't speak Greek, but google translate agrees with the example translation (see below) and it translates back to the original sentence. 

These changes are live on the [dev branch](https://github.com/xenova/transformers.js/tree/docs), and I plan to make a full release soon.


Example usage:
```js

import { pipeline, env } from '../src/transformers.js';
env.allowRemoteModels = false;

(async () => {
    let translator = await pipeline('translation', 'facebook/nllb-200-distilled-600M');

    let result = await translator('I like to walk my dog.', {
        src_lang: 'eng_Latn',
        tgt_lang: 'ell_Grek'
    });
    console.log(result);
    // [ { translation_text: 'Μου αρέσει να περπατάω το σκυλί μου.' } ]

    let result2 = await translator(result[0].translation_text, {
        src_lang: 'ell_Grek',
        tgt_lang: 'eng_Latn'
    });
    console.log(result2);
    // [ { translation_text: 'I like to walk my dog.' } ]
})();
```


---

Depending on how urgently you need this, you can either wait for the full release, or you can install from the dev branch, and convert the model using the new format.

The steps would look something like this:
1. Install from dev branch: `npm install "https://github.com/xenova/transformers.js.git#docs"`
2. Run the conversion script: `python -m scripts.convert --quantize --model_id facebook/nllb-200-distilled-600M`

**Comment by xenova** [comment]
I'll also make it default to english (so you don't need to specify source language)

**Comment by mark-beshara** [comment]
You are the :goat:, thank you for implementing this!

I might mess around on the dev branch but this was mostly a for-fun project so no urgency, but I def appreciate you taking the time to work and implement this so quickly! 

>I'll also make it default to english (so you don't need to specify source language)

I'm actually going to determine source language with cld3 since it might vary, but still it's a nice feature to have regardless.

**Comment by mark-beshara** [comment]
Hey before this gets closed figured I'd let you know about this bug, when I tried to run the example you gave me I got an error in tokenizer.js about the line `this.post_processor.config.single[0].SpecialToken.id = generate_kwargs.src_lang;`, since single[0] isn't a SpecialToken, it's a Sequence. 

Changing the line to `this.post_processor.config.single[2].SpecialToken.id = generate_kwargs.src_lang;` produced outputs. Though I'm not sure if it's messing something else since it gets the first translation semi-close, but then deviates heavily on the translation back. This is with the quantized model so not sure if that's the reason? Here's the output, with me printing the value of `this.post_processing.config.single` and the translated text:
`[
  { Sequence: { id: 'A', type_id: 0 } },
  { SpecialToken: { id: '</s>', type_id: 0 } },
  { SpecialToken: { id: 'eng_Latn', type_id: 0 } }
]
[ { translation_text: 'Ασχολείται με το σκυλί.' } ]
[
  { Sequence: { id: 'A', type_id: 0 } },
  { SpecialToken: { id: '</s>', type_id: 0 } },
  { SpecialToken: { id: 'ell_Grek', type_id: 0 } }
]
[
  {
    translation_text: "I'm going to be a little bit more careful about the rest of the world."
  }
]`

Did you use a quantized model or the complete model when you were running it?

**Comment by xenova** [comment]
Whoops! I forgot to account for different orderings of the special tokens list in the config. Thanks for pointing that out :) Will fix now.

**Comment by xenova** [comment]
Fixed [here](https://github.com/xenova/transformers.js/commit/76e2a1f3c3c09dbb3644de57c81fa83d878f6d9c)

**Comment by mark-beshara** [comment]
Perfect, will pull the latest version!

As for the model performance any idea why it differed from your outputs, or was it the same and the comments you had were just the ideal outputs?

**Comment by xenova** [comment]
> As for the model performance any idea why it differed from your outputs, or was it the same and the comments you had were just the ideal outputs?

The comments were the actual model outputs, so, you should be getting the same/similar. Are you using the latest version of optimum?

**Comment by mark-beshara** [comment]
Hmmm I thought I was since I was running 1.8.2 but it looks like a new update dropped a couple days ago, I'll try again with it and see how it goes. 

If it's not a lot of trouble that would be great just in case this goes poorly again lol

**Comment by mark-beshara** [comment]
Alright so after updating every ML package I have in the env it finally quantized properly and I got the expected output so think everything is in order now with that last bug fix!

**Comment by xenova** [comment]
> Alright so after updating every ML package I have in the env it finally quantized properly and I got the expected output so think everything is in order now with that last bug fix!

🎉🎉🎉 Sweet!

**Comment by mark-beshara** [comment]
sounds good, looking forward to the release in main and for 2.0!

:skull: Isn't that why we all became programmers, to write endless docs? lmaoo
