### ISSUE TITLE
Xenova/whisper-tiny preprocessor_config.json is missing `mel_filters`

### ISSUE THREAD

**Issue by kungfooman** [xenova/transformers.js#107]
**Describe the bug**
*A clear and concise description of what the bug is.*

![image](https://github.com/xenova/transformers.js/assets/5236548/5f5b8f1b-0b15-47a0-be88-b7d905bedfad)

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

```js
async function clearTransformersCache() {
  const tc = await caches.open("transformers-cache");
  const keys = await tc.keys();
  keys.forEach(key => tc.delete(key));
}
await clearTransformersCache();
// git clone https://huggingface.co/Xenova/whisper-tiny/
env.localModelPath = "http://127.0.0.1/transformer/models/";
const pipe = await pipeline("automatic-speech-recognition", "whisper-tiny");
const audioCTX = new AudioContext({
  sampleRate: 16000
});
const arrayBuffer = await (await fetch(SPEECH2TEXT_AUDIO.currentSrc)).arrayBuffer();
const decoded = await audioCTX.decodeAudioData(arrayBuffer);
const audio = decoded.getChannelData(0);
const result = await pipe(audio);
console.log("result", result);


```

**Expected behavior**

Making this code crash-proof:

https://github.com/xenova/transformers.js/blob/13b570ce975306d3b9dd3f88fb59dffc3a001cc1/src/processors.js#L860-L861

**Environment**
- Transformers.js version: latest docs branch
- Browser (if applicable): Chrome (should happen everywhere though)
- Operating system (if applicable): Linux (should happen everywhere though)

**Other**

My current "solution" is to simply copy over the entire file from:

https://huggingface.co/Xenova/whisper-tiny.en/blob/main/preprocessor_config.json

(it's the same, but having `mel_filters`)

**Comment by xenova** [comment]
That is quite strange indeed. Those were saved directly from using `.save_pretrained`, so, I'm not too sure why it didn't include it. It also seems to be a problem with small and base (non-english models). I'll look into it. Thanks!
