### ISSUE TITLE
[Question] Problem when converting an embedding model.

### ISSUE THREAD

**Issue by falcon027** [xenova/transformers.js#108]
A thirst I would like to thank everyone for providing and maintaining this library. It makes working with ML in JavaScript a breeze. 
I was working with the embedding models and tried to convert a multilingual model [("paraphrase-multilingual-MiniLM-L12-v2")](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) for use with transformers.js. I used the flow command to do the conversion: 

``` 
python -m scripts.convert --quantize --model_id sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 --task semantic-segmentation --from_hub
```

But I got the following error back: 

```  
File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.bert.configuration_bert.BertConfig'> for this kind of AutoModel: AutoModelForSemanticSegmentation.
Model type should be one of BeitConfig, Data2VecVisionConfig, DPTConfig, MobileNetV2Config, MobileViTConfig, SegformerConfig, UperNetConfig.
```  

I think I am using the wrong type of task, but I am not sure. Can anyone help me with this problem at hand. 
Thanks in advance. Falcon

**Comment by takoyaro** [comment]
try using `default` for the task

**Comment by falcon027** [comment]
Thanks for your quick reply, I tried it with the flag default and it resulted in a different error:
```
python -m scripts.convert --quantize --model_id sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 --task default --from_hub
```
```
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/optimum/exporters/tasks.py", line 1357, in get_model_from_task
    if TasksManager._TASKS_TO_LIBRARY[task.replace("-with-past", "")] == "transformers":
KeyError: 'default'
```

**Comment by xenova** [comment]
Hi there. We have updated the conversion script, so you should now be able to do:

```bash
python -m scripts.convert --quantize --model_id sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
```

For convenience, I have already converted and uploaded to the hub: https://huggingface.co/Xenova/paraphrase-multilingual-MiniLM-L12-v2

So, when the npm package is published (will be soon), you can use it as 
```js
import { pipeline } from '@xenova/transformers';

let extractor = await pipeline('feature-extraction', 'paraphrase-multilingual-MiniLM-L12-v2');

let output = await extractor('This is a sentence');
```

**Comment by xenova** [comment]
[Prerelease 2.0.0-alpha.0](https://www.npmjs.com/package/@xenova/transformers) is now available which fixes this. Closing for now. Feel free to reopen or ask further questions.
