### ISSUE TITLE
[Feature request] Support for `Prepend` type in `Normalizer.fromConfig`

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#109]
**Name of the feature**
A user of OpenCharacters (where AutoTokenizer is used to support [Basaran](https://github.com/hyperonym/basaran) inference - not that this context is super relevant here) was trying to load [this LLaMA model](https://huggingface.co/TehVenom/Pygmalion-7b-Merged-Safetensors) but hit upon the error "[Unknown Normalizer type: Prepend](https://github.com/xenova/transformers.js/blob/13b570ce975306d3b9dd3f88fb59dffc3a001cc1/src/tokenizers.js#L490)"

This is what the `config` object looks like:

![image](https://github.com/xenova/transformers.js/assets/1167575/479b8ab2-dd62-4db4-83ea-9a5335f817dd)

**To replicate**
```js
await import("https://cdn.jsdelivr.net/npm/@xenova/transformers/dist/transformers.min.js");
let tokenizer = await AutoTokenizer.from_pretrained("https://huggingface.co/TehVenom/Pygmalion-7b-Merged-Safetensors/resolve/main");
```

**Comment by xenova** [comment]
Sure thing - I can add that 👍

**Comment by xenova** [comment]
Had some time, so I thought I'd quickly implement this.

Though, it has `"pre_tokenizer": null,` - do you know what that means?

**Comment by xenova** [comment]
Added in https://github.com/xenova/transformers.js/commit/fa198903d361291bc32fa24067d621e28e0f64f4

It wasn't as simple as adding a prepend normalizer, since the llama tokenizer also does other things (like byte fallback)... but I got it working :)

Will be released in v2... (I promise, it will be released shortly haha 🤣 )

**Comment by josephrocca** [comment]
Thank you!!

**Comment by xenova** [comment]
Now in pre-release, which you can install the normal way.
```
npm i @xenova/transformers
```

You can then import and use as follows: 
```js
import {AutoTokenizer} from '@xenova/transformers';
let tokenizer = await AutoTokenizer.from_pretrained('TehVenom/Pygmalion-7b-Merged-Safetensors')
console.log(tokenizer('Hello world').input_ids)
```


Or you can import from a CDN:

```html
<script type="module">
    import { AutoTokenizer } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers/dist/transformers.js';
</script>
```

Outputs a `Tensor` with the following data:
```
{
  data: [1, 15043, 3186],
  dims: [1, 3],
  size: 3,
  type: "int64"
}
```

---

This is much more similar to the standard HF `from_pretrained` syntax. Closing the issue now :)

**Comment by josephrocca** [comment]
Brilliant!

**Comment by xenova** [comment]
Happy to help :) It will take a little longer to get the llama models themselves running in the browser via ONNX, but feel free to suggest other tokenizers I can add.

**Comment by josephrocca** [comment]
@xenova Looks like there's some sort of minor bug related to pages served on localhost (unrelated to Normalizer stuff, but I figured it might not be worth its own issue). This code works fine on non-localhost tabs:
```js
let { AutoTokenizer } = await import("https://cdn.jsdelivr.net/npm/@xenova/transformers@2.0.0-alpha.0/dist/transformers.js");
let tokenizer = await AutoTokenizer.from_pretrained("https://huggingface.co/TehVenom/Pygmalion-7b-Merged-Safetensors/resolve/main");
```

But if I run on a page that's served to localhost, then I get this error:

![image](https://github.com/xenova/transformers.js/assets/1167575/3f3091e2-7a74-4d0e-a12d-21c6f5b9ae78)

It seems to be adding `https://huggingface.co` to the start of the URL and also adding `resolve/main`, so it ends up requesting:
```
https://huggingface.co/https://huggingface.co/TehVenom/Pygmalion-7b-Merged-Safetensors/resolve/main/resolve/main/tokenizer_config.json
```

**Comment by josephrocca** [comment]
Ah, missed that - please forgive me and my feverish haste to implement this :sweat_smile:

(I realise now that I was testing the above code in the browser console of huggingface.co, since I just happened to have that tab open, and the full URL version that I posted in my above message actually works there, somehow. So it's not a localhost vs non-localhost situation, it's huggingface.co vs non-huggingface.co that was causing my confusion)
