### ISSUE TITLE
[Bug] Add note about breaking change (version upgrade 1.4.3 to 2)

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#114]
Congrats to version 2! 🎉 

I'd just like to throw in that a note somewhere would be useful that the new version breaks sites written for the "old" logic of v1.4.3. 

This

`<script src="https://cdn.jsdelivr.net/npm/@xenova/transformers/dist/transformers.min.js"></script>`

doesn't work anymore but instead you need to specify the version with 

`<script src="https://cdn.jsdelivr.net/npm/@xenova/transformers@1.4.3/dist/transformers.min.js"></script>`.

This fixed my broken sites ad-hoc. Else, people will probably be able to find this issue and fix it themselves :)

**Comment by xenova** [comment]
I think the best option would be to provide versioned examples/links, so that when users copy-paste example code, nothing should break.

I'll write a script that will update those links on each release.
