### ISSUE TITLE
[Bug] Davlan/bert fails in demo

### ISSUE THREAD

**Issue by rg3h** [xenova/transformers.js#116]
**Describe the bug**

uncaught promise error when using https://xenova.github.io/transformers.js/ 
and selecting the Token classification w/ Davlan/bert-base-multilingual-cased-ner-hrl

Task:
**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

go to https://xenova.github.io/transformers.js/ 
Select the Token classification w/ Davlan/bert-base-multilingual-cased-ner-hrl option from the drop down
Select "Generate" button
Nothing appears to happen and developer window reports:
caught (in promise) Error: token_ids must be a non-empty array of integers.
    at Function.decode (worker-ed2ef37e.js:1790:46739)
    at worker-ed2ef37e.js:1791:944
    at Array.map (<anonymous>)
    at token_classification (worker-ed2ef37e.js:1791:906)
    at async worker-ed2ef37e.js:1790:127237

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I was hoping to see the resulting token ids for the demo.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: not sure, it is whatever your  demo page is running on 18May2023
- 
- Browser (if applicable):  I was running Brave
- Operating system (if applicable): Windows 10
- Other:

**Additional context**
*Add any other context about the problem here.*

The translation demo does work, so other aspects of this awesome library are working.

**Comment by xenova** [comment]
Good catch - thanks! I thought I tested all the demos after migrating the demo-site, but looks like I missed this one :) Fixing now.

**Comment by xenova** [comment]
Demo back up and running - just need to fix the decoding for the numbers (should be 2016, not 2 0 1  6)
![image](https://github.com/xenova/transformers.js/assets/26504141/33d30bbc-62fc-4ace-97aa-c9064cfde07c)

**Comment by rg3h** [comment]
Thanks xenova -- looking forward to it!

**Comment by xenova** [comment]
Live in v2.0.1 👍 
https://www.npmjs.com/package/@xenova/transformers/v/2.0.1
