### ISSUE TITLE
TypeError: quantize_dynamic() got an unexpected keyword argument 'activation_type'

### ISSUE THREAD

**Issue by spencekim** [xenova/transformers.js#12]
When running the script: 
```
python ./scripts/convert.py --model_id philschmid/flan-t5-base-samsum --from_hub --quantize --task seq2seq-lm
```

I get the following error:
```
TypeError: quantize_dynamic() got an unexpected keyword argument 'activation_type'
```

It works fine without the --quantize argument.

**Comment by xenova** [comment]
Hi! This is a problem I also ran into, and the way to fix it is to downgrade onnxruntime to version 1.10.0

I've put listed some other requirements in the requirements.txt file here: https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt

**Comment by xenova** [comment]
Actually, I think I can just remove that keyword argument. This should mean the conversion script will work with later versions of onnxruntime (like 1.14.1)

**Comment by flatsiedatsie** [comment]
I saw the same error just now, having followed the tutorial in the documentation.. somewhat. This is on a Macbook Pro M1.

```
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'
```

I started with a git clone.
```
git clone https://github.com/xenova/transformers.js.git
cd transformers.js
```

Using `python -m scripts.convert --quantize --model_id Norod78/gpt-fluentui-flat-svg` from the `transformers.js` folder resulted in:
```
No module named scripts.convert
```

Then I moved into the script directory, and (longer story shorter) tried this:

```
python3 convert.py --quantize --model_id Norod78/gpt-fluentui-flat-svg
```

That seemed to work initially, but only created a single .onnx file called `model.onnx`, which I believe is a full 32bit flavour.

The script then generated an error:
```
 The exported model was saved at: models/Norod78/gpt-fluentui-flat-svg
Quantizing:   0%|                                                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File ".../scripts/convert.py", line 545, in <module>
    main()
  File ".../scripts/convert.py", line 521, in main
    quantize([
  File ".../scripts/convert.py", line 294, in quantize
    quantize_dynamic(
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'
```

Removing `--quantize` only created the same 32bit model. It also shows a warning:
```
The ONNX export succeeded with the warning: The maximum absolute difference between the output of the reference model and the ONNX exported model is not within the set tolerance 1e-05:
```

After some searching online I also tried to manually install the latest version of optimum:
```
python -m pip install git+https://github.com/huggingface/optimum.git
```

But that had no effect.
