### ISSUE TITLE
[Question] Basic Whisper Inference vs Speed of Demo Site

### ISSUE THREAD

**Issue by jpg-gamepad** [xenova/transformers.js#122]
Hello, I love the library~ thanks for making it!

I am trying to use the Whisper inference method displayed on the demo site, but it's running really slow, 
It's taking me about 20 seconds to run it locally vs a few seconds on the demo site.

Is there some magic behind the scenes that I'm missing?

I'm just running a simple post message and listening for the updates:
``` 
worker.postMessage({
    task: 'automatic-speech-recognition',
    audio: file,
    generation: {
       do_sample: false,
       max_new_tokens: 50,
       num_beams: 1,
       temperature: 1,
       top_k: 0
    }
});

worker.addEventListener('message', event => {
    const data = event.data;
    if(data.type === 'update') {
        let elem = document.getElementById("whisper");
        elem.value = data.data
    }
});
```

**Comment by jpg-gamepad** [comment]
Okay, I'm reopening, this question because it turns out it wasn't an issue with it being local, as I'm now getting the performance dip again online. I'm scratching my head as to what I am doing to make it run 5x slower.

I might try running it in an Electron app in the morning and see if it's still happening there.

This is my code:
```
const worker = new Worker(new URL('./worker.js', import.meta.url), {
  type: 'module',
});

async function transcribeAudio() {
  const sampling_rate = 16000;
  const audioContext = new AudioContext({ sampleRate: sampling_rate })
  const arrayBuffer = await (await fetch('./jfk.wav')).arrayBuffer()
  let testblob = await audioContext.decodeAudioData(arrayBuffer);

  worker.postMessage({
    task: 'automatic-speech-recognition',
    audio: testblob.getChannelData(0),
    generation: {
        do_sample: false,
        max_new_tokens: 50,
        num_beams: 1,
        temperature: 1,
        top_k: 0
    },
  });
}

worker.addEventListener('message', event => {
  const data = event.data;
  if(data.type === 'update') {
      let elem = document.getElementById("whisper");
      elem.value = data.data
  }
});
```

**Comment by jpg-gamepad** [comment]
I think it has to do with me refreshing too many times. It's working smoothly again after restarting my browser.

**Comment by xenova** [comment]
Hmmm... 👀 Glad to see if's somewhat resolved now... since it's a little difficult to diagnose the exact problem 😅 Are you using any build tools? I've tested with vite and webpack.

**Comment by jpg-gamepad** [comment]
I am just using the webpack version of the worker.js file.

However, I've decided to transfer this over to Electron since the models are quite large.
If I run into the issue again I will reopen this question and add more details.

Thank you for your time!

**Comment by xenova** [comment]
Sounds good! Remember to check out the example electron application: https://github.com/xenova/transformers.js/tree/main/examples/electron

Hopefully that helps 🤗

**Comment by jgw96** [comment]
I know this issue is closed, but just wanted to say that I have also run into what sounds like this issue, also while using Whisper. I am also  using http-server as my dev server, with vite for bundling. I am going to try some other simple dev servers.
