### ISSUE TITLE
convert.py script exits with message `Killed`

### ISSUE THREAD

**Issue by dkogut1996** [xenova/transformers.js#13]
When running the following:
`python3.9 ./transformers.js/scripts/convert.py --model_id google/flan-ul2 --from_hub --quantize --task seq2seq-lm-with-past `   

I receive the following:                                                                                                                      
```
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████| 784/784 [00:00<00:00, 86.3kB/s]
Downloading (…)model.bin.index.json: 100%|█████████████████████████████████████████████████████████| 67.5k/67.5k [00:00<00:00, 3.05MB/s]
Downloading (…)l-00001-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.69G/4.69G [00:54<00:00, 85.5MB/s]
Downloading (…)l-00002-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.97G/4.97G [01:02<00:00, 79.1MB/s]
Downloading (…)l-00003-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.97G/4.97G [01:05<00:00, 75.9MB/s]
Downloading (…)l-00004-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.96G/4.96G [01:08<00:00, 72.5MB/s]
Downloading (…)l-00005-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 5.00G/5.00G [01:02<00:00, 79.5MB/s]
Downloading (…)l-00006-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.93G/4.93G [01:32<00:00, 53.3MB/s]
Downloading (…)l-00007-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 5.00G/5.00G [01:39<00:00, 50.4MB/s]
Downloading (…)l-00008-of-00008.bin: 100%|█████████████████████████████████████████████████████████| 4.93G/4.93G [02:10<00:00, 37.9MB/s]
Killed 
```
Subsequent runs of the script will simply output `Killed` after about 15s.

Is there something I can do to fix this? I am running ubuntu 18.04 on x86 arch.

**Comment by xenova** [comment]
Oh wow... I've never converted such a large model before. Behind the scene, the conversion script calls HuggingFace's optimum library for converting to ONNX (https://github.com/huggingface/optimum), and I'm inclined to believe this is a problem with their library. Perhaps it tries to load the full model into memory, and you run out of memory while trying to convert? So, I would recommend trying to convert using their script to see if it also happens there. (And if so, you can open an issue there)

On another note, what do you plan to use the model for? WASM (the tech needed to run the model in the browser) uses a 32-bit address space (meaning max model size of 4GB). That said, when their WebGPU backend is released (in April), it will most likely support larger models.

**Comment by dkogut1996** [comment]
You're right, exporting to onnx using optimum directly produces the same `Killed` error.

I actually hadn't known about the 4 gb limitation, so I won't really need to continue trying to integrate it. I was mostly just trying to experiment with various models.

Thank you!
