### ISSUE TITLE
[Feature request] Code examples for each pipeline in the docs

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#134]
### Reason for request
I've spent the last 15 minutes trying to find out how to use the `zero-shot-image-classification`, and have come to the conclusion that there should be simple example snippets for each pipeline. This is probably already on the roadmap, but there wasn't an issue for it so I'm adding this just in case.

I think the best way to do this would be to add another column to the "Supported tasks/models" table which links to a simple "getting started" code snippet for each task. There would ideally be a list of Hugging Face models that are supported too.

### Additional context
This is likely not necessary, but regarding my specific search, just to give you some perspective (on the user experience of a 1x developer 😅), I first found [this](https://huggingface.co/tasks/zero-shot-image-classification) via the [Supported tasks/models](https://github.com/xenova/transformers.js#supported-tasksmodels), but this gives a Python example:

![image](https://github.com/xenova/transformers.js/assets/1167575/39cc065a-f7f6-4daa-993d-2bd88db282c4)

I wasn't sure how to pass in the images (e.g. url vs blob), or how the named parameters maps to transformers.js's style (my default assumption is that all python named parameters should be within an object/POJO as the final parameter, after the positional parameters).

So then I thought - ah, I'll just go to the web demo and inspect the code, but I couldn't find a link to the web demo in the github anymore (can this be added back?). While Googling about I did manage to find [this example](https://github.com/xenova/transformers.js/issues/56#issuecomment-1489490468) of zero-shot *text* classification, which was helpful.

So I eventually managed to find [this page](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.ZeroShotImageClassificationPipeline):

![image](https://github.com/xenova/transformers.js/assets/1167575/7c4021fb-89c8-4d02-8286-71ce0ea7bb99)

But the `._call(images, candidate_labels, options)` is not clickable, so I'm still not sure what the images array (I assume it's an array) should contain.

My next step is to guess (try blob, url), otherwise I'll dig into the code here on github. **Edit**: So, it does indeed take a URL, so long as CORS headers allow, of course.

**Comment by xenova** [comment]
https://github.com/xenova/transformers.js/commit/0ecf9606be756b53af2c51627ea27447418cff5b Fixes the "jump to content" issue. 👍

**Comment by xenova** [comment]
Finally got around to adding code examples for each pipeline! 👍 
https://huggingface.co/docs/transformers.js/api/pipelines

**Comment by josephrocca** [comment]
@xenova Nice!! Can a link be added to each example in the "Supported tasks/models" table? Something like this:

![image](https://github.com/xenova/transformers.js/assets/1167575/a654dc58-bcc3-43d6-b6af-e714078b4033)

The existing links in the first column point to a page with Python code examples, and I think the actual pipelines doc page itself is a bit intimidating for newbies. I can submit a pull request with this if you like.

Alternatively (or in addition to the above), it'd be *very* cool if the existing links - e.g. https://huggingface.co/tasks/conversational had a toggle/tab on the code snippets to change switch from Python to JS.

**Comment by xenova** [comment]
> and I think the actual pipelines doc page itself is a bit intimidating to navigate for newbies. 

Yeah, this is unfortunately due to how the JSDocs are auto-generated 😅 

> The support table is a nice "starting point" for people to explore the library I think. I can submit a pull request with this if you like.

That would be appreciated! 🤗 

> Alternatively (or in addition to the above), it'd be very cool if the existing links - e.g. https://huggingface.co/tasks/conversational had a toggle/tab on the code snippets to change switch from Python to JS.

I think this would be a good idea later down the line when the library has support for all tasks 😇 ... hopefully soon!
