### ISSUE TITLE
I get this Unexpected token '??='

### ISSUE THREAD

**Issue by Zenyker** [xenova/transformers.js#141]
Just install this happens 3 time in 3 files I fix030s180m***n123456 it but the other error

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /Users/greeksfarrier/Desktop/AI/test/node_modules/@xenova/transformers/src/utils/hub.js

**Comment by xenova** [comment]
Yes, like I said, it's quite difficult to debug without knowing more information about your setup. My guess is that you are using quite an old version of node/npm. Can you check with `node -v` and `npm -v`?

**Comment by Zenyker** [comment]
your right I am using nvm and was in a older version, sorry for that, thanks
