### ISSUE TITLE
React translation error

### ISSUE THREAD

**Issue by escottgoodwin** [xenova/transformers.js#142]
I created a new react app with create react app and then just copied over the App.js and worker.js (and lint file) from your react translator example with the nllb-200-distilled-600M model.

However, I get the model loading error - 'Unexpected token '<', "<!DOCTYPE "... is not valid JSON'

Not sure what the issue is.

**Comment by xenova** [comment]
This is most likely because it is trying to load the models locally first, and I assume you didn't download the model files from [here](https://huggingface.co/Xenova/nllb-200-distilled-600M/tree/main)? You can confirm this by inspecting your network tab.

If you don't want to host the models locally, then you can add the following code to worker.js:

```js
import { pipeline, env } from "@xenova/transformers";

// Disable local models
env.allowLocalModels = false;
```

**Comment by escottgoodwin** [comment]
You mean pre-download them?

I used the exact same worker file as your example. How does that work and
why is this not working in my app. Is there a difference between your
example code and a basic new react app?

**Comment by escottgoodwin** [comment]
here is the code:

https://github.com/escottgoodwin/transformer_translate

**Comment by xenova** [comment]
> I used the exact same worker file as your example. How does that work and
why is this not working in my app. Is there a difference between your
example code and a basic new react app?

The default behaviour is the first try the local model files, and then fallback to remote model files (if local models are not found). You can you open your network tab in the browser to make sure that the fallback request is made.

**Comment by xenova** [comment]
Please confirm whether this is still an issue, or did the above setting fix this?

**Comment by escottgoodwin** [comment]
I just switched to developing in vite. I think it has something to do with
different handling of environment variables in vite and cra apps.

**Comment by xenova** [comment]
Gotcha! 👍  iirc, create-react-app has been deprecated, and I've been loving using vite lately! So, I'll close this issue for now, but feel free to reopen or create a new issue if you have any other questions.

**Comment by Swaraj9** [comment]
Hello, I've been getting the same error. Initially I was using create-react-app but switched to vite after seeing this thread, but still getting the same error. I also tried the nextJS example but received the same error there as well.

**Comment by iamsorenl** [comment]
I have been unable to work around this issue locally but once I hosted it (I opted for firebase) the issue went away.

**Comment by erkkimon** [comment]
Same here, I tried with Ionic / React / Vite, but got this same error. Here is the simple component which causes incalid JSON error:

```
import './ExploreContainer.css';
import { pipeline, env } from '@xenova/transformers';
import { IonButton } from '@ionic/react';

env.allowRemoteModels = true;

interface ContainerProps { }

const ExploreContainer: React.FC<ContainerProps> = () => {
  const handleClick = async () => {

    let translator = await pipeline('translation', 'Xenova/nllb-200-distilled-600M');

    let result = await translator('I like to walk my dog.', {
      src_lang: 'eng_Latn',
      tgt_lang: 'ell_Grek'
    });

    let result2 = await translator(result[0].translation_text, {
      src_lang: 'ell_Grek',
      tgt_lang: 'eng_Latn'
    });
  }
  return (
    <div id="container">
      <IonButton onClick={handleClick}>Hello</IonButton>
    </div>
  );
};

export default ExploreContainer;
```

**Comment by xenova** [comment]
@erkkimon As stated above, please try:
```js
env.allowLocalModels=false;
```
Note that you need to clear browser clash.

**Comment by erkkimon** [comment]
@xenova Thanks! I also tried that one but it didn't help alone. This code was one of my multiple approaches. :)

However, just as a note for everyone who bumps into this ticket, the solution seems to be in [this ticket.](https://github.com/xenova/transformers.js/issues/366) 

So for the record, I tried Ionic / Vite / React, NextJS and pure React (npx create-react-app), and I always bumped into the same problem. In all those cases the solution from the linked ticket seems to work:

```
env.allowLocalModels = false;
env.useBrowserCache = false;
```

This is obviously a workaround as stated in the linked ticket, but it works well as a temporary fix. At least it makes developing apps possible until there is a solution which doesn't force user to download the model every time again.

Thanks @xenova for developing this great library and I guess this problem will be fixed as people dig deeper into the problem in the linked ticket.

Cheers!

**Comment by xenova** [comment]
@erkkimon Can you please detail how you are ensuring that browser cache has been emptied (without setting `env.useBrowserCache = false;`)? My suspicion is that you are not doing it correctly. It should be:
1. Open devtools
2. Go to "Application" tab
3. Go to "Storage"
4. Click "Clear site data"

**Comment by erkkimon** [comment]
That did the trick, thanks @xenova!

**Comment by adrianlyjak** [comment]
pretty sure what happens here is that vite has the somewhat annoying behavior of serving `index.html` for all unhandled request paths with its dev server. It's somewhat difficult to disable. What makes this even messier with transformers, is that first request for the html response gets cached, so its somewhat hard to debug, since it stops showing up in the network log after the first request. Perhaps would be neat if transformers.js purged the cache if it failed to parse the json

**Comment by CntrlX** [comment]
i need help with this i need to loiad a local file andthere fore i cant use the env.allowLocalModels = false;
how can i solve this
