### ISSUE TITLE
[Bug] 'ERR_DLOPEN_FAILED' when trying to run on server

### ISSUE THREAD

**Issue by mahi83** [xenova/transformers.js#145]
**Describe the bug**
*A clear and concise description of what the bug is.*

I am trying to create a server using express and I get an error that say 'ERR_DLOPEN_FAILED'. Please keep in mind I'm new to this JS world. 

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

I have an `index.ts` file with the following code:

```
import express from 'express';
import { mean_pooling } from '@xenova/transformers';

export const queryEmbedder = express.Router();

class QueryPipeline {
  static modelName = '';
  static instance;

  static async getTokenizerInstance(progress_callback) {
    if (this.instance === null) {
      let { env, AutoTokenizer } = await import('@xenova/transformers');

      // NOTE: Uncomment this to change the cache directory
      this.instance = await AutoTokenizer.from_pretrained(
        this.modelName,
        (progress_callback = { progress_callback })
      );

      return this.instance;
    }
  }

  static async getModelInstance(progress_callback) {
    if (this.instance === null) {
      // Dynamically import the Transformers.js library
      let { env, AutoModel } = await import('@xenova/transformers');

      this.instance = await AutoModel.from_pretrained(
        this.modelName,
        (progress_callback = { progress_callback })
      );
    }

    return this.instance;
  }
}


var response;
queryEmbedder.get('/embed', async (req, res) => {
  const query = req.body.text;
  const { text } = query;

  let response_token_output;
  let response_model_output;
  if (text) {
    const tokenizer = await QueryPipeline.getTokenizerInstance();
    const embedder = await QueryPipeline.getModelInstance();
    response_token_output = await tokenizer(text);

    response_model_output = await embedder(response_token_output);

    const last_hidden_state = response_model_output['last_hidden_state'];
    const attention_mask = response_token_output['attention_mask'];

    response = { embedding: mean_pooling(last_hidden_state, attention_mask) };

    res.statusCode = 200;
  } else {
    const response = { error: 'Bad request' };
    res.statusCode = 400;
  }

  // Send the JSON response
  res.end(JSON.stringify(response));
});
```

My routes.ts files has the following:
```
import express from 'express';
export const routes = express.Router();
routes.use('/queryembedding', queryEmbedder);

```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The server doesn't even start. I have successfully run other non transformer related routes. Its just this page in particular that is throwing an error when initializing. 

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

The following is the error I get when i run `npm run api`. 
```
asset server.js 2.38 MiB [emitted] (name: server) 1 related asset
asset 5ae005dd35998766eb7289963206f4fc.node 275 KiB [emitted] (auxiliary name: server)
asset 9f92b6e3c34a390e5737ac41938d7846.node 272 KiB [emitted] (auxiliary name: server)
asset b71adfbc8af61218b3c766da73d7c46b.node 260 KiB [emitted] (auxiliary name: server)
asset 3462c20bc014c41980e4f72130762bea.node 237 KiB [emitted] (auxiliary name: server)
asset 7a5758ad5230899ec828dc5919d020f6.node 210 KiB [emitted] (auxiliary name: server)
asset 332b2ce9fd36cb77421d6f263b9d702f.node 183 KiB [emitted] (auxiliary name: server)
asset 51389bf580de2f6b64793af1d22aeef4.node 168 KiB [emitted] (auxiliary name: server)
webpack compiled successfully in 2713 ms

node:internal/modules/cjs/loader:1310
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
```
Error: dlopen(/Users/fkarim3/projects/benefits_search_abyss/products/api/build/3462c20bc014c41980e4f72130762bea.node, 0x0001): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: <8D033380-CA2C-3909-BB25-D901E6321665>

**Environment**
- Transformers.js version:2.1.1
- Browser (if applicable):Chrome
- Operating system (if applicable): MacOS Ventura 13.3.1
- Other:

**Additional context**
*Add any other context about the problem here.*

I am not even sure if the functions run because I get an error at the beginning. Any comments would be appreciated. If you think the code could be written better, I would take any tips.

**Comment by xenova** [comment]
Your code looks okay and I don't see any glaring issues, so I don't think this is a Transformers.js-related issue. What version of node and npm are you using?

**Comment by xenova** [comment]
Please let me know if you are still experiencing this issue. Otherwise, I will close this issue as it seems to be a problem with your environment.
