### ISSUE TITLE
[Bug] Chunk Timestamp [1] is not rounded

### ISSUE THREAD

**Issue by PushpenderSaini0** [xenova/transformers.js#159]
**Describe the bug**

While using **Whisper Web** and trying to export to JSON i have encountered a bug.
The timestamp[1] does not have proper rounder values like the timestamp[0].

I have verified this is not a bug due to exporting to JSON, I believe that wrong variable is used when setting chunk.timestamp[1] 

Please check this line [here](https://github.com/xenova/transformers.js/blob/480417118044f407bd5f0feca9008d1f31e82888/src/tokenizers.js#L2615)
```js
chunk.timestamp[1] = time;
```

This should be equal to  `rounded_time`
```diff
- chunk.timestamp[1] = time;
+ chunk.timestamp[1] = rounded_time;
```

**How to reproduce**

You can reproduce this bug by using the default audio link provided and then exporting to JSON

[Website](https://huggingface.co/spaces/Xenova/whisper-web)
[Audio](https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/ted_60.wav)

**Expected behavior**

timestamp[1] should have rounder values like the timestamp[0]

**Logs/screenshots**

![image](https://github.com/xenova/transformers.js/assets/54404738/32f8bc02-eca6-4efa-af80-fcbadda7302e)

**Environment**

- Transformers.js version: 2.2.0

**Additional context**

I have tried to make changes to the code.
```diff
- chunk.timestamp[1] = time;
+ chunk.timestamp[1] = rounded_time;
```
This change does fix the problem.

![image](https://github.com/xenova/transformers.js/assets/54404738/9b5942d5-8077-49ee-9b6d-428e1c9c6f84)

You can assign this bug to me, and I can raise a PR with this fix.

**Comment by xenova** [comment]
Yep you're right! This should be `rounded_time`. Feel free to open a PR!
