### ISSUE TITLE
[Question] Embeddings for the Entire Document

### ISSUE THREAD

**Issue by hadminh** [xenova/transformers.js#176]
Hi Thanks for all the effort, I really appreciate it. I enjoy coding in JS and do all things in JS.  
Is it a good idea to load the entire json document to get embeddings? What tokenizer should I choose? I have a tone of valuable information in my key and value pairs? or should I craft a sentence from the document?

```json
{
  "id": 2053926,
  "city": "New York",
  "user_id": 3578165,
  "price": 75,
  "native_currency": "USD",
  "price_native": 75,
  "price_formatted": "$75",
  "lat": 40.854397081884706,
  "lng": -73.93876393071385,
  "country": "United States",
  "name": "air conditioned room w/ great view",
  "smart_location": "New York, NY",
  "has_double_blind_reviews": false,
  "instant_bookable": false,
  "bedrooms": 1,
  "beds": 1,
  "bathrooms": 1,
  "market": "New York",
  "min_nights": 1,
  "neighborhood": "Washington Heights",
  "person_capacity": 3,
  "state": "NY",
  "zipcode": "10033",
  "user": {
    "user": {
      "id": 3578165,
      "first_name": "Benjamin",
      "has_profile_pic": true
    }
  },
  "address": "Pinehurst Avenue, New York, NY 10033, United States",
  "country_code": "US",
  "cancellation_policy": "flexible",
  "property_type": "Apartment",
  "reviews_count": 14,
  "room_type": "Private room",
  "room_type_category": "private_room",
  "picture_count": 18,
  "_geoloc": {
    "lat": 40.854397081884706,
    "lng": -73.93876393071385
  },
  "objectID": "507205000"
}
```

**Comment by xenova** [comment]
Most (if not all) of the models used for embeddings have been trained on sentences, so yes, it probably is wise to format it in a sentence-like way.

However, it mainly depends on your use-case and what you're going to be using the embeddings for. Just as an example, formatting the GPS coordinates as part of your text sentence will be meaningless to the model.

Just from a quick glance at your data, I assume you're building some semantic search application for rentals, so you'll probably be able to generate sensible embeddings by substituting just a few keys into your sentence: mainly just "name" actually. All other keys seem to either be numbers (price) or locations (text/gps) and I think there are better ways to handle search for these types of data. That said, if you really wanted to, you can substitute these terms into your generated description. For example: 

```
Title: {air conditioned room w/ great view}
Description: {3} bedroom and {1} bathroom {apartment} located at {Pinehurst Avenue, New York, NY 10033, United States} with a {flexible} cancellation policy.
```

Let me know if you have any other questions!

**Comment by hadminh** [comment]
Thanks for the insightful answer. Yes, as you correctly guessed, I am trying to build both semantic and similarity search. I wasn't sure how the tokenization process works and thought that property fields or keys are generally useful in the tokenization process. 

I noticed the "vectorizePropertyName": true [option](https://weaviate.io/developers/weaviate/tutorials/modules#retrievers--vectorizers) and in this [link](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-contextionary#classproperty-names), Weaviate shows how they tokenize the entire object, including the keys, and try to split camel case or snake case to understand the semantics. This is interesting and a bit of a mystery because it suggests that current models seem to understand JSONL, JSON, CSV, etc.
