### ISSUE TITLE
[Question] Running transformers.js in a browser extension

### ISSUE THREAD

**Issue by davidtbo** [xenova/transformers.js#180]
Hello,

I'm trying to build a chrome extension that uses Transformers.js. When I try to import it in the background worker script, I first get an error that says process is not available, because apparently someone decided browser plugins shouldn't use process.env anymore. I found a solution that said to put   
```
define: {
    'process.env': {}
}
```
in my vite.config.js, which worked to get me past that, but the next error is:
```
Error: Dynamic require of "../bin/napi-v3/undefined/undefined/onnxruntime_binding.node" is not supported
```
Has anyone gotten this working in a browser environment yet? I saw a video about tensorflow.js in the browser, but I'd prefer to use transformers.js because you already provided me with an example of how to get it to behave like Sentence Transformers. :)

**Comment by davidtbo** [comment]
I got this example working:
https://github.com/xenova/transformers.js/tree/main/examples/extension

Now I just need to apply the example to my own code. Hopefully I should be good to go now.

**Comment by xenova** [comment]
Great! 🥳 I do intend to update the example even more - as when I originally made it, I remember having some issues with the background thread "timing out" and going to sleep 😅... It's probably something very simple that I was missing, but when I have some time again, I'll get it working properly!

Maybe you'll be able to figure it out - and if you do, please feel free to share here!

**Comment by xenova** [comment]
I've been busy updating the example: https://github.com/xenova/transformers.js/tree/extension/examples/extension and will hopefully merge into main after a bit more testing and optimization. Let me know if that helps!
