### ISSUE TITLE
[Bug] Transformers.js loads the wrong model configuration after running npm run build

### ISSUE THREAD

**Issue by JEF1056** [xenova/transformers.js#185]
**Describe the bug**
*A clear and concise description of what the bug is.*

After compiling a create-react-app project with `npm run build`, transformers.js attempts to load models as if they were encoder-only when the model configuration defines them as encoder-decoder

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

1. Implement an app similar to https://github.com/xenova/transformers.js/tree/main/examples/react-translator, but with `create-react-app`
2. Use a T5 model (encoder-decoder)
3. add `env.useBrowserCache = false;` to see what files are being loaded
4. Start an instance `npm start`. Confirm it's working and loading
    - You should see something like this in the browser network. Note that it's loading `encoder_model_quantized.onnx` and `decoder_model_merged_quantized.onnx`: ![image](https://github.com/xenova/transformers.js/assets/22546776/96cd0b8d-8fc7-4802-aaec-016fb08bcf7b)
5. Start an instance with `npm run build && serve -s build`
    - This is what the browser network receives. Note it's loading `mode_quantized.onnx`, as if it were loading a encoder-only model: ![image](https://github.com/xenova/transformers.js/assets/22546776/697bb966-936b-48cf-9f57-353fdbff7dce)
   - Logs. I've logged a few important things, inclusing that it is corrctly reading the model type from the config. The service worker is newly cleared: ![image](https://github.com/xenova/transformers.js/assets/22546776/8731dea8-22eb-4436-92dd-750ad9349532)

**Expected behavior**
*A clear and concise description of what you expected to happen.*
I expect `npm start` and `npm run build` to produce results that are identical

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: 2.3.1
- Browser (if applicable): Chrome 114.0.5735.199 (Official Build) (64-bit)
- Operating system (if applicable):
- Other:

**Additional context**
A few notes form my own debugging:
- `npm start`, e.g. the dev command, works fine and does load the correct model configuration
- In the network requests, transformers.js attempts to load a `model_quantized.onnx` instead of `encoder_model_quantized.onnx` and `decoder_model_merged_quantized.onnx`
- Replacing [this line here](https://github.com/xenova/transformers.js/blob/aceab9bf3d1be9dadf6601b8f775e519376258e3/src/models.js#L629) with `let modelType = Seq2SeqModelType` fixes the problem
- Logging `MODEL_CLASS_MAPPING.get(this.name)` in `from_pretrained()` results in `sam`, and deleting the `sam` model entry from `MODEL_CLASS_TYPE_MAPPING` [here](https://github.com/xenova/transformers.js/blob/aceab9bf3d1be9dadf6601b8f775e519376258e3/src/models.js#L2681) logs `detr`, which is just the second to last class type mapping. I'm guessing the bug lies somewhere around here

**Comment by xenova** [comment]
Hi there 👋  Thanks for the detailed bug report! My hunch is that this is somehow related to create-react-app, as I have used vite without any problems.

The automodel to class mapping is dynamically built, based on a few different types of filters, and I assume that CRA is trying to do some optimization with this.

afaik, CRA has been deprecated, so, adding support specifically for it might be a waste of time 😅. Can you maybe try again but with vite? Or perhaps another question: is there a reason you still need to use CRA?

**Comment by JEF1056** [comment]
Huh, I didn't realize CRA is depreciated; good to know! The project I'm working on was built with CRA and i've been migrating it from pure TF.js to Transformers.js (to great results, btw!)

I think it'd be worthwhile for me to try migrating the app to Vite for futureproofing's sake, since I've found a workaround that temporarily will resolve my problem.

**Comment by xenova** [comment]
> I think it'd be worthwhile for me to try migrating the app to Vite for futureproofing's sake, since I've found a workaround that temporarily will resolve my problem.

Sounds good! 🚀 Feel free to reopen or create a new issue if you have any further questions 👍
