### ISSUE TITLE
all-MiniLM-L6-v2 vector lengths

### ISSUE THREAD

**Issue by unkn-wn** [xenova/transformers.js#193]
Hey, is there any way to programmatically set fix the vector embedding array lengths to a certain length? I was using https://huggingface.co/Xenova/all-MiniLM-L6-v2 with nodejs and every input I ran through the pipe gave a different length, and it would be nice to be able to keep it consistent.

**Comment by xenova** [comment]
Remember to normalise and apply mean pooling to the embeddings as follows:


Same issue as: https://github.com/xenova/transformers.js/issues/151

**Comment by unkn-wn** [comment]
Thanks! I wasn't able to find that before; really helps a lot

**Comment by xenova** [comment]
No worries! :) Feel free to ask any more questions or check out the documentation for other examples: https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.FeatureExtractionPipeline
