### ISSUE TITLE
[Feature request] Support Private Models

### ISSUE THREAD

**Issue by fozziethebeat** [xenova/transformers.js#198]
**Support Private Models**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

With the python libraries, you can download models and tokenizers from the hub by either providing an auth token or being logged in via `huggingface-cli login --token=....`.

Ideally transformers.js would enable the same support when a user is locally logged in and the environment has the auth token in scope.

I've tried this just now to access `meta-llama/Llama-2-13b-hf` which requires a license agreement and can only be downloaded with a token.

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

This puts model access on part with the python libraries so that private models can be accessed.

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by fozziethebeat** [comment]
Note, a way to deal with this is to use [hf_hub_download](https://github.com/xenova/transformers.js/issues/198) to download the files locally and then update [env](https://github.com/xenova/transformers.js/issues/198) to point to those local models.

But ideally this would just work.

**Comment by xenova** [comment]
Sure, I can add this 👍

Due to security concerns with leaking access tokens to the client, this will only be allowed in node.js when `process.env` is accessible.

**Comment by xenova** [comment]
I made a PR for it here: https://github.com/xenova/transformers.js/pull/202 Please let me know what you think 👍

**Comment by fozziethebeat** [comment]
Yeah that looks perfect.  I 100% agree this should only happen on node servers.  This looks like what I was going to try and hack in.

**Comment by xenova** [comment]
Sweet 👍  and here is the documentation for usage: https://moon-ci-docs.huggingface.co/docs/transformers.js/pr_202/en/guides/private

I'll get to merging soon
