### ISSUE TITLE
[Bug] Tokenizing with Llama 2 model freezes

### ISSUE THREAD

**Issue by fozziethebeat** [xenova/transformers.js#199]
**Describe the bug**
*A clear and concise description of what the bug is.*

I manually downloaded the new `meta-llama/Llama-2-7b-hf` model to my local disk and loaded it up with transformer.js tokenizer.  When trying to tokenize a very particular string, tokenization halts and spins forever.  Checking top, the node process is doing _something_ but it's not clear what.  I've let this run for at least 10 minutes and it doesn't finish.

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

```js
const breaking_string = `They wrote the following:
Momentum in your online business comes from (crystal) clarity around who you serve and how you’re going to serve them. 🤔   Over on The Art of Paid Traffic podcast today, I’m pumped to share with you an interview with one of my Accelerator Group Coaching students, Trish Taylor. 🤗                                                                                           Trish is a stylist (and former celebrity stylist at that), coach and brand style expert for business women, teaching them to own their worth and show up in an authentic and meaningful way. 🙌🏼                                                        sI asked Trish to come on the show because she’s gone through what I think is a super relatable transformation in her business -- that of working with clients 1-on-1 to now scaling her business online and creating online courses and programs. 👩🏼🏼 YOU
<200d>💻
As you’ll hear, it wasn’t until she had clarity on who exactly she serves that she was able to clearly create offers that serve this audience that she’s so passionate about.  ♀️
You\'ll also hear how she’s using a quiz and challenge launch, why I don't think she should count out webinars, the metrics she should be paying attention to when evaluating her ad campaigns, and so much more. 📊
Follow the link in my bio to give today's episode a listen and I’d love to hear from you…  are there any transformations YOU
 RE wanting to make in your business? 👇🏼                                                                                  *
. . . . . . . . .`;

export default async (argv: any) => {
  const { env, AutoTokenizer, PreTrainedTokenizer } = await eval(
    "import('@xenova/transformers')"
  );
  if (process.env.LOCAL_TRANSFORMER_PATH) {
    env.localModelPath = process.env.LOCAL_TRANSFORMER_PATH;
  }
  const pretrained = await AutoTokenizer.from_pretrained(
    "meta-llama/Llama-2-7b-hf"
  );
  const tokens = pretrained.encode(breaking_string);                                                                          console.log(tokens.length);
};
```

Pre-steps requires downloading the model locally and setting LOCAL_TRANSFORMER_PATH.

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The string should be tokenized.  The same string can be tokenized with `mosaicml/mpt-7b-8k`.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: ^2.4.1
- Browser (if applicable):
- Operating system (if applicable): MacOS
- Other: Node v18.16.0

**Additional context**
*Add any other context about the problem here.*

**Comment by xenova** [comment]
I will test once I gain access to the llama-v2 models. In the meantime, I tested with the llama-v1 tokenizer and it works as intended, so it is most likely due to some change between tokenizer versions.

**Comment by xenova** [comment]
Thanks! By the way, can you confirm that the repo you're testing with contains the required files: tokenizer.json and tokenizer_config.json?

I've tested with a version on the hub with those files and it seems to work just fine?

```html
<script type="module">
    import { AutoTokenizer } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.4.1';
let text = `you…  `


const pretrained = await AutoTokenizer.from_pretrained(
    "daryl149/llama-2-7b-chat-hf"
  );
const tokens = pretrained.encode(text);       
console.log(JSON.stringify(tokens));
// "[1,366,30098,259]"
</script>
```
JSFiddle demo: https://jsfiddle.net/jep6wky5/2/

**Comment by fozziethebeat** [comment]
I confirmed this.

I downloaded the model by doing

```
from huggingface_hub import snapshot_download
snapshot_download("meta-llama/Llama-2-7b-hf", local_dir="/Users/fozziethebeat/devel/models/meta-llama/Llama-2-7b-hf")
```

And manually verified there's both `tokenizer.json` and `tokenizer_config.json`.  Both look normal to me and on spot checking seem to match what's on the hub.

Let me try the chat tokenizer. it could be the 7b tokenizer has an issue

**Comment by fozziethebeat** [comment]
I checked `meta-llama/Llama-2-7b-chat-hf` and it had the same problem.  It's possible that downloading it locally is causing a problem but not sure how to rule that out just yet.

**Comment by xenova** [comment]
I have now got access to the models, but everything is working correctly for me. Can you confirm that transformers.js is loading models from the correct folder?

```js
import { env } from '@xenova/transformers';
env.localModelPath = '/path/to/local/models/';
```

See [docs](https://huggingface.co/docs/transformers.js/api/env) for more information.

**Comment by fozziethebeat** [comment]
I've ruled out a few possible explanations.  In my first runs I was running a typescript command that was being compiled by our tsconfig.

I've simplified the breaking example down to a simple mjs file:

```js
import { env, AutoTokenizer, PreTrainedTokenizer } from "@xenova/transformers";

(async () => {
  const breaking_string = `you…  `;
  env.localModelPath = "/Users/fozziethebeat/devel/models/";
  const pretrained = await AutoTokenizer.from_pretrained(
    "meta-llama/Llama-2-7b-chat-hf"
  );
  const tokens = pretrained.encode(breaking_string);
  console.log(tokens.length);
})();
```

This is still breaking for me even without typescript and even with setting the local path manually.

**Comment by xenova** [comment]
Does this demo work in your browser: https://jsfiddle.net/jep6wky5/2/ ? It might be an issue with mac + node.js

**Comment by fozziethebeat** [comment]
That fiddle works for me. So it's likely something with running on mac & node.js.

**Comment by xenova** [comment]
I unfortunately do not have a mac to test with, so it's a little difficult to help debug. Are you certain it freezes at `.encode()`? Does this happen with other llama tokenizers like [hf-internal-testing/llama-tokenizer](https://huggingface.co/hf-internal-testing/llama-tokenizer)? Are there no error logs?

If you are able to, I would appreciate if you cloned the repo and tested from source. In that way, you can trace through the code to see exactly where it freezes.

**Comment by fozziethebeat** [comment]
Yes that's my next step.  I just woke up in my timezone so I'll start debugging more deeply.

**Comment by fozziethebeat** [comment]
Okay, I've figured out some things.  I think it has something to do with text normalization, which for sure happens different in node and in the browser.  

I found out that by manually changing `tokenizer.json` to have a pre_tokenizer such as 

```
  "pre_tokenizer": {
    "type": "ByteLevel",
    "add_prefix_space": false,
    "trim_offsets": true,
    "use_regex": true
  },
```

(This is pulled from Mosaic's configs)

The problem goes away entirely.  The tokenization is ugly but things work out.

I also found that by trimming away the trailing whitespace also happens to fix the problem.  Apparently the `… ` is some atrocious character that gets handled differently on some platforms and without a pre tokenizer, it passes through and may or may not get handled right.

The problem I diagnosed pretty deeply is that the while loop in the `bpe` method goes into an infinite loop.  The word and pair variables keep getting the same value because the trailing whitespace remains and the `...` value never gets found since it's not in the vocab.

**Comment by fozziethebeat** [comment]
Inspecting some other tokenization results, this isn't viable.  it corrupts most strings.  Need to figure out another fix.

**Comment by xenova** [comment]
Wow that's really strange?! 👀 Especially considering that it works in the browser (Mac/windows/Linux) as well as in node windows/Linux, but not for node mac.

Just out of curiosity, if you try the same with the python library, does it work correctly?

I don't want to speak too soon, but you might have found a bug with the mac version of node.js 👀. If you're able to test later versions of node.js, that could also be very useful! Thanks for investigating this!

**Comment by fozziethebeat** [comment]
Looking more closely at the [reference transformers implementation](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/tokenization_llama.py) I think the problem is due to not using sentencepiece.  The real LlamaTokenizer uses the binary model file with sentencepiece and lets that do all the hard work.  I know sentencepiece has lots of special handling for issues like this, and there's probably some key trick that's not in the BPE javascript class.

**Comment by xenova** [comment]
Right, I had to reimplement the sentencepiece tokenisation, and up until now it had been working just fine 👀. The strange part is that it works on windows and Linux, but not mac, which I think is the thing to focus on. 

In particular, the BPE algorithm is a direct translation of the HF implementation, which is sometimes used as a fallback in certain cases.

**Comment by fozziethebeat** [comment]
Yeah it is weird that this one character sequence breaks things.  I confirmed this problem doesn't trigger in python when using the same repo.  So somewhere sentencepiece normalizes this problem away.

**Comment by xenova** [comment]
If you're able to edit the code, does calling .trim() on the bigram (or wherever needed) fix the problem?

**Comment by fozziethebeat** [comment]
Let me confirm trimming the bigram or tokens works, but generally yes, trimming away the whitespace seemed to fix the problem (before calling `encode`).

**Comment by fozziethebeat** [comment]
Yes, doing `let bpe_token_list = this.bpe(token.trim()).split(" ");` fixes the problem entirely.

**Comment by xenova** [comment]
Or perhaps adding a limit of 2 to the split function in the BPE algorithm?

**Comment by fozziethebeat** [comment]
yeah, that also seems reasonable.

**Comment by xenova** [comment]
Okay great 👍 I'll do some more testing tomorrow, and add the string you found as a unit test.

**Comment by jlia0** [comment]
Is it possible to run LLaMA models (7B) using onnxruntime-web tho? What about quantized models using GPTQ?

**Comment by xenova** [comment]
> Is it possible to run LLaMA models (7B) using onnxruntime-web tho?

Not yet, but there is [amazing work](https://twitter.com/daken_/status/1681094181018644482) being done by @dakenf to get these larger models running! Stay tuned for more from him!

**Comment by dakenf** [comment]
7B is 13gb and Chrome seems to have a hard limit of 16gb per tab, so most likely not. Only if all layers would be loaded to GPU but it's not possible yet. Quite a number of ONNX OPs are not implemented for WebGPU

I've seen that some folks could allocate up to 32gb in Firefox but my patched runtime does not work there. Anyway, we're slowly getting there but I cannot say when it would be possible.

**Comment by xenova** [comment]
The folks over at https://webllm.mlc.ai/ seem to have got it working 👍  I think they just adapted their vicuna code to use the llama2 weights. Very cool stuff!
![image](https://github.com/xenova/transformers.js/assets/26504141/4def910f-3f08-4149-936c-a41b3196f30a)

**Comment by dakenf** [comment]
I guess q4 in the name means 4 bit quantization? If the size is reduced to at least 7-8gb then it will fit easily. They have an amazing thing but it comes with completely different approach: they compile the model into an optimized webassembly executable. I'm trying to make it work with unmodified onnx models

**Comment by jlia0** [comment]
> https://webllm.mlc.ai/

WebLLM/MLC-LLM is using a different infrastructure which is based on [Apache TVM Unity](https://tvm.apache.org/), which is a deep learning compiler and accelerator, but more optimized and powerful I think.

**Comment by xenova** [comment]
> Yes, doing `let bpe_token_list = this.bpe(token.trim()).split(" ");` fixes the problem entirely.

@fozziethebeat I've been looking into this for the past ~4 hours, trying to understand the exact reason behind this 😅. And yes, although the above does fix it (and surprisingly not break any of the other unit tests), I'd like to try figure our where and why exactly there is an infinite loop in the first place.

So, if you could possibly test (and maybe add a bunch of debug statements) to 1. determine which `while` loop the infinite loop occurs in, and 2. which condition is never met that causes the infinite loop

Also, does this happen with other unknown characters followed by a space (not just the ellipsis)?

**Comment by fozziethebeat** [comment]
I did some analysis.  We get to a point to the BPE infinite while loop where:

1. bigram becomes `  ` (two white spaces)
2. first becomes `` (empty string)
3. second becomes `` (empty string)
4. word becomes `[▁you,…, , ]`
5. Then when we do `j = word.indexOf(first, i);`, `j` naturally becomes `-1` because it can't find the empty string and we push all of `word` into `new_word`.  Thus creating an infinite loop where `word` never changes.

Why does `bigram` become `  `? It's because pairs gets reduced to `[▁you …,…  ,   ]` and the first two strings don't exist in the vocab due to the strange character, but `  ` is in the vocab (surprisingly?), so that gets picked as the only suitable bigram.

**Comment by xenova** [comment]
The Metaspace pretokenizer should convert all spaces to `▁`, making `[ '▁you', '…', '▁▁' ]` (which is how it appears on my side). Printing out the starting pairs gives:
`[ '▁ y', 'y o', 'o u', 'u …', '… ▁', '▁ ▁' ]`

Are you saying that, if you add a print statement to pairs before the first `while (true)` loop, you get actual spaces in the pairs?

**Comment by xenova** [comment]
I was able to test with a mac user (node 18.16.0; os 13.4.1), and strangely enough, everything worked correctly 😅 ... Could you maybe provide a bit more information about your system (e.g., what mac OS version?). The fact that the tokenization works in your browser (as well as on other windows/linux/mac systems) leads me to believe that this is a problem with your current setup, and perhaps some outdated library?)

**Comment by fozziethebeat** [comment]
Okay this must be my machine doing something *completely* ridiculous.  

```js
      const r = breaking_string.replaceAll(" ", "_");
      expect(r).toBe("you…__");
```
Fails.  `r` stays the same as `breaking_string`.  Doing it in my browser works just fine.  So there' _must_ be something wrong with my setup.  Let me figure out which detail breaks this.

**Comment by xenova** [comment]
🤯🤯🤯 I knew it! Although I'm happy that my guess was correct (after like 6 hours of debugging haha), it's very strange that it's not working 🤔. Assuming you haven't changed anything with your node/npm installation (I mean, who would?), this might be a bug with node.js itself 👀. In fact, I think you should raise an issue on their GitHub repo.

**Comment by fozziethebeat** [comment]
Nope, I think node is fine.  I think this is actually a different case of character encodings.  The whitespaces I'm working with aren't actually the standard white space (utf-8 value 32).  They're instead some other whitespace character (utf-8 sequence 194, 160).  I think this is maybe a Japanese half-width whitespace that renders the same and is often NFC nornmalized to the standard whitespace character.

Pasting it here is probably what's dropping the bad character for anyone trying to replicate this.

I checked that if I do `replaceAll` by copying the character, it works as expected.

I also did this to inspect the bytes:

```
      const breaking_string = "you…  ";
      let utf8Encode = new TextEncoder();
      console.log(utf8Encode.encode(breaking_string));
```

And it printed 

```
    Uint8Array(10) [
      121, 111, 117, 226,
      128, 166, 194, 160,
      194, 160
    ]
```

Which is not what you'd expect

So I think the fix is to always run the strings through a utf-8 normalizer to normalize out these almost-but-not-quite valid characters.  That's probably why the MPT tokenizer and sentencepiece libraries handle this properly, they do NFC normalization.

**Comment by xenova** [comment]
That's so interesting, because that's the first thing I thought about: I copied your message, checked the bytes, and indeed, they were 32. GitHub seems to have converted them to the standard space character.

Let me add that string as a unit test and do some more tests.

**Comment by fozziethebeat** [comment]
Yeah, I think browsers by default will normalize this character out.  Having worked on sentencepiece, it's a notorious character that _always_ causes surprising problems.

**Comment by xenova** [comment]
So using the actual string, I was able to reproduce this issue 👍. Funnily enough, NFC normalization doesn't fix this 👀 
```js
"\u0079\u006F\u0075\u2026\u00A0\u00A0".normalize('NFC') === "\u0079\u006F\u0075\u2026\u00A0\u00A0"
true
```

I'll do some testing to see what the best way to fix this is.

**Comment by xenova** [comment]
Okay I've gone down a rabbit hole of sentencepiece and the llama tokenizer and crazily enough, `\xa0\xa0` IS ACTUALLY IN the llama tokenizer (id=8655). This means that the real problem comes in - not during normalization - but when splitting on whitespace in the BPE algorithm:

https://github.com/xenova/transformers.js/blob/86e68bf9c0d0733567b7ffb9b51bacdfe7cb9204/src/tokenizers.js#L551

must be replaced with `let [first, second] = bigram.split(' ')`...

and 
https://github.com/xenova/transformers.js/blob/86e68bf9c0d0733567b7ffb9b51bacdfe7cb9204/src/tokenizers.js#L489
must be replaced with  `this.merges = config.merges.map(x => x.split(' '));`

--- 

I'm making a commit for this; and it should fix everything :)

**Comment by fozziethebeat** [comment]
Oh good grief that's wild.  Glad a fix finally got figured out tho and a way to replicate/test it.  This was pretty maddening.

**Comment by xenova** [comment]
Opened a PR for it here: https://github.com/xenova/transformers.js/pull/208! As a last sanity check, do you mind checking that everything works as intended? I'll merge after that (and once tests pass 🚀)

> Oh good grief that's wild. Glad a fix finally got figured out tho and a way to replicate/test it. This was pretty maddening.

100%! 😓 Thanks so much for your help!
