### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by okpatil4u** [xenova/transformers.js#20]
Any plans to add webgpu support ?

**Comment by xenova** [comment]
Absolutely! ONNX runtime web is planning to add support for it in April this year (https://github.com/microsoft/onnxruntime/issues/11695), so, when it does, I will be adding support for it!

**Comment by okpatil4u** [comment]
That's freaking amazing. Waiting for the patch :).

Should I keep this issue open ?

**Comment by xenova** [comment]
> That's freaking amazing. Waiting for the patch :).
> 
> Should I keep this issue open ?

I can't wait either haha! I think I can close it for now, but perhaps pin it (since I imagine others will have the same question).

**Comment by sanbuphy** [comment]
> Absolutely! ONNX runtime web is planning to add support for it in April this year ([microsoft/onnxruntime#11695](https://github.com/microsoft/onnxruntime/issues/11695)), so, when it does, I will be adding support for it!

Thank you very much! love for onnxruntime!

**Comment by jlia0** [comment]
Just a follow up on this, any updates? I noticed there is a [repo](https://github.com/mlc-ai/web-llm) doing similar stuff. Really looking forward to a big boost in speed. Also, is onnxruntime-node still faster than onnxruntime-web with WebGPU support? 5x speed up sounds too amazing to not be fixed. :(

**Comment by xenova** [comment]
Hi! Yes, onnxruntime-web just merged a PR into main which adds webgpu support! (see [here](https://twitter.com/xenovacom/status/1650634015060156420)).

While we wait for a full release, I'll do some local building and testing.

**Comment by jozefchutka** [comment]
hi @xenova , any promising updates? Is this THE issue to subscribe to to get notified about upcoming release with webgpu ?

**Comment by hadnet** [comment]
Alright, it's already July 7th, any updates on the progress of this?
