### ISSUE TITLE
[Question] Translation models

### ISSUE THREAD

**Issue by jedLahrim** [xenova/transformers.js#200]
@xenova is there a model that do the text translation that have lighter weight i mean with minimum size?

**Comment by xenova** [comment]
Do you know which languages you want to translate to/from?

**Comment by jedLahrim** [comment]
this one i used is so heavy 1.17gb in the folder

**Comment by jedLahrim** [comment]
@xenova im gonna inputing languages by me testing in postman

**Comment by xenova** [comment]
Feel free to look on the [Hub](https://huggingface.co/models?pipeline_tag=translation&sort=downloads&search=Helsinki-NLP) for translation models. I would recommend Helsinki-NLP/opus models.

**Comment by jedLahrim** [comment]
can we load the model from his source like this model: https://huggingface.co/Xenova/nllb-200-distilled-600M/tree/main

**Comment by jedLahrim** [comment]
hello @xenova i just get back from vacation monday and i built this little api :                                                                              ```
const axios = require('axios');
const options = {
  method: 'POST',
  url: 'https://text-translation6.p.rapidapi.com/xenova/translate',
  headers: {
    'content-type': 'application/json',
    'X-RapidAPI-Key': '4fb84e5862msh93493191641aa67p1730ebjsn9a38755eabe6',
    'X-RapidAPI-Host': 'text-translation6.p.rapidapi.com'
  },
  data: {
    text: 'this is a test request',
    from: 'ENGLISH',
    to: 'ARABIC'
  }
};

try {
	const response = await axios.request(options);
	console.log(response.data);
} catch (error) {
	console.error(error);
}
```
in order to simplify the translation (from ,to) +200 languages n place of waiting until the 1.18Gb model loaded in your machine and after use the .cache folder to loded from cache i built this api to send a simple request to aws and gcp servers to do the translation job in a flexible way.

**Comment by jedLahrim** [comment]
hello @xenova i just get back from vacation monday and i built this little api : 

```
const axios = require('axios');
const options = {
method: 'POST',
url: 'https://text-translation6.p.rapidapi.com/xenova/translate',
headers: {
'content-type': 'application/json',
'X-RapidAPI-Key': '4fb84e5862msh93493191641aa67p1730ebjsn9a38755eabe6',
'X-RapidAPI-Host': 'text-translation6.p.rapidapi.com'
},
data: {
text: 'this is a test request',
from: 'ENGLISH',
to: 'ARABIC'
}
};

try {
const response = await axios.request(options);
console.log(response.data);
} catch (error) {
console.error(error);
}
```                                                       

in order to simplify the translation (from ,to) +200 languages n place of waiting until the 1.18Gb model loaded in your machine and after use the .cache folder to loded from cache i built this api to send a simple request to aws and gcp servers to do the translation job in a flexible way.

**Comment by jedLahrim** [comment]
link in rapidapi
[](https://rapidapi.com/jolix1235/api/text-translation6)

**Comment by jedLahrim** [comment]
link in rapidapi

[](https://rapidapi.com/jolix1235/api/text-translation6)

**Comment by jedLahrim** [comment]
link in rapidapi

`https://rapidapi.com/jolix1235/api/text-translation6`

**Comment by jedLahrim** [comment]
> const axios = require('axios');
> const options = {
> method: 'POST',
> url: 'https://text-translation6.p.rapidapi.com/xenova/translate',
> headers: {
> 'content-type': 'application/json',
> 'X-RapidAPI-Key': '4fb84e5862msh93493191641aa67p1730ebjsn9a38755eabe6',
> 'X-RapidAPI-Host': 'text-translation6.p.rapidapi.com'
> },
> data: {
> text: 'this is a test request',
> from: 'ENGLISH',
> to: 'ARABIC'
> }
> };
> 
> try {
> const response = await axios.request(options);
> console.log(response.data);
> } catch (error) {
> console.error(error);
> }

**Comment by xenova** [comment]
Cool! 🙌

I'll close the issue since you seem to have found a solution.
