### ISSUE TITLE
[Question] Is transformers.js expected to work with react native?

### ISSUE THREAD

**Issue by Wehzie** [xenova/transformers.js#205]
I've naively been trying to run the transformers js library via react native on android.
Note that onnxruntime-react-native explicitly supports react native, however the transformers.js package depends only on onnxruntime-web and onnruntime-node.
Importing the transformers.js works fine, however as I try to load a model, I receive the error `import.meta` is currently unsupported from `transformers.js`.

It would be super convenient to be able to use pipes directly without needing to interface without onnxruntine-react-native directly! If not supported yet, what would need to be done?

**Comment by xenova** [comment]
Hi there! 👋 React Native is not officially supported (yet), but we do aim to get it working in the future! Fortunately, there is an open fork/PR here: https://github.com/xenova/transformers.js/pull/118, and it seems to works!

**Comment by Wehzie** [comment]
Thanks for the info! Looking forward to it.
