### ISSUE TITLE
[Question] Output always equal to Input in text-generation

### ISSUE THREAD

**Issue by AndreEneva** [xenova/transformers.js#206]
I tried a different types of input and always get the output equals the input... What I'm missing?

```
const answerer = await pipeline('text-generation', 'Xenova/LaMini-Cerebras-590M');

let zica = await answerer(`Based on this history:
André de Mattos Ferraz is an engineering manager in Rio de Janeiro, Brazil. He has worked in systems development in the oil sector, working in several areas of the oil/gas life cycle: Exploration, Reservoir, and Production. He also worked on data science projects for predicting failures of water injection pumps, forecasting water filter saturation (SRU), and analyzing vibrations.

What are André tech skills?`);
console.log(zica)
```

![image](https://github.com/xenova/transformers.js/assets/139378356/f35b3c9a-fdcc-4258-ac0d-0a2e8de83877)

**Comment by xenova** [comment]
The original model can be found here: https://huggingface.co/MBZUAI/LaMini-Cerebras-590M and according to their README, it has been instruction finetuned and requires specific prompting. Here's the python version:

```py
# pip install -q transformers
from transformers import pipeline

checkpoint = "{model_name}" 

model = pipeline('text-generation', model = checkpoint)

instruction = 'Please let me know your thoughts on the given place and why you think it deserves to be visited: \n"Barcelona, Spain"'

input_prompt = f"Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:"

generated_text = model(input_prompt, max_length=512, do_sample=True)[0]['generated_text']

print("Response", generated_text)
```

**Comment by mfandre** [comment]
@xenova but how I can pass those extra parameters (max_length)? And I tried using this ###instructions and the result was the same.

**Comment by xenova** [comment]
You can do so as follows:
```js
await answerer(input_prompt, {
    max_length: 512,
});
```

**Comment by mfandre** [comment]
Worked! you are super @xenova !

**Comment by xenova** [comment]
Great! If you need it, here is the full list of generation parameters: https://huggingface.co/docs/transformers.js/main/en/api/utils/generation#new-generationconfigkwargs

Some of them might not yet be implemented (e.g., `max_time`), but the popular ones (like `max_new_tokens` or `do_sample` should work!
