### ISSUE TITLE
[Bug] Assertion error when importing in React app

### ISSUE THREAD

**Issue by eklavyaisabird** [xenova/transformers.js#207]
**Describe the bug**
*A clear and concise description of what the bug is.*

I get this after putting only this line in my code: 
`import { pipeline } from "@xenova/transformers";`

<img width="514" alt="Fail to Compil BART MNLI Transjs" src="https://github.com/xenova/transformers.js/assets/77216995/0708144d-943c-4330-9fc2-e02a27c6af69">

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

These are my only other imports. The file is a React component file.
```
import React, { useEffect, useState } from "react";
import "./Feed.css";
import Post from "./Post";
import TweetBox from "./TweetBox";
import db from "../firebase";
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

i didnt expect an error to occur from simply importing it. It snot an import error or anything. I dont really know what it is and theres no documentation.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: not sure, just did `npm i @xenova/transformers`
- Browser (if applicable): Chrome
- Operating system (if applicable): MacOS

**Comment by eklavyaisabird** [comment]
18.2.0

**Comment by xenova** [comment]
It's a little difficult to tell from your error messages, but are you perhaps using typescript + react? If so, you can bypass the additional compiler checks to the library by adding this to your tsconfig.json:

```
{
    "compilerOptions": {
        "skipLibCheck": true,
        ...
    },
    ...
}
```

**Comment by eklavyaisabird** [comment]
I am only using js files unfortunately

**Comment by xenova** [comment]
And what build tool are you using? Vite, webpack, ... ? If possible, can you please provide more information (e.g., are you using something like create react app?)

**Comment by eklavyaisabird** [comment]
Got it, is there a way to change it from CRA to Vite? 

Thank you for all your help!
