### ISSUE TITLE
[Bug] Problem working with Next.js

### ISSUE THREAD

**Issue by james0248** [xenova/transformers.js#210]
**Describe the bug**
I am trying to use `transformers.js` in my Next.js project, but I have problem using it in the new `app` directory.

**How to reproduce**
Import any model from `@xenova/transformers` and initialize it. I have a [test repository](https://github.com/james0248/transformers-test) for this error.

`app/page.tsx`
```typescript
import { PreTrainedTokenizer } from '@xenova/transformers'

export default function Home() {
  const tokenizer = new PreTrainedTokenizer({}, {})
  /* extra stuff */
}
```

**Expected behavior**
The application starts without any problem.

**Logs/screenshots**
```
- error ./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
./node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/onnxruntime-node/dist/binding.js
./node_modules/onnxruntime-node/dist/backend.js
./node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./app/page.tsx
```

**Environment**
- Transformers.js version: `2.4.1`
- Browser (if applicable): Safari
- Operating system (if applicable): MacOS Ventura (13.3.1)
- Other:

**Additional context**
### What I've tried
1. The solution from #98 (Ignore `.node` files)
I've tried making webpack to ignore `.node` files but as pointed out in #183, `Cannot find module 'onnxruntime-node'` error appears. I've also tried installing `onnxruntime-node` separately. Following is the config used:
`next.config.js`
```javascript
module.exports = {
    reactStrictMode: true,
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        // Modify the webpack configuration
        config.plugins.push(
            // Ignore node-specific modules when bundling for the browser
            new webpack.IgnorePlugin({
                resourceRegExp: /^onnxruntime-node$|^node:/,
            })
        );

        return config;
    },
};
```

3. Use `node-loader` 
I have added a config to `next.config.js` for web pack to handle `.node` files. However, it seems like webpack is having trouble finding the path to the `.node` file. 
```
- error node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node (5:0) @ eval
- error Error: node-loader:
Error: dlopen(/path/to/project/.next/server/app//_next/332b2ce9fd36cb77421d6f263b9d702f.node, 0x0001): tried: '/path/to/project/.next/server/app//_next/332b2ce9fd36cb77421d6f263b9d702f.node' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/path/to/project/.next/server/app//_next/332b2ce9fd36cb77421d6f263b9d702f.node' (no such file), '/path/to/project/.next/server/app//_next/332b2ce9fd36cb77421d6f263b9d702f.node' (no such file)
    at eval (webpack-internal:///(rsc)/./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node:6:9)
    at (rsc)/./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node (/path/to/project/.next/server/app/page.js:2667:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at webpackContext (/path/to/project/.next/server/app/page.js:33:9)
    at eval (webpack-internal:///(rsc)/./node_modules/onnxruntime-node/dist/binding.js:10:133)
    at (rsc)/./node_modules/onnxruntime-node/dist/binding.js (/path/to/project/.next/server/app/page.js:2540:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./node_modules/onnxruntime-node/dist/backend.js:20:19)
    at (rsc)/./node_modules/onnxruntime-node/dist/backend.js (/path/to/project/.next/server/app/page.js:2529:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42) {
  digest: undefined
}
null
```

Following is the config used:
`next.config.js`
```javascript
module.exports = {
    reactStrictMode: true,
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.node = {
            __dirname: false,
        };
        config.module.rules.push({
            test: /\.node$/,
            loader: 'node-loader',
            options: {
                name: "[contenthash].[ext]"
            },
        });
        return config;
    },
};
```

I have checked out #183 however the issue closed with a solution **not** using the `app` directory. It would be great to have a working example using the app directory, since the future updates in Next will be recommending that way. 
I've noticed you are working on a Next.js example. I would be happy to work on it together if you have any trouble.

**Comment by xenova** [comment]
Hi there 👋 Yeah, I agree... I should make a Next.js example 😅 I read through some of the webpack documentation, and after a bit of testing, it looks like the setting we need is [`config.resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias)

Does something like this work for you?

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    webpack: (config) => {
        // Ignore node-specific modules when bundling for the browser
        // https://webpack.js.org/configuration/resolve/#resolvealias
        config.resolve.alias = {
            ...config.resolve.alias,
            "sharp$": false,
            "onnxruntime-node$": false,
        }
        return config;
    },
};

module.exports = nextConfig;
```

**Comment by xenova** [comment]
I spent a few hours just making a really simple next.js sample application (https://github.com/xenova/transformers.js/pull/211) w/ the new App router. Let me know if that works and I'll merge into main.

**Comment by james0248** [comment]
I've checked your PR and it works great! My issue also seems to be solved so I think it will be okay to close this issue.
However, I added the `next.config.js` part you uploaded and encountered the following error:
```
- error node_modules/@xenova/transformers/src/env.js (60:0) @ eval
- error TypeError: Cannot read properties of undefined (reading 'wasm')
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
    at eval (./app/tokenizer/page.tsx:7:78)
    at (sc_client)/./app/tokenizer/page.tsx (/path/to/project/.next/server/app/tokenizer/page.js:391:1)
    at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
null
```
I moved all my `transformers.js` related code to a client side rendered page and it seems to be working fine. (But I keep getting the error message)
It seems like it's a problem caused by ignored the `onnxruntime_node` package on the server side, so I don't think it is 100% fixable.

**Comment by callmephilip** [comment]
yeah, i am also curious how to get this to work server side

**Comment by xenova** [comment]
Okay I'll look into maybe extending the template/demo to show how to do both client-side and server-side ML. Will keep you updated 👍

**Comment by callmephilip** [comment]
thanks!

**Comment by xenova** [comment]
Okay I've created two demo applications:
1. Client-side (i.e., in-browser) inference: https://github.com/xenova/transformers.js/tree/next-template/examples/next-client ([tutorial](https://moon-ci-docs.huggingface.co/docs/transformers.js/pr_211/en/tutorials/next)).
2. Server-side inference: https://github.com/xenova/transformers.js/tree/next-template/examples/next-server (tutorial coming soon) via the new For more information, see https://nextjs.org/docs/app/building-your-application/routing/router-handlers

In both cases, I use the new app router (Next.js >= 13).

Let me know what you think, then I'll merge into main.

**Comment by callmephilip** [comment]
@xenova it seems to be working as expected server side (both locally and when deployed). i guess the part i was missing is `serverComponentsExternalPackages` in `next.config`. Nice catch!

**Comment by xenova** [comment]
Here's the demo app for those interested: https://huggingface.co/spaces/Xenova/next-server-example-app

**Comment by sauhaardac** [comment]
Thanks for this work @xenova!

Just wanted to note, I'm running into this error with your `next-server-example-app` when running locally on a M1 Mac device locally:
```
- error ./node_modules/.pnpm/onnxruntime-node@1.14.0/node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
```

Would appreciate any guidance regarding this issue, though I understand if it is difficult to look into/debug if you don't have access to a similar arm64 darwin device.

**Comment by xenova** [comment]
The webpack config should handle this (i.e., ignore bundling onnxruntime-node). Could you try with npm instead of pnpm?

**Comment by sauhaardac** [comment]
@xenova Thanks so much! somehow using `npm` instead of `pnpm` resolved the issue. I'm not sure why that would be... if it works it works I guess though 😄

**Comment by blechatellier** [comment]
@xenova @raunakdoesdev did you find a way to make it to work with pnpm?

**Comment by xenova** [comment]
@blechatellier Unfortunately not. I also, admittedly, don't have much experience with pnpm. That said, this does look like a pnpm issue, so I would recommend opening up an issue in their repo instead. Alternatively, this may be an issue with next.js, since `serverComponentsExternalPackages` is marked as [experimental](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages).

**Comment by thomasgrob** [comment]
> I've checked your PR and it works great! My issue also seems to be solved so I think it will be okay to close this issue. However, I added the `next.config.js` part you uploaded and encountered the following error:
> 
> ```
> - error node_modules/@xenova/transformers/src/env.js (60:0) @ eval
> - error TypeError: Cannot read properties of undefined (reading 'wasm')
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
>     at eval (./app/tokenizer/page.tsx:7:78)
>     at (sc_client)/./app/tokenizer/page.tsx (/path/to/project/.next/server/app/tokenizer/page.js:391:1)
>     at __webpack_require__ (/path/to/project/.next/server/webpack-runtime.js:33:42)
> null
> ```
> 
> I moved all my `transformers.js` related code to a client side rendered page and it seems to be working fine. (But I keep getting the error message) It seems like it's a problem caused by ignored the `onnxruntime_node` package on the server side, so I don't think it is 100% fixable.

Did you get this working at all?

**Comment by cwooldridge1** [comment]
> @xenova Thanks so much! somehow using `npm` instead of `pnpm` resolved the issue. I'm not sure why that would be... if it works it works I guess though 😄

Thanks for this. Was banging my head for an hour. pnpm support would be great. Starting to not get the pnpm hype though as it seems like it has alot of weird issues like this.

**Comment by cwooldridge1** [comment]
Its worth noting that currently in Next.js 14 you cannot use this library in both client side and server side. You have to pick one or else you will get those WASM / binary errors.

For server side you have to have: 
```
//next.config.js
  experimental: {
    serverComponentsExternalPackages: ['sharp', 'onnxruntime-node'],
  },
```
If you are doing client side you have to have:
```
//next.config.js
  webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      sharp$: false,
      'onnxruntime-node$': false,
    };

    return config;
  },
```

You cannot have both configs, chose the one based on where your doing your transforming

**Comment by mouimet-infinisoft** [comment]
> webpack: (config) => {
>     config.resolve.alias = {
>       ...config.resolve.alias,
>       sharp$: false,
>       'onnxruntime-node$': false,
>     };
> 
>     return config;
>   },

Hello everyone,
Thanks for all answers. I am facing the same issue with a different scenario. I am using --turbo to bundle, therefore the webpack configuration for client side seems to be useless. If my assumptions is right. Anyone has faced the same issue that could give me insights or point me in the right direction?

Regards,
Mart

**Comment by desaxce** [comment]
> @blechatellier Unfortunately not (I also don't have much experience with pnpm). That said, this does look like a pnpm issue, so I would recommend opening up an issue in their repo instead. Alternatively, this may be an issue with next.js, since `serverComponentsExternalPackages` is marked as [experimental](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages).
> 
> See [here](https://github.com/vercel/next.js/issues/43433) for a related issue.

To have it work with `pnpm`, I had to put the `serverComponentsExternalPackages` (`onnxruntime-node` and `sharp`) as dependencies in package.json:
```
"dependencies": {
    "@xenova/transformers": "^2.4.2",
    "onnxruntime-node": "1.14.0",
    "sharp": "0.32.6",
    ...
}
```
That way, `pnpm install` puts the two dependencies directly beneath `node_modules` and not just in `node_modules/.pnpm`. I suspect the Next.js `serverComponentsExternalPackages` relies on those directories being direct children of `node_modules`.

**Comment by kungfooman** [comment]
> Clearly not a sustainable solution.

The question is just: do you think `Next.js`, `pnpm` or `transformers.js` should fix something?

To me it just sounds like `pnpm` is cutting corners to feed their "being faster" argument, but I'm not running into this issue, so I don't really know. What do you think, should you open an issue at `pnpm` for a sustainable solution?

**Comment by desaxce** [comment]
> The question is just: do you think `Next.js`, `pnpm` or `transformers.js` should fix something?

`pnpm` optimizes common dependencies by putting them in `.pnpm`, seems good to me.

`Next.js` "should" adjust the experimental `serverComponentsExternalPackages` option for the specific case of indirect dependencies. Like here: `onnxruntime-node` is specified, but it's only seen through `@xenova/transformers`. 

For the time being, specifying `peerDependencies` is fine with me. An additional couple of dependencies to keep an eye on in `package.json`. Every time `@xenova/transformers` updates its dependencies, I'll have to update these two as well. 
```
"peerDependencies": {
    "sharp": "0.32.6",
    "onnxruntime-node": "1.14.0"
}
```

**Comment by lancejpollard** [comment]
These solutions no longer appear to work for Next.js 15.
