### ISSUE TITLE
[Bug] Got errors when using model Xenova/multi-qa-mpnet-base-cos-v1

### ISSUE THREAD

**Issue by dragonman225** [xenova/transformers.js#219]
**Describe the bug**
*A clear and concise description of what the bug is.*

I'm using the model like this

```js
const model = "Xenova/multi-qa-mpnet-base-cos-v1";
const sentenceTransformer = await pipeline("feature-extraction", model);
```

But when running there're errors:

```
Unknown model class "mpnet", attempting to construct from base class.
Malformed class definition. [class PreTrainedModel extends Callable]
file:///.../node_modules/@xenova/transformers/src/models.js:673
            throw Error(`Unable to load model: ${pretrained_model_name_or_path}. Please report this bug at https://github.com/xenova/transformers.js/issues/new/choose.`);
                  ^

Error: Unable to load model: Xenova/multi-qa-mpnet-base-cos-v1. Please report this bug at https://github.com/xenova/transformers.js/issues/new/choose.
```

The model seems to be a valid option as it's found at https://huggingface.co/Xenova/multi-qa-mpnet-base-cos-v1

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

Setup a pipeline with the model:

```js
const model = "Xenova/multi-qa-mpnet-base-cos-v1";
const sentenceTransformer = await pipeline("feature-extraction", model);
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The model should be loaded without errors.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

```
Unknown model class "mpnet", attempting to construct from base class.
Malformed class definition. [class PreTrainedModel extends Callable]
file:///.../node_modules/@xenova/transformers/src/models.js:673
            throw Error(`Unable to load model: ${pretrained_model_name_or_path}. Please report this bug at https://github.com/xenova/transformers.js/issues/new/choose.`);
                  ^

Error: Unable to load model: Xenova/multi-qa-mpnet-base-cos-v1. Please report this bug at https://github.com/xenova/transformers.js/issues/new/choose.
```

**Environment**
- Transformers.js version: 2.4.2
- Browser (if applicable): Node.js v18.4.0
- Operating system (if applicable): macOS 13.4.1 on MacBook Air (M1, 2020)
- Other:

**Additional context**
*Add any other context about the problem here.*

**Comment by xenova** [comment]
Thanks for the report 👍 Will get this fixed... 😃

**Comment by xenova** [comment]
Fixed in https://github.com/xenova/transformers.js/pull/221 (which is now live in [v2.4.3](https://www.npmjs.com/package/@xenova/transformers/v/2.4.3))

**Comment by dragonman225** [comment]
Thank you for the fixing it so quickly!
