### ISSUE TITLE
[Docs] Add example code for zero-shot-classification

### ISSUE THREAD

**Issue by Aschen** [xenova/transformers.js#229]
I have a huge difference in performances when trying to perform a simple classification task. The Python version give better performances than the JS version.

Also, the JS classifier is not able to classify correctly the corresponding texts as "street address".

I'm using `Xenova/bart-large-mnli` in JS and `facebook/bart-large-mnli` in Python.

Here are my results (first 2 texts are a street address):
```bash
$ python bart.py
facebook/bart-large-mnli
0.9975677132606506
0.9981901049613953
0.004343739710748196
0.022633692249655724

$ node bart.js
Xenova/bart-large-mnli
0.4556246405304541
0.5631336436601322
0.6358004417358224
0.6758611902199643
```

**How to reproduce**

Follow this GIST https://gist.github.com/Aschen/cd73b13ae09e5dad5f50e7485bad4d1a

**Expected behavior**

The classifiers results should be approximately the same. In this example, the JS classifier is not able to identify any of the texts as a street address while the Python classifier does it well.

**Environment**
- Transformers.js version: 2.4.1
- Operating system (if applicable): Ubuntu 22

**Comment by xenova** [comment]
Hi there, to get the exact same results, you must use the unquantized version of the model. In your case, replace

```js
let pipe = await pipeline('zero-shot-classification', modelName);
```

with 

```js
let pipe = await pipeline('zero-shot-classification', modelName, { quantized: false });
```

**Comment by vdeturckheim** [comment]
Hey!
Thanks for the quick response!
On my macbook, with ```jslet pipe = await pipeline('zero-shot-classification', modelName, {
    quantized: false
});
```

I am getting 
```
Xenova/bart-large-mnli
0.15272954834526048
0.5874339301398102
0.1241952172402541
0.1940727717263689
```
which is very far still from what I get in Python. Am I missing something else?

Thanks a lot!

**Comment by vdeturckheim** [comment]
Seems the original code is wrong
```
const result = await pipe(text, {
      labels,
    });
```
should be
```
const result = await pipe(text, labels);
```

**Comment by xenova** [comment]
Oh right! Totally missed that haha. [Here's](https://huggingface.co/docs/transformers.js/api/pipelines#zeroshotclassificationpipelinecalltexts-candidatelabels-options-codepromiseampltobjectarrayampltobjectampgtampgtcode) the relevant section in the docs for the zero-shot-classification pipeline.

![image](https://github.com/xenova/transformers.js/assets/26504141/e0d7cbec-7e44-4183-9f70-6356dd4a43a0)

Although, I should definitely add a snippet of example usage to the docs, like some of the other pipelines.

**Comment by vdeturckheim** [comment]
I tried to look to update the doc, but it requires me more than 2 brains cycle to think where it would go - might circle back if I have some free time in the week :)

**Comment by vdeturckheim** [comment]
🙇 
It seems it would take me more than a couple brain cycles to PR the doc here. I might do it if I have some free time in the week :)

**Comment by xenova** [comment]
> I might do it if I have some free time in the week 

That would be much appreciated! 🤗 ... I'll keep the issue open in the meantime and once we have an example in the docs, I'll close it.

**Comment by Aschen** [comment]
@xenova Can you tell me where the doc is located so I can add an example and close this PR?

**Comment by xenova** [comment]
@Aschen it's part of the JSDoc for the class:

https://github.com/xenova/transformers.js/blob/ebc97223057f0e9057b6ec27e21387434b5479a2/src/pipelines.js#L548-L555

**Comment by xenova** [comment]
[Docs](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.ZeroShotClassificationPipeline) are now live! 🚀
![image](https://github.com/xenova/transformers.js/assets/26504141/2f35aa7f-4f07-4a4d-93c3-d52fe1b81255)

Will make a release shortly too (so you can use deberta models, which as shown above, seem to perform pretty well).

**Comment by vdeturckheim** [comment]
Amazing!
Thanks everyone!

**Comment by xenova** [comment]
> Is there a new release of the lib needed? 

Yes, I still need to release the next version. If you want, you can install from source.

**Comment by vdeturckheim** [comment]
Sounds good, thanks!

**Comment by xenova** [comment]
[v2.5.1](https://www.npmjs.com/package/@xenova/transformers/v/2.5.1) is now live :)

**Comment by vdeturckheim** [comment]
🚀  you're the best (also, don't work too late ;) )
