### ISSUE TITLE
[Feature request] Add support for llama models

### ISSUE THREAD

**Issue by JEF1056** [xenova/transformers.js#231]
**Name of the feature**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

Adding support for the llama models: https://huggingface.co/docs/transformers/model_doc/llama2

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

The llama models, particularly llama2, are pretty popular foundation models for many modern transformers use cases. Being able to run them on node servers or even in the browser would be great! I don't think this model strays too far from the traditional text-generation pipeline (already used by gpt2, gpt-neo, and a few others) so hopefully this is a easy change to make.

**Additional context**
*Add any other context or screenshots about the feature request here.*
I can provide an onnx-converted model if needed!

**Comment by JEF1056** [comment]
Thanks for the quick model support addition! 
I'll test the converted models on onnxruntime-node shortly and post my results here
A sidenote but the 7b models require ~96gb of system ram to convert and quantize

**Comment by xenova** [comment]
> I'll test the converted models on onnxruntime-node shortly and post my results here

Sounds good! 🔥 I've actually never tested a model > 2GB with onnxruntime-node, so, it will be good to know if it works! 😅 

> A sidenote but the 7b models require ~96gb of system ram to convert and quantize

Woah 🤯 If you're using our conversion script, you can disable the validation with `--skip_validation`. From my experience, that's where most RAM is consumed.

**Comment by xenova** [comment]
I've merged my [PR](https://github.com/xenova/transformers.js/pull/232) to add llama/llama2 support, and I will make a release shortly. Just note that you will need to do the >=7B model conversions yourself.
