### ISSUE TITLE
[Docs] Mention demo (GitHub pages) in Readme 

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#233]
I love your old demo page on GitHub pages (https://xenova.github.io/transformers.js/), as one can easily play with the models and copy code if needed.
Is there any reason it's not mentioned anymore (or not more visible) in the Readme? 

(Sorry, added bug label accidentally, should be question instead)

**Comment by xenova** [comment]
Hey! 👋 Yeah I probably should add it back, shouldn't I 😅 ... I think it got lost into the mix when I changed demo link to the docs. Another reason is that I would like to improve the UI to make it much nicer (since as you can tell, it's really old lol).
