### ISSUE TITLE
[Feature request] New conversational models for Transformers.js

### ISSUE THREAD

**Issue by atantos** [xenova/transformers.js#236]
**Conversational Models**

It would be a valuable addition to have Transformers.js support the Llama2 [Llama2](https://huggingface.co/docs/transformers/model_doc/llama2) model.

**Reason for request**
*Why is it important that we add this feature?*

It is important to try it out so that it is possible to create sensible chatbots in a multilingual setting (using other languages than English). This is not possible/recommended based on the already supported models by Transformers.js.

**Comment by xenova** [comment]
I've merged my PR to add llama/llama2 support, but you will need to do the >=7B model conversions yourself.
