### ISSUE TITLE
[Question] Ipynb for ONNX conversion?

### ISSUE THREAD

**Issue by Mihaiii** [xenova/transformers.js#237]
Could you please share the code you're using to convert models to onnx? I know you say in your cards you're using Optimum, but when I try to do it myself, I get much larger onnx files (talking about disk space here) and I don't know what I'm doing wrong.

**Comment by xenova** [comment]
Probably the easiest way is to clone the repo and use our conversion script (in the scripts folder).

```bash
python -m scripts.convert --quantize --model_id <model_name_or_path>
```


Check out the [docs](https://huggingface.co/docs/transformers.js/custom_usage#convert-your-models-to-onnx) for more info.

**Comment by Mihaiii** [comment]
@xenova This is what I did, but I ended up with onnx files that are similar in disk space size with the initial model sizez while your onnx models are smaller.

**Comment by xenova** [comment]
Did you use the `--quantize`` flag?

**Comment by Mihaiii** [comment]
Oh, sorry, you pointed me to some other docs than the ones I was using for Optimum conversion.

My bad and thank you very much! 

Will retry today with your script. Closing.
