### ISSUE TITLE
[Question] Can you list all available models using tranformers.js?

### ISSUE THREAD

**Issue by sambowenhughes** [xenova/transformers.js#238]
Hey 👋 

I was wondering if it's possible to list available models using the `transformers.js` package? 

e.g. 
> pipeline.getAvailableModels()

**Comment by xenova** [comment]
You can search the Hub for models which can be used with transformers.js by selecting "Transformers.js" from the libraries section: https://huggingface.co/models?library=transformers.js

You can also check [this section](https://github.com/xenova/transformers.js#models) of the README to see the list of supported model architectures.

**Comment by xenova** [comment]
Like I said above, I'd recommend searching on the [hub](https://huggingface.co/models?library=transformers.js) for compatible models, but another way is to check out the [supported_models.py](https://github.com/xenova/transformers.js/blob/main/scripts/supported_models.py) file which contains the models that we use for unit testing.
