### ISSUE TITLE
[Model request] Add multilingual-e5-small

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#241]
**Name of the model**
[multilingual-e5-small](https://huggingface.co/intfloat/multilingual-e5-small)

**Reason for request**
At the moment (August 2023) it seems to be the best fit for creating multilingual embeddings in transformers.js as it's small (0.44Gb) and has few dimensions (384). More infos why [here](https://github.com/do-me/SemanticFinder/discussions/32#discussioncomment-6667030).

**Comment by xenova** [comment]
It should already be supported :) https://huggingface.co/Xenova/multilingual-e5-small

**Comment by do-me** [comment]
Argh, my bad. With a type I obviously cannot find the model: 

![](https://github.com/xenova/transformers.js/assets/47481567/aa2c0372-f60d-49d5-9ab7-a15ae9be1407)

Thanks! :)
