### ISSUE TITLE
[Bug] Non-english word-level timestamps

### ISSUE THREAD

**Issue by LostArrows27** [xenova/transformers.js#252]
I'm currently using NextJS with transfomer.js  but it gives me this error when i try the code in your README.md
![image](https://github.com/xenova/transformers.js/assets/97510841/5d08f741-a360-433f-874d-70dbbfb52896)
And this is my code and app's dependencies
![image](https://github.com/xenova/transformers.js/assets/97510841/47756afc-c1f5-4214-9534-fe40b1072c99)
![image](https://github.com/xenova/transformers.js/assets/97510841/462aeea9-b93c-4201-853a-7319f27c752a)

**Comment by LostArrows27** [comment]
Do you guys have any idea how to fix it

**Comment by xenova** [comment]
Hi there. 👋 Please follow the instructions in this tutorial: https://huggingface.co/docs/transformers.js/tutorials/next, as this has been a common problem others have faced (see closed issues too). All you need to do is basically update your webpack config file (depending on whether you want to do client-side or server-side inference.

**Comment by LostArrows27** [comment]
oh i see bro, definitely i will follow that tutorial 1 more time. Thanks so much

**Comment by LostArrows27** [comment]
@xenova I was able to use the transform.js but there's 1 problem, that's i can't detect each word timestamp. I don't know if there's an option that we can pass in the transcriber function to do it. Can you tell me way to do it or is there a list of full parameters in the Transcriber function in automatic-speech-regconition task ?
![image](https://github.com/xenova/transformers.js/assets/97510841/9918c629-56e0-4639-a12a-97e68e676fe6)

**Comment by LostArrows27** [comment]
Sorry for ask you a bit much but I try changing ```return_timestamps``` to ```word``` but it gives me this error though i have ```output_attentions: true``` to the pipeline
![image](https://github.com/xenova/transformers.js/assets/97510841/fba75da2-ee72-402f-a94c-a67737b005e2)
![image](https://github.com/xenova/transformers.js/assets/97510841/dd3ea102-893a-42f3-9592-9179649f0b68)

![image](https://github.com/xenova/transformers.js/assets/97510841/bf5da878-4df3-466a-a791-4a19a28757d1)

**Comment by LostArrows27** [comment]
@xenova I try word-level timestamps when set ```return_timestamp='word'``` with this [audio_file](https://cbvwrikamnjrgcobbmii.supabase.co/storage/v1/object/public/avatar/hyouka.mp3) but its not works. Its still give the same result when i set ```return_timestamp=true```

**Comment by xenova** [comment]
Please make sure you are using the correct model. `revision: 'output_attentions',`

**Comment by LostArrows27** [comment]
I have put it in the pipeline with this model
![image](https://github.com/xenova/transformers.js/assets/97510841/cb96be18-9647-49d2-ad0a-f5bfe963293c)

**Comment by xenova** [comment]
Does this code work for you?
```js
let url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/jfk.wav';
let transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-tiny.en', {
    revision: 'output_attentions',
});
let output = await transcriber(url, { return_timestamps: 'word' });
// {
//   "text": " And so my fellow Americans ask not what your country can do for you ask what you can do for your country.",
//   "chunks": [
//     { "text": " And", "timestamp": [0, 0.78] },
//     { "text": " so", "timestamp": [0.78, 1.06] },
//     { "text": " my", "timestamp": [1.06, 1.46] },
//     ...
//     { "text": " for", "timestamp": [9.72, 9.92] },
//     { "text": " your", "timestamp": [9.92, 10.22] },
//     { "text": " country.", "timestamp": [10.22, 13.5] }
//   ]
// }
```

**Comment by xenova** [comment]
Can you check your package-lock.json to see which version of transformers.js you are using? 2.5.2 is the latest.

**Comment by LostArrows27** [comment]
yes, it's the 2.5.2 version. Can you test with the audio file i send above, the ```return_timestamps='word'``` doesn't seem to work with Japanese

**Comment by xenova** [comment]
You should also specify the language when transcribing. As shown in the [docs](https://huggingface.co/docs/transformers.js/api/pipelines#pipelinesautomaticspeechrecognitionpipeline-codepipelinecode):

```js
let url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/french-audio.mp3';
let transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-small');
let output = await transcriber(url, { language: 'french', task: 'transcribe' });
// { text: " J'adore, j'aime, je n'aime pas, je déteste." }
```

Could you please send the output that is returned?

**Comment by xenova** [comment]
I've been playing around with this a bit more and neither my implementation, nor the [python version](https://github.com/huggingface/transformers/pull/23205) is producing good enough results. Have you tested this with the python library before?

**Comment by xenova** [comment]
Okay after a bit more digging I was able to find something. PR [here](https://github.com/xenova/transformers.js/pull/253) which should fix most of these issues. I'll still do some more testing though.

**Comment by LostArrows27** [comment]
> Okay after a bit more digging I was able to find something. PR [here](https://github.com/xenova/transformers.js/pull/253) which should fix most of these issues. I'll still do some more testing though.

yoooooo thanks for the hard works bro, the result from your testing look awesome man im ngl. I just wonder if i install your package through npm how can i test new update from the PR

**Comment by xenova** [comment]
I'll be doing a new release as soon as I've done more testing (particularly on your audio file). So, if everything goes well, I'll get a release out today!

**Comment by xenova** [comment]
@LostArrows27 The medium, unquantized model seems to perform relatively well. I don't speak Japanese, but does this seem (somewhat) accurate?

```json
{
  "text": "高校生活といえばバライロバライロといえば高校生活そう言われるのがあたり前なくらい高校生活はいつもバライロの扱いだよなさりとねすべての高校生がバライろん望んでいるわけではないと、ここらを思うんだが、例えば電楽にも、スポーツにも、色々いザタにも興味を示さない人間というのも、いるんじゃないか。",
  "chunks":[
    {"text": "高", "timestamp": [0,7.68]},
    {"text": "校", "timestamp": [7.68,7.9]},
    {"text": "生活", "timestamp": [7.9,8.24]},
    {"text": "と", "timestamp": [8.24,8.64]},
    {"text": "い", "timestamp": [8.64,8.76]},
    {"text": "えば", "timestamp": [8.76,8.96]},
    {"text": "バ", "timestamp": [8.96,9.22]},
    {"text": "ライ", "timestamp": [9.22,9.32]},
    {"text": "ロ", "timestamp": [9.32,9.52]},
    {"text": "バ", "timestamp": [10.4,10.56]},
    {"text": "ライ", "timestamp": [10.56,10.72]},
    {"text": "ロ", "timestamp": [10.72,10.86]},
    {"text": "と", "timestamp": [10.86,11.02]},
    {"text": "い", "timestamp": [11.02,11.12]},
    {"text": "えば", "timestamp": [11.12,11.28]},
    {"text": "高", "timestamp": [11.28,11.6]},
    {"text": "校", "timestamp": [11.6,11.74]},
    {"text": "生活", "timestamp": [11.74,12.1]},
    {"text": "そう", "timestamp": [13.34,13.66]},
    {"text": "言", "timestamp": [13.66,13.8]},
    {"text": "わ", "timestamp": [13.8,13.92]},
    {"text": "れる", "timestamp": [13.92,14.06]},
    {"text": "の", "timestamp": [14.06,14.2]},
    {"text": "が", "timestamp": [14.2,14.3]},
    {"text": "あ", "timestamp": [14.3,14.44]},
    {"text": "た", "timestamp": [14.44,14.52]},
    {"text": "り", "timestamp": [14.52,14.64]},
    {"text": "前", "timestamp": [14.64,14.74]},
    {"text": "な", "timestamp": [14.74,14.92]},
    {"text": "く", "timestamp": [14.92,15.08]},
    {"text": "らい", "timestamp": [15.08,15.2]},
    {"text": "高", "timestamp": [15.82,15.9]},
    {"text": "校", "timestamp": [15.9,16.06]},
    {"text": "生活", "timestamp": [16.06,16.4]},
    {"text": "はい", "timestamp": [16.4,16.66]},
    {"text": "つ", "timestamp": [16.66,16.84]},
    {"text": "も", "timestamp": [16.84,16.94]},
    {"text": "バ", "timestamp": [16.94,17.16]},
    {"text": "ライ", "timestamp": [17.16,17.26]},
    {"text": "ロ", "timestamp": [17.26,17.44]},
    {"text": "の", "timestamp": [17.44,17.54]},
    {"text": "扱", "timestamp": [17.54,17.76]},
    {"text": "い", "timestamp": [17.76,17.9]},
    {"text": "だ", "timestamp": [17.9,18]},
    {"text": "よ", "timestamp": [18,18.08]},
    {"text": "な", "timestamp": [18.08,18.22]},
    {"text": "さ", "timestamp": [19.6,20.02]},
    {"text": "り", "timestamp": [20.02,20.14]},
    {"text": "と", "timestamp": [20.14,20.26]},
    {"text": "ね", "timestamp": [20.26,20.46]},
    {"text": "す", "timestamp": [21.26,21.34]},
    {"text": "べ", "timestamp": [21.34,21.44]},
    {"text": "て", "timestamp": [21.44,21.54]},
    {"text": "の", "timestamp": [21.54,21.66]},
    {"text": "高", "timestamp": [21.66,21.82]},
    {"text": "校", "timestamp": [21.82,22]},
    {"text": "生", "timestamp": [22,22.18]},
    {"text": "が", "timestamp": [22.18,22.28]},
    {"text": "バ", "timestamp": [22.28,22.48]},
    {"text": "ライ", "timestamp": [22.48,22.58]},
    {"text": "ろ", "timestamp": [22.66,22.74]},
    {"text": "ん", "timestamp": [22.74,22.84]},
    {"text": "望", "timestamp": [22.84,23.02]},
    {"text": "んで", "timestamp": [23.02,23.22]},
    {"text": "いる", "timestamp": [23.22,23.36]},
    {"text": "わ", "timestamp": [23.36,23.5]},
    {"text": "け", "timestamp": [23.5,23.58]},
    {"text": "では", "timestamp": [23.58,23.78]},
    {"text": "ない", "timestamp": [23.78,24.04]},
    {"text": "と、", "timestamp": [24.04,24.6]},
    {"text": "ここ", "timestamp": [24.6,24.7]},
    {"text": "ら", "timestamp": [24.7,24.78]},
    {"text": "を", "timestamp": [24.78,24.88]},
    {"text": "思", "timestamp": [24.88,25.02]},
    {"text": "うん", "timestamp": [25.02,25.14]},
    {"text": "だ", "timestamp": [25.14,25.24]},
    {"text": "が、", "timestamp": [25.24,26.2]},
    {"text": "例えば", "timestamp": [26.2,26.7]},
    {"text": "電", "timestamp": [26.7,27.06]},
    {"text": "楽", "timestamp": [27.06,27.24]},
    {"text": "に", "timestamp": [27.24,27.54]},
    {"text": "も、", "timestamp": [27.54,28.16]},
    {"text": "ス", "timestamp": [28.16,28.32]},
    {"text": "ポ", "timestamp": [28.32,28.44]},
    {"text": "ーツ", "timestamp": [28.44,28.6]},
    {"text": "に", "timestamp": [28.6,28.82]},
    {"text": "も、", "timestamp": [28.82,29.44]},
    {"text": "色", "timestamp": [29.44,29.58]},
    {"text": "々", "timestamp": [29.58,29.72]},
    {"text": "い", "timestamp": [29.72,29.84]},
    {"text": "ザ", "timestamp": [29.84,29.96]},
    {"text": "タ", "timestamp": [29.96,30.02]},
    {"text": "に", "timestamp": [30.02,30.12]},
    {"text": "も", "timestamp": [30.12,30.24]},
    {"text": "興", "timestamp": [30.24,30.44]},
    {"text": "味", "timestamp": [30.44,30.58]},
    {"text": "を", "timestamp": [30.58,30.7]},
    {"text": "示", "timestamp": [30.7,30.88]},
    {"text": "さ", "timestamp": [30.88,31.1]},
    {"text": "ない", "timestamp": [31.1,31.26]},
    {"text": "人", "timestamp": [31.26,31.44]},
    {"text": "間", "timestamp": [31.44,31.56]},
    {"text": "という", "timestamp": [31.56,31.82]},
    {"text": "の", "timestamp": [31.82,31.96]},
    {"text": "も、", "timestamp": [31.96,32.38]},
    {"text": "いる", "timestamp": [32.38,32.5]},
    {"text": "ん", "timestamp": [32.5,32.64]},
    {"text": "じゃない", "timestamp": [32.64,32.86]},
    {"text": "か。", "timestamp": [32.86,33.48]}
  ]
}
```

**Comment by LostArrows27** [comment]
@xenova except the first word the model detect it with the background music (which should start around 7.4s-7.68s not from 0s), all the other timestamp seems to be pretty accurate bro, just have a little different from the main subtitle file (0.1 - 0.3s). But i guess this result is pretty good compare to some model i have tested ngl
![image](https://github.com/xenova/transformers.js/assets/97510841/fafba37e-19ea-4c78-9378-0c55a1da6e90)

**Comment by xenova** [comment]
cc @hollance may be able to comment on the "starting at 0 issue" - I remember seeing him comment on it somewhere.

**Comment by LostArrows27** [comment]
okay ill find it, but it in this reposity's issues right

**Comment by xenova** [comment]
> okay ill find it, but it in this reposity's issues right

Either here, or https://github.com/huggingface/transformers/ - I can't remember 😅

**Comment by xenova** [comment]
Turns out there was a [bug](https://github.com/huggingface/transformers/issues/25605) in the python version, and I've made a [PR](https://github.com/huggingface/transformers/pull/25607) to fix it. I'll make the fix here too.

**Comment by LostArrows27** [comment]
@LostArrows27 glad to hear that we can fix the starting timestamp error bro. And tell me when you release the new update on the package 😁

**Comment by xenova** [comment]
Will do :) ... I'll wait for some feedback on that [PR](https://github.com/huggingface/transformers/pull/25607) before I merge my fix, so I won't make the release tonight (but it will happen soon) 🤗

**Comment by LostArrows27** [comment]
@xenova oh seem like you have fixed the bug right, i wonder when will you publish the new version of the npm package

**Comment by xenova** [comment]
Yes! 🤗 Just fixing some CI/CD problems, and will release shortly!

**Comment by xenova** [comment]
Released! 🥳 https://www.npmjs.com/package/@xenova/transformers/v/2.5.3

**Comment by LostArrows27** [comment]
@xenova wow nice bro, can wait too test that soon 😁 But i wonder what config should i use like the medium model u said, ..... to give the word timestamp more accurate
