### ISSUE TITLE
[Bug] Model fails to load in Brave with Failed to execute 'open' on 'CacheStorage'

### ISSUE THREAD

**Issue by quantuminformation** [xenova/transformers.js#256]
**Describe the bug**
Try load model in brave : get error: 
Uncaught (in promise) DOMException: Failed to execute 'open' on 'CacheStorage': An attempt was made to break through the security policy of the user agent.
<img width="1700" alt="image" src="https://github.com/xenova/transformers.js/assets/216566/e8c05445-8fb6-41cc-a414-63b739355cef">

**How to reproduce**
record audio and try transcribe here https://huggingface.co/spaces/Xenova/whisper-web

**Expected behavior**
model loads

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Web site
- Brave
- Mac OS

**Additional context**
*Add any other context about the problem here.*

**Comment by xenova** [comment]
I assume this is because of certain browser settings (which are restrictive by default). However, it should continue to work after being unable to open the cache, so I'll look into that.

You should be able to get it working in the meantime by visiting the page directly: https://xenova-whisper-web.hf.space/index.html.

**Comment by quantuminformation** [comment]
perfect thanks, works fine

prob a cross domain thing

**Comment by quantuminformation** [comment]
I'm getting this when transcribing

![image](https://github.com/xenova/transformers.js/assets/216566/d8378212-5bc0-49fa-94ea-7334fa030f8a)

**Comment by quantuminformation** [comment]
seems to be a brave thing

works fine in safari

**Comment by xenova** [comment]
When you play back the audio in Brave, is it clear? Admittedly, I haven't tested in Brave, but there shouldn't be any difference.

**Comment by quantuminformation** [comment]
tried again, and it worked

![image](https://github.com/xenova/transformers.js/assets/216566/f2556e8c-9816-4ef6-99f7-575df9e59ba9)


is there any way to train this to recognise voices, so it could be used to split out separate transcriptions or just labelled as X user??

**Comment by xenova** [comment]
There's an open feature request in the python library for [diarization](https://github.com/huggingface/transformers/issues/25376), and I will add it to transformers.js when supported there first. :)

**Comment by xenova** [comment]
Okay good news, it was as simple as updating some dependencies 👍 It now will not fail, but ignore the attempt to add the model files to cache. In other words, it will work while you are on the page (and the model will be cached in memory while you are running), but once you refresh you will need to download the model again.

In less-restrictive browsers like chrome, you can refresh the page and the model will still be in cache. 🤗

**Comment by quantuminformation** [comment]
legend, any ideas what it was about Brave that needs to re-download the model each time?

I was also wondering if there is an option to get realtime transcription, or at least a nice way to batch transcription every 2 s

**Comment by xenova** [comment]
> any ideas what it was about Brave that needs to re-download the model each time?

My understanding is that Brave (due to its focus on privacy) is being extremely restrictive and only allowing caching when requested from the same domain. There may be a flag you can enable to allow this behaviour, but you should just be able to use the website if you visit it directly (hf.space link) instead of accessing it through an iframe (hf.co link).

> I was also wondering if there is an option to get realtime transcription, or at least a nice way to batch transcription every 2 s

That will be possible when we add WebGPU support... which should be coming soon! 😇🔥

**Comment by quantuminformation** [comment]
great, atm I'm just gonna try batch over 2s of audio at a time to the web worker and hope users don't complain to much ><
