### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by utiq** [xenova/transformers.js#263]
**Describe the bug**
*A clear and concise description of what the bug is.*

I tried to create a nodeJS express app, I get this error when I make a call to the server:
```
Unable to load from local path "/node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/tokenizer.json": "ReferenceError: Headers is not defined"
Unable to load from local path "/node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/tokenizer_config.json": "ReferenceError: Headers is not defined"
Unable to load from local path /node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/config.json": "ReferenceError: Headers is not defined"
```

**Comment by xenova** [comment]
Hi there. What version of node are you using? We recommend using at least 18.

**Comment by utiq** [comment]
> Hi there. What version of node are you using? We recommend using at least 18.

16.15.1

**Comment by xenova** [comment]
> 16.15.1

Yes, that is the reason then. You might be able to get around this by just importing from node-fetch and updating the global `fetch` and `Headers` objects.

For example:
```js
import fetch, {Headers} from 'node-fetch'

if (!globalThis.fetch) {
  globalThis.fetch = fetch
  globalThis.Headers = Headers
}
```
^^ from https://stackoverflow.com/a/71626669/13989043

**Comment by xenova** [comment]
Oh yes, thanks for that! I think I just copied the versions of Vite from another tutorial. I will fix that.

**Comment by Kiranism** [comment]
I'm using Next.js 13 with Node.js version 19, and I'm still encountering this error. Interestingly, when I perform a certain function, I receive a response. However, when I call another function that does the same thing, it returns an error. Everything was fine untill i changed the model. Unable to load from local path
im new to this transformer thing so please help

**Comment by xenova** [comment]
@Kiranism does [this](https://github.com/xenova/transformers.js/issues/263#issuecomment-1695867568) not work for you? However, node 19 should have `Headers` defined globally, no?
