### ISSUE TITLE
[Question] gte models don't work with pipeline

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#267]
I just noticed that the gte model family doesn't work in the transformers.js pipeline for feature-extraction with your (@xenova) onnx versions on HF.

My code throws an error.

```Javascript
import { pipeline } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.5.4';

async function allocatePipeline() {
  let pipe = await pipeline("feature-extraction", "Xenova/multilingual-e5-small");
  let out = await pipe("I love transformers", { pooling: 'mean', normalize: false });

  document.getElementById("output").innerHTML = out.data;
}

allocatePipeline();
```

Live example [here](https://geo.rocks/minimal-transformersjs-example-gte).

```
Uncaught (in promise) Error: An error occurred during model execution: "Missing the following inputs: token_type_ids.
    at transformers@2.5.4:70:5612
    at y (transformers@2.5.4:70:5971)
    at M (transformers@2.5.4:70:8450)
    at transformers@2.5.4:70:10792
    at Function.forward (transformers@2.5.4:70:10799)
    at Function._call (transformers@2.5.4:70:10675)
    at Function.e [as model] (transformers@2.5.4:88:508)
    at Function._call (transformers@2.5.4:73:1424)
    at Function._call (transformers@2.5.4:73:6152)
    at e (transformers@2.5.4:88:508)
```

However, HF user Supabase converted the models differently so that they are actually usable with the pipeline, e.g. [gte-small](https://huggingface.co/Supabase/gte-small#javascript). I noticed that Supabase added the vocab.txt file - is it possible that this or other files are missing in your versions or is there a more complex reason for this?

I'm pretty interested in the gte family as they are the most performant small models currently available (according to the MTEB leaderboard).

**Comment by xenova** [comment]
This was noticed before [here](https://github.com/xenova/transformers.js/issues/177#issuecomment-1616033265), and is due to the author of the model mixing tokenizers and models. As seen in the [config file](https://huggingface.co/intfloat/multilingual-e5-small/blob/main/config.json):
```json
{
  "architectures": [
    "BertModel"
  ],
  "tokenizer_class": "XLMRobertaTokenizer",
}
```

This workaround fixed it for me:
```js
const extractor = await pipeline(
    "feature-extraction",
    "Xenova/multilingual-e5-small",
    { revision: "main" }
);

extractor.tokenizer.prepare_model_inputs = (model_inputs) => {
    const token_type_ids = model_inputs.attention_mask.clone();
    token_type_ids.data.fill(0n);
    return {...model_inputs, token_type_ids};
};
const result = await extractor("This is a simple test.", {
    pooling: "mean",
    normalize: true,
});
console.log(result);
// Tensor {
//   data: Float32Array(384) [0.019251275807619095, 0.008903810754418373, -0.05832963064312935, ...]
//   dims: [1, 384],
//   size: 384,
//   type: "float32"
// }
```

so maybe that helps (for now at least).

**Comment by xenova** [comment]
Just letting you know what the other gte models should work fine, as they use a Bert architecture as well as a Bert tokenizer.

**Comment by do-me** [comment]
Thanks for you detailed reply! I just noticed later on that I was mixing up e5 and gte models as both `Xenova/multilingual-e5-*` and `Xenova/gte-small` weren't working out of the box.

**Comment by xenova** [comment]
> both Xenova/multilingual-e5-* and Xenova/gte-small weren't working out of the box.

Are you sure `gte-small` isn't working? It should be - and I believe I have tested it already.

**Comment by do-me** [comment]
You are right, it's indeed working. For some reason I was convinced it wasn't... sorry.
I'll change the title of this issue to apply only to `multilingual-e5-*`.
