### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by chelouche9** [xenova/transformers.js#27]
Hi @xenova,

Thanks again for all the hard work and this amazing library. 
I am trying to make it work on Next.js. Everything works fine but when I build (static site generation) and I run the website, I get weird errors. I think they might be related to webpack. 

This is the error:
**Uncaught SyntaxError: Label 'r' has already been declared**

I am using next.js 13.2.4

I have seen you made some commits to fix Jimp on Next.js do you have an example how to use it?

**Comment by chelouche9** [comment]
@xenova by the way, do you have any contributors' guidelines? I would be happy to help with this :)

**Comment by kungfooman** [comment]
Open F12/devtools and copy the rest of the error or make a screenshot, that gives it more context and makes it easier to fix.

**Comment by chelouche9** [comment]
Hope this is helpful since it is after the build.
<img width="591" alt="Screenshot 2023-03-18 at 17 54 30" src="https://user-images.githubusercontent.com/71208698/226116632-6c2acfe7-0fa2-491c-b2ce-501313424776.png">

**Comment by kungfooman** [comment]
Can't you click on it? For dev purposes, it shouldn't be minified either, it just makes debugging a hell.

**Comment by chelouche9** [comment]
It's only minified once I build and export it as a static website. Before that when I use 'npm run dev' and files are served not statically everything works fine.

**Comment by xenova** [comment]
Hi! Thanks for the issue. I actually just pushed a fix for this: https://github.com/xenova/transformers.js/commit/dfac119bc1a2667c4609cc82cc3c2d7d3eb5bbe8

I just haven't made a release yet since I was waiting for some feedback from someone.

**Comment by xenova** [comment]
> @xenova by the way, do you have any contributors' guidelines? I would be happy to help with this :)

I haven't written any yet (mainly because I didn't expect the library to blow up like this haha). For the meantime, any type of contributions (in any format) will be greatly appreciated!

**Comment by xenova** [comment]
I just published v1.2.6: https://www.npmjs.com/package/@xenova/transformers

Can you check if it works? :)

**Comment by chelouche9** [comment]
@xenova it still didn't work. But I found a solution, apparently because of the minify function of next.js and webpack. 

I added this to the `next.config.js` on next.js version 13:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  swcMinify: false,
};
```

**Comment by xenova** [comment]
> @xenova it still didn't work. But I found a solution, apparently because of the minify function of next.js and webpack.
> 
> I added this to the `next.config.js` on next.js version 13:
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   swcMinify: false,
> };
> ```

Hmmm, how strange. I don't see how minifying would break things. Could you perhaps post error message (un-obfuscated)?

**Comment by chelouche9** [comment]
I tried to use webpack source map but it didn't work for some reason.

I did some research and next.js integrated a new compiler swc which is doing the modification. What I did in the configuration is changing to another minifier called Terser - https://nextjs.org/docs/advanced-features/compiler#minification

**Comment by chelouche9** [comment]
> Some google searching says that it might be a caching issue? https://stackoverflow.com/a/67659159

Tried that already lol 🤣

**Comment by xenova** [comment]
Hmm - that's odd 👀 . So, is your problem solved (for the most part, at least)?

Once I finish what I am currently working on (*cough* whisper timestamps *cough*), I will try to look into it a bit more :)

**Comment by chelouche9** [comment]
@xenova yes, on my end it is fixed :)
