### ISSUE TITLE
[Feature request] Improve TypeScript portability

### ISSUE THREAD

**Issue by AyresMonteiro** [xenova/transformers.js#275]
# **Improve TypeScript portability**
Current typescript definitions are broken.

**Reason for request**
I'm trying to use this library in a Typescript project.

**Additional context**
Images of broken imports.

![image](https://github.com/xenova/transformers.js/assets/53703706/61d348d8-5b74-4e0b-b4b5-94e89667112a)

**Comment by AyresMonteiro** [comment]
Update: I could build it using this `tsconfig,json`:
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "sourceMap": true,
    "outDir": "./build/",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "Node16",
    "resolveJsonModule": true,
    "isolatedModules": true,
  },
  "exclude": ["node_modules", "build"]
}
```

**Comment by kungfooman** [comment]
Right now we violate the Liskov Substitution Principle:

> Simply put, the Liskov Substitution Principle (LSP) states that objects of a superclass should be replaceable with objects of its subclasses without breaking the application. In other words, what we want is to have the objects of our subclasses behaving the same way as the objects of our superclass.

Mini fake example:

```js
class Callable {
    /**
     * This method should be implemented in subclasses to provide the
     * functionality of the callable object.
     *
     * @param {any[]} args
     * @throws {Error} If the subclass does not implement the `_call` method.
     */
    _call(...args) {
        throw Error('Must implement _call method in subclass')
    }
}

class Pipeline extends Callable {
    _call(a = 1, b = 2) {}
}

class QuestionAnsweringPipeline extends Pipeline {
    // THIS IS THE ERROR - which we just // @ts-ignore right now
    _call(a = "str", b = 2) {}
}
```

[TS Playground](https://www.typescriptlang.org/play?ts=4.6.2&filetype=js#code/MYGwhgzhAEDCYnAIxAU2gbwFDV9A9AFSE57SHQAqAFgJYwC2qALtQPYAm0E7AriFyTpaDAA5omAO2aoutSd15JQkCKhjM20UQCc2AN1od0rVKTwUAZr0nBmtNpIS1mAT2htL0U9GAJkaB5IAFaodgB05rgkZOTQAAKiYDpgDJhgkq4A2gC6AL7QyQDmEFFx8ax6AO4wGACiOno6BQCSXj4QSipQ0Bxs6tCSbMzQIuKoUiM+AAYA+n6I09BMrJyRsYT4UfP+ABThB8UQAJSYZXiVbFXQDU27AOQAsrwQI2MSqNLQO4jLLOxyBSdZTgKD3Y5RPJYKFYbowAAKtFEqBA8nQqAAHjJJBwYPBEGAUOhsGQfiBdmBoABeaAARgANNAkNToAAmU4YKEwuHQACKvHU9kcAEFJBAqqgdPIiojkajJOisZ9cdBZSi0WdSQtyZSaQAiV46PWM5k09mYLlYIA)

Solution? We could water down the type of `Pipeline#_call`, but lets think more about it...
