### ISSUE TITLE
[Feature request] Feature Extraction Image Demo

### ISSUE THREAD

**Issue by MentalGear** [xenova/transformers.js#277]
Thank you for this awesome library. The Demo Page is greatly helpful in quickly assessing the different capabilities. It'd be great if the demo page could also a demo for "**Feature Extraction**", both textual and image based.

**Comment by xenova** [comment]
See [here](https://github.com/xenova/transformers.js/tree/main/examples/semantic-image-search-client) for an example showcasing text+image feature extraction (for semantic image search).

Online demo: https://huggingface.co/spaces/Xenova/semantic-image-search-client
Video:


https://github.com/xenova/transformers.js/assets/26504141/5fb8b786-45ea-416c-b643-f913b9ab0cc3

Hopefully that answers your question :)
