### ISSUE TITLE
[Bug] TypeError: response.body.getReader is not a function

### ISSUE THREAD

**Issue by coralexbadea** [xenova/transformers.js#281]
**Describe the bug**

I try to use the library inside a next.js project, but I have an error: TypeError: response.body.getReader is not a function from hub.js
From what I understood this is a problem with fetch function different from node-fetch, please help me I spent 6 hours on this problem, I really need some guidance here.

**How to reproduce**

Tried to insert the library inside this project: https://github.com/supabase-community/langchain-chatbot-demo
And added:
```
    const generateEmbeddings = await pipeline(
      'feature-extraction',
      'Xenova/all-MiniLM-L6-v2'
    );
```
 and latter
```
      const embedding = await this.generateEmbeddings(document, {
        pooling: 'mean',
        normalize: true,
      });
```

**Expected behavior**

I would like the error not to happen

**Logs/screenshots**

**Environment**
- Transformers.js version:2.5.4
- Browser (if applicable):
- Operating system (if applicable):
- Other:

**Comment by xenova** [comment]
This is most likely because you are using an old version of node.js. We recommend using node >= 18.
