### ISSUE TITLE
[Bug] Title goes here. error while loading Flan T5 onnx model

### ISSUE THREAD

**Issue by allthingssecurity** [xenova/transformers.js#282]
Error: Failed to load model with error: D:\a\_work\1\s\onnxruntime\core\graph\model.cc:146 onnxruntime::Model::Model Unsupported model IR version: 9, max supported IR version: 8

    at new OnnxruntimeSessionHandler (C:\shashank\agentwork\react-translator\node_modules\onnxruntime-node\dist\backend.js:27:92)
    at C:\shashank\agentwork\react-translator\node_modules\onnxruntime-node\dist\backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.

Here is the code
```js
import { pipeline } from '@xenova/transformers';
import { env } from '@xenova/transformers';
env.localModelPath = 'C:/shashank/agentwork/';
env.allowRemoteModels = false;
let generator = await pipeline('text2text-generation', 'flan-alpaca-xl-quantized');
let output = await generator('how can I become more healthy?', {
  max_new_tokens: 100,
});
```

And model i downloaded from here
https://huggingface.co/smjain/flan-alpaca-xl-quantized

**Comment by allthingssecurity** [comment]
Also the npm modules and their versions are here
+-- @types/react-dom@18.2.7
+-- @types/react@18.2.21
+-- @vitejs/plugin-react@4.0.4
+-- @xenova/transformers@2.5.4
+-- eslint-plugin-react-hooks@4.6.0
+-- eslint-plugin-react-refresh@0.4.3
+-- eslint-plugin-react@7.33.2
+-- eslint@8.48.0
+-- onnx-proto@8.0.1
+-- onnxruntime-web@1.15.1
+-- react-dom@18.2.0
+-- react@18.2.0
`-- vite@4.4.9

**Comment by xenova** [comment]
Hi there. You need to export the model with `onnx<1.14.0` (python) for now, as onnxruntime-web is version 1.14.1 and only supports onnx 13.x. This requirement is specified in scripts/requirements.txt.

**Comment by jhpassion0621** [comment]
@xenova I made onnx models by using onnx==1.3.2, onnxruntime==1.3.1 but I am still getting `Unsupported model IR version: 9, max supported IR version: 8` message.

**Comment by jhpassion0621** [comment]
@allthingssecurity Did you try with downgrading onnx version? What result did you get?
