### ISSUE TITLE
The generate API always returns the same number of tokens as output nomatter what is min_tokens

### ISSUE THREAD

**Issue by allthingssecurity** [xenova/transformers.js#285]
Here is the code I am trying
```js
import { pipeline } from '@xenova/transformers';
import { env } from '@xenova/transformers';


let generator = await pipeline('text2text-generation', 'Xenova/LaMini-Flan-T5-783M');
let output = await generator('write a blog on Kubernetes?', {
  max_new_tokens: 512,min_new_tokens:512,min_length:300
});

console.log(output)
```
So no matter whatever is min_new_tokens or min_length (even if I try one of them only), output just remains same length

**Comment by xenova** [comment]
Are you sure? Running on my side (just using `max_new_tokens`), I get this:
```js
let generator = await pipeline('text2text-generation', 'Xenova/LaMini-Flan-T5-783M');
let output = await generator('write a blog on Kubernetes?', {
    max_new_tokens: 100,
});
// Kubernetes is a popular cloud computing platform that allows users to store, manage, and process data on-premises and on the cloud. It is a distributed computing environment that is designed to be scalable, secure, and easy to manage. 
Kubernetes is known for its robust security features, including a distributed network architecture, distributed computing, and a distributed database management system. It also offers a wide range of services and tools for developers, including
```

without `max_new_tokens` I get:
```js
// Kubernetes is a popular cloud computing platform that allows users to store, manage
```

**Comment by xenova** [comment]
[This line](https://huggingface.co/Xenova/LaMini-Flan-T5-783M/blob/main/config.json#L26) in the config.json file seem to indicate that indeed the max window for generation is 128. Oddly enough, no runtime error is displayed. A simple fix might just be to crop the past key values to this length. @fxmarty, do you maybe have any ideas here?

**Comment by xenova** [comment]
In fact, I was able to reproduce this in the python library:

With `transformers`:
```py
from transformers import pipeline
pipe = pipeline('text2text-generation', 'MBZUAI/LaMini-Flan-T5-783M')
output = pipe('Tell me a story about cheese.', max_new_tokens=500)
len(pipe.tokenizer(output[0]['generated_text'])['input_ids'])
# returns 128
```

Or with `optimum`:
```
git clone https://huggingface.co/Xenova/LaMini-Flan-T5-783M
```

```python
import onnxruntime as ort
from optimum.onnxruntime import ORTModelForSeq2SeqLM
from transformers import AutoTokenizer, pipeline

model_id = 'LaMini-Flan-T5-783M'
session = ORTModelForSeq2SeqLM.from_pretrained(
    model_id,
    subfolder='onnx',
    use_merged=False,
    encoder_session=encoder_model,
    decoder_session=decoder_model,
    decoder_with_past_session=decoder_model,
    )
tokenizer = AutoTokenizer.from_pretrained(model_id)

encoder_model=ort.InferenceSession('LaMini-Flan-T5-783M/onnx/encoder_model_quantized.onnx')
decoder_model=ort.InferenceSession('LaMini-Flan-T5-783M/onnx/decoder_model_merged_quantized.onnx')

generator_ort = pipeline(
    task="text2text-generation",
    model=session,
    tokenizer=tokenizer,
)

output = generator_ort('Tell me a story about cheese.', max_new_tokens=500)
len(tokenizer(output[0]['generated_text'])['input_ids'])
# returns 128
```

cc @Narsil @ArthurZucker perhaps I'm missing some generation parameter? As I mentioned above, it looks like `relative_attention_max_distance` is causing this (which is set to 128 in [config.json](https://huggingface.co/Xenova/LaMini-Flan-T5-783M/blob/main/config.json#L26)).

**Comment by Narsil** [comment]
Seems it was just trained that way somehow.
Probably just fed only sentences of 128 tokens max (which would put a lot of EO S token there).

If you do use `min_length` it will not produce EOS and respect it, proving that's it's the model's doing of finishing at 128. (Also the pipeline includes the prompt so 128 is the total length).

**Comment by fxmarty** [comment]
Hi, at least on the transformers side, if you want `generate` to actually obey to `min_new_tokens` (allowing EOS tokens) you need the following:

```python
gen_config = GenerationConfig(..., eos_token_id=None)
model.generation_config.eos_token_id = None  # greedy_search falls back on this eos_token_id that we need to set to None as well for min_new_tokens to have an effect.
```

due to [this](https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/generation/utils.py#L2401) and [this](https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/generation/utils.py#L2501)

transformers.js behavior is probably different though, so the issue may be elsewhere.

**Comment by fxmarty** [comment]
Yes really: https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/generation/utils.py#L2501. If all sequences in the batch produce an EOS token, the generation stops before `min_new_tokens`.

**Comment by xenova** [comment]
> transformers.js behavior is probably different though, so the issue may be elsewhere.

@fxmarty I haven't yet added the `min_new_tokens` option to Transformers.js' generation config, and it should be quite simple to add, so that's one difference. However, my concern is more about why it's stopping at exactly 128.

@Narsil with your example, could you maybe explain to me why the generation always stops at 128 if you don't specify min length? Is the model actually predicting `eos_token`? Or is it due to `"relative_attention_max_distance": 128,` in [config.json](https://huggingface.co/Xenova/LaMini-Flan-T5-783M/blob/main/config.json#L26)? I've also [searched](https://github.com/search?q=repo%3Ahuggingface%2Ftransformers%20relative_attention_max_distance&type=code) the transformers repo for `relative_attention_max_distance`, but it doesn't appear in the generation code (it's only set for config). If it's operating as I understand it, does it not make sense to crop the attentions during generation?

**Comment by Narsil** [comment]
It looks like eos I tried to remove the relative thing from the config and nothing seems to have changed. I may have done it wrong though I just edited the file and didn't check what happened deep into the code.

**Comment by xenova** [comment]
> It looks like eos 

Your earlier experiment of setting `min_tokens` (i.e., not allowing the model to predict EOS) seems to confirm this. Still very strange, no? I would think that even if the model only attends to the previous 128 tokens, it would still be able to generate more than that. Alternatively, this may be a by-product of how the model was trained: with chunks of 128 tokens.

I initially suspected that the model would output gibberish after token 128 if we just don't allow it to predict EOS. However, the output seems perfectly sound 👍 (320 tokens)

> _Kubernetes is a popular containerization platform that allows developers to build and deploy applications on a large scale. It is a lightweight, scalable, and cost-effective way to manage and scale applications. Kubernetes is based on the Kubernetes Stack, which is a collection of containerization tools and services. It is designed to be easy to use and manage, making it a popular choice for developers and organizations. One of the main advantages of Kubernetes is its ability to handle large volumes of traffic. Kubernetes supports_ **a large number of concurrent applications, and it can handle large volumes of traffic with ease. It is also a highly customizable platform, allowing developers to tailor Kubernetes to their specific needs. Kubernetes is also highly secure, as it uses a combination of encryption, port control, and containerization techniques to ensure that applications can run smoothly on different environments. Kubernetes also provides a robust security framework, which makes it easy to manage and deploy applications. This makes it a popular choice for developers who want to build and deploy applications on a large scale. Kubernetes also provides a robust security framework, which makes it easy to manage and secure applications. It is also a popular choice for developers who want to build and deploy applications on a large scale. Overall, Kubernetes is a powerful tool for building and deploying applications on a large scale.**

(bold is >token 128)
