### ISSUE TITLE
[Question] Which models can we convert to ONNX w/ optimum?

### ISSUE THREAD

**Issue by kingsoftheweb** [xenova/transformers.js#288]
Can we convert any model on huggingface using optimum to be compatible with transformer.js?

**Comment by kingsoftheweb** [comment]
This the model we are interested in converting:

Salesforce/blip-image-captioning-large

We want to know If it is possible to convert it using optimum or no.

**Comment by xenova** [comment]
Unfortunately I don't think this architecture is supported yet by [optimum](https://github.com/huggingface/optimum). Maybe @fxmarty can comment on this.

**Comment by kingsoftheweb** [comment]
Thanks for getting back to me.

So, how can we know If a model on huggingface can be converted or no?
