### ISSUE TITLE
How would I use Facebook Blenderbot?

### ISSUE THREAD

**Issue by jessejohnson** [xenova/transformers.js#29]
Hi @xenova, I just noticed you uploaded a quantized Blenderbot to Hugging Face. Do you have instructions on how to use it? The original model doesn't have any...

Thanks!

**Comment by xenova** [comment]
Hey! I uploaded the model files, but I haven't added support the necessary classes yet to the library... which will be coming soon!

**Comment by jessejohnson** [comment]
OMG! That was a quick answer, thanks! I'm going to try t5 next :)
You're amazing

**Comment by xenova** [comment]
Haha no worries ;) I'm currently adding timestamps for whisper (speech to text), but blenderbot is on the TODO list! (I will try to remember to post here once it is ready)
