### ISSUE TITLE
[Feature request] add BAAI/bge-large-en models for embeddings

### ISSUE THREAD

**Issue by happysalada** [xenova/transformers.js#290]
**Name of the feature**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

The model is not listed in the supported models, but it's using the transformer dependency and onnx, so I thought this would be supported.
https://github.com/FlagOpen/FlagEmbedding

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

the model is at the top of the leaderboard for embeddings

**Additional context**
the dependencies are torch and transformers https://github.com/FlagOpen/FlagEmbedding/blob/master/setup.py
that is why I thought it would potentially be usable.

unfortunately trying to run the script errors with
```
❯ : python3 -m scripts.convert --quantize --model_id BAAI/bge-large-en
/Users/raphael/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/raphael/dev/transformers.js/scripts/convert.py", line 89, in <module>
    class ConversionArguments:
  File "/Users/raphael/dev/transformers.js/scripts/convert.py", line 117, in ConversionArguments
    f" {str(list(TasksManager._TASKS_TO_AUTOMODELS.keys()))}. For decoder models, use `xxx-with-past` to export the model using past key values in the decoder."
AttributeError: type object 'TasksManager' has no attribute '_TASKS_TO_AUTOMODELS'
```

if there is anything I can do to move this forward, I would be happy to.
Otherwise if it's impossible, no worries at all, I thought I might ask.

**Comment by xenova** [comment]
Hi 👋  There was a recent change to optimum which causes this issue. I will update the conversion script now. Fortunately, we already have converted this model you are looking for: https://huggingface.co/Xenova/bge-large-en

**Comment by happysalada** [comment]
You are absolutely awesome!

**Comment by xenova** [comment]
New conversion script [here](https://github.com/xenova/transformers.js/commit/d7438ce26dc64ae9228a4ca3835d31ba3ec7c439)

**Comment by happysalada** [comment]
hey, one more thing, I noticed in the table on the readme, in the nlp task table, the feature extraction task is missing.
is it a conscious choice ? ( I guess that is why I didn't find the model originally).
