### ISSUE TITLE
[Question] Issue with deploying model to Vercel using NextJS and tRPC

### ISSUE THREAD

**Issue by arnabtarwani** [xenova/transformers.js#295]
Hi I'm trying to deploy my model to Vercel via NextJS and tRPC and have the .cache folder generated using the postinstall script 

```
// @ts-check
let fs = require("fs-extra");
let path = require("path");

async function copyXenovaToLocalModules() {
  const paths = [["../../../node_modules/@xenova", "../node_modules/@xenova"]];

  for (const pathTuple of paths) {
    const [src, dest] = [
      path.join(__dirname, pathTuple[0]),
      path.join(__dirname, pathTuple[1]),
    ];
    await fs.remove(dest).catch(() => {});
    await fs.copy(src, dest).catch(() => {});

    // Create .cache folder for dest paths

    const cacheDir = path.join(dest, "transformers", ".cache");
    await fs.mkdir(cacheDir).catch(() => {});
  }
}

copyXenovaToLocalModules();

```
When I run this, I get the following error: 

```
env {
  backends: {
    onnx: { wasm: [Object], webgl: {}, logLevelInternal: 'warning' },
    tfjs: {}
  },
  __dirname: '/vercel/path0/packages/api/node_modules/@xenova/transformers',
  version: '2.5.4',
  allowRemoteModels: true,
  remoteHost: 'https://huggingface.co/',
  remotePathTemplate: '{model}/resolve/{revision}/',
  allowLocalModels: true,
  localModelPath: '/vercel/path0/packages/api/node_modules/@xenova/transformers/models/',
  useFS: true,
  useBrowserCache: false,
  useFSCache: true,
  cacheDir: '/vercel/path0/packages/api/node_modules/@xenova/transformers/.cache/',
  useCustomCache: false,
  customCache: null
}
An error occurred while writing the file to cache: [Error: ENOENT: no such file or directory, mkdir '/vercel'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/vercel'
}
An error occurred while writing the file to cache: [Error: ENOENT: no such file or directory, mkdir '/vercel'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/vercel'
}
An error occurred while writing the file to cache: [Error: ENOENT: no such file or directory, mkdir '/vercel'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/vercel'
}
``` 
Can someone help me with this?

**Comment by xenova** [comment]
This doesn't look like an issue with transformers.js, but rather with the structure of the vercel server. Do you have permissions set for the `/vercel` folder (and does it exist)?

**Comment by arnabtarwani** [comment]
Hi I have fixed the model path however, there's another error with onnxruntime-node 

```
Error: Failed to load model because protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/var/task/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at /var/task/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
Aborted(Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/@xenova/transformers@2.5.4/dist/ort-wasm-simd.wasm')
failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/@xenova/transformers@2.5.4/dist/ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.
Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'https:/cdn.jsdelivr.net/npm/@xenova/transformers@2.5.4/dist/ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.)
```

I have updated wasm paths to use the js.deliver one however, this is still causing some issue.

**Comment by xenova** [comment]
Can you verify that the wasm files are in the `/vercel/path0/packages/api/node_modules/@xenova/transformers/dist/` folder? I think the error message explains what is going wrong.

**Comment by arnabtarwani** [comment]
Upon checking the path, the `dist` and `types` folder were missing when the package was installed during deployment. 

```
file package.json
file src
console.log {
  backends: {
    onnx: { wasm: [Object], webgl: {}, logLevelInternal: 'warning' },
    tfjs: {}
  },
  __dirname: '/var/task/node_modules/@xenova/transformers',
  version: '2.5.4',
  allowRemoteModels: false,
  remoteHost: 'https://huggingface.co/',
  remotePathTemplate: '{model}/resolve/{revision}/',
  allowLocalModels: true,
  localModelPath: '/var/task/packages/api/src/models',
  useFS: true,
  useBrowserCache: false,
  useFSCache: true,
  cacheDir: '/tmp/.cache',
  useCustomCache: false,
  customCache: null
}
``` 

The is still persistent 
```
Error: Failed to load model because protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/var/task/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at /var/task/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/@xenova/transformers/dist/ort-wasm-simd.wasm')
failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/@xenova/transformers/dist/ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.
Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/@xenova/transformers/dist/ort-wasm-simd.wasm'). Build with -sASSERTIONS for more info.)
```

**Comment by xenova** [comment]
> Aborted(Error: ENOENT: no such file or directory, open '/var/task/node_modules/@xenova/transformers/dist/ort-wasm-simd.wasm')

The error says that these files were not found, so you should be able to fix it by copying the wasm files from [here](https://www.jsdelivr.com/package/npm/@xenova/transformers?tab=files&path=dist) into `/var/task/node_modules/@xenova/transformers/dist/`.
![image](https://github.com/xenova/transformers.js/assets/26504141/d1a3a8b1-a0d3-4cd4-a7c5-2c607bc39d94)

**Comment by arnabtarwani** [comment]
Hi there, 
Thanks for the solution on the `dist` folder issue. The error is fixed now however, the onnxruntine-node error is still persistent. 

```
Error: Failed to load model because protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/var/task/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at /var/task/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
``` 

I have tried using experimental features and without onnxruntime-node but the error is consistent. 
I looked into this #63 as it pretty much similar but in monorepo setup with pnpm, it occurs constantly.

**Comment by xenova** [comment]
I gather you already tried our `next-server` [tutorial](https://huggingface.co/docs/transformers.js/tutorials/next#serverside-inference) (source code [here](https://github.com/xenova/transformers.js/tree/main/examples/next-server))?

**Comment by arnabtarwani** [comment]
I'm using v1.15.1 and I have this exact setup in my next config 

![image](https://github.com/xenova/transformers.js/assets/19692895/11d7d5bc-d8d4-454c-a9b0-de861429b711)

![image](https://github.com/xenova/transformers.js/assets/19692895/b2b3260e-d2ea-4948-a2e5-6edb4980f803)

**Comment by xenova** [comment]
Right, so I believe that is the issue. The current WASM files are for v1.14.0. See the [package.json](https://github.com/xenova/transformers.js/blob/main/package.json#L45)

Could you try downgrade to 1.14?

**Comment by arnabtarwani** [comment]
Still no luck. Both the dependencies are installed in packages/api and are being hoisted to NextJs as a dependency. is it necessary that the onnxruntime-node be installed under NextJS app?

**Comment by xenova** [comment]
Hmm, let's see 🤔... which model are you trying to run? Perhaps you are trying to run a model with external data format (i.e., >2GB in size). That seems probable.

**Comment by arnabtarwani** [comment]
Currently, using this one `Xenova/paraphrase-multilingual-MiniLM-L12-v2` and the onnx that it generated was definitely huge

**Comment by xenova** [comment]
Hmm... still not over the 2GB limit, so that rules that out. Are you able to run the model locally with node.js directly?

**Comment by arnabtarwani** [comment]
It runs locally without any issues and also, without local models

**Comment by arnabtarwani** [comment]
One correction - I'm using tRPC and also, am using T3 stack https://github.com/t3-oss/create-t3-turbo for this. I'm serving my API as a package via NextJs so it's an extra step that's being added here

**Comment by xenova** [comment]
The only issue I can find in the onnxruntime repo which has a similar error message to yours is [this one](https://github.com/microsoft/onnxruntime/issues/13117). From there:

> I checked the model and it works on my PC.
> 
> The model is OK. Your code is OK, and the log tells that it successfully run into the WebAssembly so the wasm is loaded OK.
> 
> One possible reason is that the model file is not served by the server correctly. From devtool, goto Network -> conv-13.onnx -> Headers. check the following headers:
> 
> content-length: 16408506
> content-type: application/octet-stream

perhaps that can provide some guidance. I've never used the tools you're referring to, but I don't think there should be something which differentiates this from other standard Next.js usage (which we have already got working).

**Comment by arnabtarwani** [comment]
There is a size limit to function 
![image](https://github.com/xenova/transformers.js/assets/19692895/5f760d09-d92f-4db2-83a0-1b13c6ce65b1)

**Comment by xenova** [comment]
Could you try with https://huggingface.co/Xenova/all-MiniLM-L6-v2 or https://huggingface.co/Xenova/bge-small-en to see if this is indeed the issue? These are much smallest.

**Comment by arnabtarwani** [comment]
Sure, let me try this

**Comment by xenova** [comment]
Quickly adding everything up (58+31+16+16+19+2+2+1+1+1 ≈ 147 MB) and this is excluding the 118MB + 17MB tokenizer files.

In total, that already sums up to >250MB

**Comment by arnabtarwani** [comment]
Earlier, when I was using the paraphrase-multilingual-MiniLM-L12-v2 I was getting this tRPC error 
`TRPCClientError: JSON Parse error: Unexpected end of input` but now the error is [TRPCClientError: Can't create a session] which might be a login error. 

Also, the warning that you saw above has gone, but I still get the same error. I don't think there is any size issue anymore
![image](https://github.com/xenova/transformers.js/assets/19692895/4b1d2f5c-3547-438b-b197-efe13f386a65)

**Comment by arnabtarwani** [comment]
@xenova It indeed was the problem with Vercel size limit. `Xenova/paraphrase-multilingual-MiniLM-L12-v2` was huge and when I used this `Xenova/all-MiniLM-L6-v2` model, it worked seamlessly. I would say if it is possible, can you further compress this `Xenova/paraphrase-multilingual-MiniLM-L12-v2` model? I really would like to use this one and also, want to deploy it on Vercel as we're planning our infrastructure to stay there. 

Otherwise, really appreciate your help on this! Thank you very much!

**Comment by xenova** [comment]
> I would say if it is possible, can you further compress this Xenova/paraphrase-multilingual-MiniLM-L12-v2 model

I mean, you could experiment with simple file compression, but from the screenshot you sent above, it would seem as though they track uncompressed file size, no? I'm not really in a position to retrain a smaller model for it, but if you are looking for other multilingual embedding models, check out the [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard). Perhaps one of those is suitable size-wise. You can then convert it to ONNX with our [conversion script](https://huggingface.co/docs/transformers.js/custom_usage#convert-your-models-to-onnx) or [Optimum](https://huggingface.co/docs/optimum) directly.

**Comment by xenova** [comment]
The vercel [docs](https://vercel.com/docs/limits/overview#serverless-function-memory) suggest you could upgrade your plan to get up to 3008MB, so hopefully that helps. Unfortunately with most text embeddings models, the relatively large vocabulary size combined with the hidden size dimension means these models are usually quite large.

I'll close the issue for now, but feel free to continue asking questions or reopen if you'd like.
