### ISSUE TITLE
[Feature request] Using transformers.js with the hf api

### ISSUE THREAD

**Issue by happysalada** [xenova/transformers.js#311]
**Name of the feature**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

Can you use transformers.js with the hf api ?
trying something like
```
          let response = await hf.featureExtraction({
            model: 'Xenova/bge-large-en',
            inputs: chunk,
          })
```
I get the following error 
Error: HfApiJson(Deserialize(Error("unknown variant `transformers.js`, expected one of `text-generation-inference`, `transformers`, `allennlp`, `flair`, `espnet`, `asteroid`, `speechbrain`, `timm`, `sentence-transformers`, `spacy`, `sklearn`, `keras`, `generic`, `stanza`, `adapter-transformers`, `fasttext`, `fairseq`, `pyannote-audio`, `doctr`, `nemo`, `fastai`, `k2`, `diffusers`, `paddlenlp`, `mindspore`, `open_clip`, `span-marker`, `bertopic`, `peft`", line: 1, column: 405)))
    at (../../../../node_modules/.pnpm/@huggingface+inference@2.6.1/node_modules/@huggingface/inference/dist/index.mjs:154:14)

so I'm guessing it's not supported ?

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

I wanted to use a "smaller" model on the inference api to be faster and lighter.

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by xenova** [comment]
Hi there. This is because the model you are trying to run is the `transformers.js` version of it, and not the `transformers` version. You can use the original model, however. https://huggingface.co/BAAI/bge-large-zh

```js
let response = await hf.featureExtraction({
    model: 'BAAI/bge-large-en',
    inputs: chunk,
})
```

**Comment by happysalada** [comment]
Thank you !
