### ISSUE TITLE
[Feature request] Add "start and end" to QuestionAnsweringPipeline

### ISSUE THREAD

**Issue by alex-breen** [xenova/transformers.js#312]
**Name of the feature**
`QuestionAnsweringPipeline `returns "start and end" values

**Reason for request**
The start and end value (or character index) corresponding to where the answer is extracted will allow the user to view the answer source. Very useful! I think this is currently returned with python HG transformer inferences.   

**Additional context**
Currently, in `processors.js`  under the `QuestionAnsweringPipeline` class, on line 380, there is a TODO to add this, (albeit as a question, so maybe it's not straightforward to do).  I've added `start, end` to `toReturn.push` on my own private fork and it appears to work like a charm.

**Comment by xenova** [comment]
> I've added start, end to toReturn.push on my own private fork and it appears to work like a charm.

Feel free to submit a PR! 🤗 I originally laid it out as a TODO since, at the time, I didn't need it for my demos (even though they are available in the python version).

**Comment by alex-breen** [comment]
I submitted a PR. https://github.com/xenova/transformers.js/pull/333
I am closing this issue.
