### ISSUE TITLE
Calling pipeline returns `undefined`. What are possible reasons?

### ISSUE THREAD

**Issue by piscopancer** [xenova/transformers.js#327]
The repository if you need it ▶▶▶ [China Cups](https://github.com/piscopancer/china-cups)

## Next 13.5 / server-side approach

Just started digging into your library. Sorry for stupidity.

### `src/app/api/translate/route.ts` 👇
```ts
import { NextRequest, NextResponse } from 'next/server'
import { PipelineSingleton } from '@/utils/pipeline'

export async function GET(request: NextRequest) {
	const text = request.nextUrl.searchParams.get('text')
	if (!text) {
		return NextResponse.json(
			{
				error: 'Missing text',
			},
			{ status: 400 },
		)
	}
	const translator = await PipelineSingleton.getInstance()
	const translation = await translator(text)
	console.log(translation) // undefined
	return NextResponse.json(translation)
}
```

### `src/utils/pipeline.ts` 👇
This singleton must be fine, I suppose. 
```ts
import { Pipeline, pipeline } from '@xenova/transformers'
import { PretrainedOptions } from '@xenova/transformers/types/models'

function DeclarePipeline() {
	return class PipelineSingleton {
		static task = 'question-answering'
		static model = undefined as undefined | string
		static instance = null as null | Promise<Pipeline>

		static async getInstance(options?: PretrainedOptions) {
			if (!this.instance) {
				this.instance = pipeline(this.task, this.model, options)
			}
			return this.instance
		}
	}
}

export const PipelineSingleton = (() => {
	if (process.env.NODE_ENV !== 'production') {
		const gl = global as any
		if (!gl.PipelineSingleton) {
			gl.PipelineSingleton = DeclarePipeline()
		}
		return gl.PipelineSingleton
	}
	return DeclarePipeline()
})() as ReturnType<typeof DeclarePipeline>
```
### `src/app/page.tsx`This is how I query it 👇
Btw, no errors occur on this stage
```tsx
export default async function HomePage({ searchParams }: THomePage) {
	const text = 'Hello'
	const translation = await axios.get(`/translate?text=${text}`).then((res) => res.data())
	// const translation = await fetch(`/translate?text=${encodeURIComponent(text)}`).then((res) => res.json())
	return <pre>{JSON.stringify(translation)}</pre>
```

## One more very important thing
When I **manually** go to `http://localhost:3000/api/translate?text=Hello` I very happily get this error:
```
 ⨯ TypeError: Value is not JSON serializable
    at serializeJavascriptValueToJSONString (node:internal/deps/undici/undici:1203:15)
    at Response.json (node:internal/deps/undici/undici:6746:55)
    at NextResponse.json (webpack-internal:///(rsc)/./node_modules/next/dist/server/web/spec-extension/response.js:66:35)
    at GET (webpack-internal:///(rsc)/./src/app/api/translate/route.ts:24:95)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\web-dev\next\china-cups\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:1:66877
 ```
 👆 the browser cannot load this url if text=... is present 😟.

 💖

**Comment by piscopancer** [comment]
Hm, as I understand now, the only problem is that pipeline returns undefined

```
export async function GET(request: NextRequest) {
	const text = request.nextUrl.searchParams.get('text')
	if (!text) {
		return NextResponse.json(
			{
				error: 'Missing text',
			},
			{ status: 400 },
		)
	}
	// const translator = await PipelineSingleton.getInstance()
	const translator = await pipeline('question-answering')
	const translation = await translator('Can I use your phone to call my mum?')
	console.log(translation) // undefined, IDK why
	return NextResponse.json('if you put any text here, it is working fine. The problem is the response being undefined 😟.')
}
```

The page loads nicely

![image](https://github.com/xenova/transformers.js/assets/109352196/a62a0f47-994e-4449-82f2-2eb74577f26a)

**Comment by xenova** [comment]
Hi there 👋 I believe the reason for this is that the `question-answering` pipeline requires two inputs: `question` and `context` (see [docs](https://huggingface.co/tasks/question-answering)). Example [code](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.QuestionAnsweringPipeline):
```js
let question = 'Who was Jim Henson?';
let context = 'Jim Henson was a nice puppet.';

let answerer = await pipeline('question-answering', 'Xenova/distilbert-base-uncased-distilled-squad');
let output = await answerer(question, context);
// {
//   "answer": "a nice puppet",
//   "score": 0.5768911502526741
// }
```

Also note that the `question-answering` pipeline is for EXTRACTIVE question answering, meaning it can only find the answer if the answer is in the context (i.e., it will return a span in the context which it thinks is the answer to the question).


Could you maybe explain your project a bit more? What are you trying to create? 🤗

**Comment by piscopancer** [comment]
@xenova Oh yes, I tried adding context and it worked. Boom. I want (really) to create a service that consumes a phrase in russian and than spits out 5 possible translations in chinese. I am going to use it myself, even more it's going to be popular bcs copy-pasting each hieroglyph from a sentence and looking up their meaning in the online dictionary one tab for one word is a fucking brain diarrhea. 

![image](https://github.com/xenova/transformers.js/assets/109352196/269e3031-0d53-4ae5-aa94-bf084791e9da)
The hollow is a translation and the filled is a word by word explanation.

As I understood `question-answering` task does not suit my desires, yes? What Task would you recommend? It is not specifically `translating` you see, I want to tell the model to respond with a pattern-bound string like so...
```
`
1-tr_BlaBlaBla
1-ex_BlaBlaBla
2-tr_BlaBlaBla
2-ex_BlaBlaBla
3-tr_BlaBlaBla
3-ex_BlaBlaBla
4-tr_BlaBlaBla
4-ex_BlaBlaBla
5-tr_BlaBlaBla
5-ex_BlaBlaBla
`
```
... which I will then break up into markdown using regex for sure.

What do you think about that, chef?

**Comment by xenova** [comment]
I don't quite understand what you mean by "pattern-bound string" (since this will depend greatly on the target language vocabulary), but you can achieve "5 different translations" by just specifying the following generation parameters:

```js
import { pipeline } from '@xenova/transformers';
let translator = await pipeline('translation', 'Xenova/nllb-200-distilled-600M');
let output = await translator('Я тебя люблю.', {
  src_lang: 'rus_Cyrl', // Russian
  tgt_lang: 'zho_Hans', // Chinese (Simplified)
                        // NOTE: Use `zho_Hant` for Chinese (Traditional)
  num_beams: 5,
  num_return_sequences: 5,
});
// [
//   { translation_text: '我爱你.' },
//   { translation_text: '我爱你' },
//   { translation_text: '我爱你的.' },
//   { translation_text: '我爱你!' },
//   { translation_text: '我爱你,你爱我.' }
// ]
```

For multilingual translation, you can find some examples [here](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.TranslationPipeline).

There are ways to restrict the "allowable tokens to be sampled", with something called a `LogitsProcessor`, but this is relatively advanced usage and shouldn't be necessary is most cases.

**Comment by piscopancer** [comment]
Thank you again. This issue is slowly becoming off-topic after we figured out that it was **the context missing** in `question-answering` which caused `undefined`. I still have plenty of questions, I am asking all of them, just not here, until next time. (It's the first type I started an AI consuming project).

💖
