### ISSUE TITLE
Unexpected character '�'

### ISSUE THREAD

**Issue by blechatellier** [xenova/transformers.js#338]
Hi,

I'm using `"@xenova/transformers": "2.6.2"` with nextjs app router. I set up `serverComponentsExternalPackages: ['sharp', 'onnxruntime-node']` in my config. It works with npm but not with pnpm.

Is there any workaround or is this a nextjs issue?

Thanks for your help,

**Comment by blechatellier** [comment]
Related to https://github.com/xenova/transformers.js/issues/183

**Comment by xenova** [comment]
Hi there 👋 As I mentioned [here](https://github.com/xenova/transformers.js/issues/210#issuecomment-1742704869), this does look like a pnpm/next.js issue (related to the experimental `serverComponentsExternalPackages` flag (see [docs](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages)). So, we won't be able to solve it here. Perhaps others have found a workaround which might help?

There is also an open issue for this [here](https://github.com/vercel/next.js/issues/43433).

**Comment by blechatellier** [comment]
Great thanks, let's close the issue here and hopefully this will be addressed soon.

**Comment by blechatellier** [comment]
For anyone facing the same issue, I've created an api endpoint in the pages folder for now and this works.
