### ISSUE TITLE
Simple demo on jsfiddle fails

### ISSUE THREAD

**Issue by sandorkonya** [xenova/transformers.js#34]
Dear @xenova ,

thank you for this repo! It is pretty sad that Microsoft did no similar for their onnx web on their own and i am grateful that you've done it.

I tried to make the simplest demo at all in JSfiddle (and codepen). 
After adding the jsdelivr source,  just added the following js:

```
import { pipeline } from "/@xenova/transformers";

// Allocate a pipeline for sentiment-analysis
let pipe = await pipeline('embeddings', 'sentence-transformers/all-MiniLM-L6-v2');

let out = await pipe('I love transformers!');
console.log(out);
```
but get no output in the console.

**Expected:** is the embedding of the text.

Adding the trailing "/" was needed, due to error:
`"Uncaught TypeError: Failed to resolve module specifier \&quot;@xenova/transformers\&quot;. Relative references must start with either \&quot;/\&quot;, \&quot;./\&quot;, or \&quot;../\&quot;."`
Could that be the source of the problem?

JSFiddle is[ here](https://jsfiddle.net/rgLavk2x/).

thank you for your help!

**Comment by xenova** [comment]
Hi! To the best of my knowledge, you can't use the `import { pipeline } from "@xenova/transformers";` syntax directly in the "JavaScript" section.

Here's a working demo where I just moved the import to the HTML (using a simple <script> tag): https://jsfiddle.net/boLm2xsy/1/

**Comment by sandorkonya** [comment]
@xenova oh, okay, i thought that the issue simple, but that so simple 😅 

Ty!!
