### ISSUE TITLE
[Feature request] Depth Estimation pipeline

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#350]
[This demo](https://huggingface.co/spaces/ilumine-AI/Insta-3D) has got me interested in playing around with depth stuff on the web, so it'd be cool if it were available as a pipeline in Transformers.js!

 * https://huggingface.co/tasks/depth-estimation
 * https://huggingface.co/models?pipeline_tag=depth-estimation

**Comment by xenova** [comment]
cc @fxmarty - perhaps something to consider adding to Optimum? 😇
