### ISSUE TITLE
[Feature request] Nougat 

### ISSUE THREAD

**Issue by DomEscobar** [xenova/transformers.js#353]
Nougat 
https://huggingface.co/docs/transformers/v4.34.0/en/model_doc/nougat

I love nougat chocolate

**Comment by xenova** [comment]
> I love nougat chocolate

A compelling reason to add it to Transformers.js! 😎

@fxmarty how difficult would it be to add a nougat export to optimum? Looking at the [config.json](https://huggingface.co/facebook/nougat-small) it's near-identical to donut models, which I recently added support for here.


From the docs:

> The model consists of a Swin Transformer as vision encoder, and an mBART model as text decoder.

**Comment by DomEscobar** [comment]
Ty! Donor unc
