### ISSUE TITLE
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'

### ISSUE THREAD

**Issue by Sunnivasteiro** [xenova/transformers.js#357]
**Describe the bug**
When I try to convert my transformers model to .onnx, I get an error because the `quantize_dynamic()` function is called with the `optimize_model = False` argument, even if it does not take that argument. This happens in `convert.py` on line 228 inside the `quantize()` function. When I set `--quantize False`, the error is not thrown, but it seems that the default is actually `--quantize True`.

When I comment out the line mentioned, with the argument `optimize_model = False`, there is no error. 

**How to reproduce**
`python -m scripts.convert --model_id /path/to/huggingface/model --task 'image-classification'`

**Environment**
- Transformers.js version: 2.6.2
- Operating system (if applicable): linux

**Comment by xenova** [comment]
Hi there, can you please check the version of onnx, onnxruntime, and optimum? I've listed the versions I've tested with in scripts/requirements.txt

**Comment by Sunnivasteiro** [comment]
Okay, everything works as expected when using the specified packages! Thank you!
