### ISSUE TITLE
[Feature request] Add support for indic-whisper models

### ISSUE THREAD

**Issue by bil-ash** [xenova/transformers.js#358]
Please convert and quantize the 12 indic-whisper (medium) models available at https://github.com/AI4Bharat/vistaar#download-models 
 for use in transformers.js. I was able to convert, quantize and make inference using these models using the https://github.com/OpenNMT/CTranslate2 library and got proper results. But in case of transformers.js, the conversion script did not work out of the box. After a lot of hit-and-trial changes in the script, I was able to generate the quantized onnx model, but I guess I made some changes without understanding and as a result while inferencing, these models do not load even. So, requesting you to convert and quantize these models because for Indian languages these have much lower Word Error Rate than similar other models.

**Comment by xenova** [comment]
> But in case of transformers.js, the conversion script did not work out of the box.

Could you share what problems you ran into?

**Comment by bil-ash** [comment]
No, the models are not on HF hub. 
I am now performing inference on those models using the ctranslate library and I do not remember now the exact error message.
Since this is no longer an issue for me, I am closing the issue.

**Comment by bil-ash** [comment]
Opening the issue again because I guess I will need to use transformer.js I have uploaded one of the models at https://huggingface.co/bh4/whisper-ben but while running inference I get the error -

`node index.mjs
`file:///root/trjs/test/node_modules/@xenova/transformers/src/models.js:3630
`           throw Error(`Unsupported model type: ${config.model_type}`)
`                ^
`
`Error: Unsupported model type: whisper
`    at AutoModelForCTC.from_pretrained (file:///root/trjs/test/node_modules/@xenova/transformers/src/models.js:3630:19)
`    at async file:///root/trjs/test/node_modules/@xenova/transformers/src/pipelines.js:2176:33
`
`Node.js v18.13.0

**Comment by xenova** [comment]
Hi there - can you please share some more information about your environment? (OS, build tools, transformers.js version, etc.)?

**Comment by xenova** [comment]
Using our [conversion script](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py), with [these versions](https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt), I was able to export the [model you linked](https://huggingface.co/bh4/whisper-ben) without any major errors.

I have uploaded the checkpoints [here](https://huggingface.co/Xenova/whisper-ben).

You can run the model with the following code:
```js
import { pipeline } from '@xenova/transformers';

let url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/bengali-audio.wav';
let transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-ben');
let output = await transcriber(url);
// { text: 'বাংলা নিউজের আয়োজন এই মূহূর্তবিশ্বের কোটি কোটি পাঠক দেখছে' }
```

Note that this uses the quantized version of the model by default. If you want to get the exact same output as the python version, you can use the unquantized version by specifying `{ quantized: false }` in the pipeline function:
```js
import { pipeline } from '@xenova/transformers';

let url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/bengali-audio.wav';
let transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-ben', { quantized: false });
let output = await transcriber(url);
// { text: 'বাংলানিউজের আয়োজন এই মুহূর্তে বিশ্বের কোটি কোটি পাঠক দেখছে' }
```

---

Closing the issue, but feel free to ask any questions you may have.
