### ISSUE TITLE
Embeddings differ between transformers.js and sentence-transformers (Python)

### ISSUE THREAD

**Issue by ekolve** [xenova/transformers.js#36]
Running the following:

```javascript
global.self = global;

const { pipeline, env } = require("@xenova/transformers");
env.onnx.wasm.numThreads = 1;
(async()=> {
        let embedder = await pipeline('embeddings', 'sentence-transformers/all-MiniLM-L6-v2')
        let sentences = [
            'The quick brown fox jumps over the lazy dog.'
        ]
        let output = await embedder(sentences)
        console.log(output[0][0]);
})();
```

and this (installable via `pip install sentence-transformers`):
```python
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer("all-MiniLM-L6-v2")
query = model.encode("The quick brown fox jumps over the lazy dog.", convert_to_tensor=True)
print(query[0])

```

results in different values (`-0.07890480756759644` and `0.0439`).  Any idea why the embedding values are different?  I also noticed that the cosine similarity values for the same two sentences between Python and transformers.js was also quite a bit different (which is likely caused by the difference in embedding values).

**Comment by xenova** [comment]
The most likely reason is due to quantisation of the models. The model weights are reduced in precision from 32-bit to 8-bit to reduce model size by a factor of ~4 (very important for usage on a website). 

However, if you are okay with loading the full model, you can export the model yourself without quantising it, and this should produce the exact same outputs.

Here's an example command:
```
python ./scripts/convert.py --model_id sentence-transformers/all-MiniLM-L6-v2  --from_hub --quantize --task default
```

and then just point to the location of your model (see readme)

**Comment by xenova** [comment]
That said, while trying to do this on my end, I did run into an issue where the pooled value wasn't being returned (most likely due to the newest version of optimum, which removed some of those nodes). So, I will implement the mean pooling myself (see [here](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2#usage-sentence-transformers))

That should fix everything :) (since you will be able to use the original model, which is only 80MB, so, nothing too problematic)

**Comment by ekolve** [comment]
Thanks for the quick reply!

I ran convert.py and generated an unquantized model and modified my code to look like this:

```javascript

global.self = global;

const { pipeline, env } = require("@xenova/transformers");
env.onnx.wasm.numThreads = 1;
env.remoteModels = false;
env.localURL = "transformers.js/models/onnx/unquantized";

(async()=> {
        let embedder = await pipeline('embeddings', 'sentence-transformers/all-MiniLM-L6-v2')
        let sentences = [
            'The quick brown fox jumps over the lazy dog.'
        ]
        let output = await embedder(sentences)
        console.log(output[0].length);
})();
```

and I now get this error:
```javascript
TypeError: Cannot read properties of undefined (reading 'data')
    at Function._call (node-transformers/node_modules/@xenova/transformers/src/pipelines.js:286:51)
```

which corresponds to this line in pipeline.js:
```javascript
        let embeddings = reshape(embeddingsTensor.data, embeddingsTensor.dims);
```

I confirmed that the path for the model was correct by altering the `localUrl` to an invalid path and transformers.js responded with `File not found`. So it appears that transformers.js is finding the exported model.

**Comment by xenova** [comment]
Yep -that's the exact error message I got now (which is because of the version of optimum used to export). Busy fixing now! :)

**Comment by ekolve** [comment]
Just tested this out and everything looks great! Thank you!  I generated embeddings for two sentences in both JS and Python and calculated the cos similarity (in their respective libraries) and they were identical.

**Comment by xenova** [comment]
Awesome! I'll push a new release.

**Comment by mahi83** [comment]
> That said, while trying to do this on my end, I did run into an issue where the pooled value wasn't being returned (most likely due to the newest version of optimum, which removed some of those nodes). So, I will implement the mean pooling myself (see [here](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2#usage-sentence-transformers))
> 
> That should fix everything :) (since you will be able to use the original model, which is only 80MB, so, nothing too problematic)

Do you have the implementation of this mean pooling in js?

**Comment by xenova** [comment]
Sure, here's the code for it: https://github.com/xenova/transformers.js/blob/035f69f79a01be181fdfc30d774efa39110afc67/src/utils/tensor.js#L583-L620

Nothing too fancy... and it assumes certain dimensions for the input.

**Comment by mahi83** [comment]
You saved me hours! :P
