### ISSUE TITLE
[Bug] PreTrainedTokenizer.decode does not accept a Tensor

### ISSUE THREAD

**Issue by mattkrick** [xenova/transformers.js#362]
**Describe the bug**

Great package! I'm new here  so this may just be a sharp edge in how I'm using it.
I'd like to split text by token as well as perform a pipeline in the most efficient way I can.
One of the last steps of the tokenizer callable is to turn the `token_ids` into a `BigInt64Array`.
This causes decode to fail because `Array.isArray(new BigInt64Array()) === false`.
As a workaround, since I also need the `attention_mask`, I need to call `encode` again, or convert the BigInt64Array back into an Array. Neither solution is bad, but it could save a few headaches for devs if there was a clearer way to handle this.

Typescript could also save devs from this gotcha, but that looks like a pretty spicy topic in this repo (https://github.com/xenova/transformers.js/issues/264) so I'll stay out of that. 😅 

**How to reproduce**

```ts
// error case
const modelInputs = embedder.tokenizer('hi')
const decoded = embedder.tokenizer.decode(modelInputs.input_ids.data) // Error: token_ids must be a non-empty array of integers.

// working case
const token_ids = embedder.tokenizer.encode('hi')
const decoded = embedder.tokenizer.decode(token_ids)
```

**Expected behavior**

The output of the callable can be provided to `decode`.
**Environment**
- Transformers.js version: 2.6.2

**Comment by xenova** [comment]
Hi there! 👋  thanks for the issue :)

This is actually something which is also present in the python library: the `.decode` function does not accept tensors:

```py
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
input_ids = tokenizer('hello', return_tensors='pt')['input_ids']
decoded = tokenizer.decode(input_ids)
decoded
```

results in 
```
TypeError: argument 'ids': 'list' object cannot be interpreted as an integer
```


The difference, however, is that Transformers.js returns tensors by default, while the python version returns lists by default. So, I do think adding support for decoding Tensors directly will be useful... 😅  Maybe someone in the community would like to make a PR for it? 😊 


Just for completeness, you can also disable returning as a tensor as follows:
```js
import { AutoTokenizer } from '@xenova/transformers';

let tokenizer = await AutoTokenizer.from_pretrained('Xenova/bert-base-uncased');
let { input_ids } = tokenizer('I love transformers!', { return_tensor: false });
console.log('input_ids', input_ids)

let decoded = tokenizer.decode(input_ids);
console.log('decoded', decoded)
```

and in this case, it does output correctly.
