### ISSUE TITLE
[Question] How to include ort-wasm-simd.wasm with the bundle?

### ISSUE THREAD

**Issue by mjp0** [xenova/transformers.js#367]
How can I include ort-wasm-simd.wasm with the bundle? I'm using this on an app that needs to be able to run offline, so I'd like to package this with the lib. I'm also running this on web worker, so that file gets requested 1+n times per user session when the worker starts.
<img width="725" alt="image" src="https://github.com/xenova/transformers.js/assets/1594723/39f7fc6e-0914-4b40-a3bc-aa17ed53851c">

**Comment by xenova** [comment]
Hi there 👋 This would depend on your project (and its build tools), but what I do for webpack is use the `copy-webpack-plugin`:

https://github.com/xenova/transformers.js/blob/e457c4b5d097730a1226da6d62a3f2d7c0a4f192/webpack.config.js#L24-L34

Either way, you should find a similar plugin available for whatever build tool you are using.

**Comment by mjp0** [comment]
I found a similar package for Vite and copied everything to dist but looks like onnx is still choosing to fetch it from jsdelivr when using transformers.js. I also tried to import onnxruntime-web directly with this conf https://github.com/microsoft/onnxruntime/issues/16729 but it did nothing. That could mean that it's up to how transformers loads onnx.

Could you please verify that your browser does indeed load the wasm files from the bundle when you use the transformers package on a website, just to make sure the issue is at my end? 🙏

**Comment by xenova** [comment]
You can set the following environment variables to use the local WASM files:

```js
// Set location of .wasm files. Defaults to use a CDN.
env.backends.onnx.wasm.wasmPaths = '/path/to/files/';
```

For more information, check out the [docs](https://huggingface.co/docs/transformers.js/custom_usage)

**Comment by mjp0** [comment]
Missed that part of the docs, but finally got it working after I found the right syntax for vite. Thanks!
