### ISSUE TITLE
[Bug] Library not working with NextJS 13

### ISSUE THREAD

**Issue by You-now-Who** [xenova/transformers.js#369]
**Describe the bug**
*A clear and concise description of what the bug is.*

Simply importing the pipeline in Next JS leads to an error. Doesn't work on either server or client components. Might be something I am doing wrong, no idea. 

Here is the error: 

```
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
./node_modules/onnxruntime-node/bin/napi-v3/ sync ^\.\/.*\/.*\/onnxruntime_binding\.node$
./node_modules/onnxruntime-node/dist/binding.js
./node_modules/onnxruntime-node/dist/backend.js
./node_modules/onnxruntime-node/dist/index.js
./node_modules/@xenova/transformers/src/backends/onnx.js
./node_modules/@xenova/transformers/src/env.js
./node_modules/@xenova/transformers/src/transformers.js
./app/page.js
```

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

Create a Next JS application and try to import the module

**Expected behavior**
*A clear and concise description of what you expected to happen.*

Expected to import and run pipeline.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: 2.7.0
- Browser (if applicable): Edge
- Operating system (if applicable): Windows
- Other:

**Additional context**
*Add any other context about the problem here.*

Using a few other modules such as tensorflow JS.

**Comment by xenova** [comment]
Hi there. Please follow this tutorial to correctly configure your next.js 13 application: https://huggingface.co/docs/transformers.js/tutorials/next

In the tutorial, we cover both client-side and server-side inference. We also showcase demo applications for each.

**Comment by You-now-Who** [comment]
Oh, thats on me! Sorry for not checking and thanks a lot for the quick reply. Really love what you are doing with this project <3

**Comment by deboboy** [comment]
FYI: tried both next.config.js approaches described in this thread, yet I'm still getting the error:

./node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

Suspect it is related to arm64 [I'm running a 2020 Mac M1].  Any recent solutions to this problem appreciated.  

Meanwhile, going to move on to other approaches to get my Next.js web app integrated with LLM dependencies.

**Comment by l4b4r4b4b4** [comment]
Yep. Keep coming back to the same error as well. Feels like webpack expects some custom loader in order to use onnx runtime properly? :thinking:
