### ISSUE TITLE
[Model request] Facebook/BlenderBot for text-generation

### ISSUE THREAD

**Issue by fakerybakery** [xenova/transformers.js#37]
Hello,
This project is really cool. I was wondering if it's possible to use the BlenderBot model. 
My current code gives me an error:
```javascript
let pipe = await pipeline('text-generation', model = 'facebook/blenderbot_small-90M')
let out = await pipe("Prompt");
console.log(out);
```
```
GET https://huggingface.co/Xenova/transformers.js/resolve/main/quantized/facebook/blenderbot_small-90M/causal-lm-with-past/tokenizer.json 404
Uncaught (in promise) Error: File not found. Could not locate "https://huggingface.co/Xenova/transformers.js/resolve/main/quantized/facebook/blenderbot_small-90M/causal-lm-with-past/tokenizer.json".
```
I saw that this was added in your [Hugging Face repository](https://huggingface.co/Xenova/transformers.js/tree/main/quantized/facebook/blenderbot_small-90M), but I was wondering what the correct way to implement this is.
Thank you!

**Comment by fakerybakery** [comment]
Thank you so much!!!

**Comment by zap8600** [comment]
> Hi! As stated in a similar issue from 2 days ago (#29) I haven't yet implemented BlenderBot (no listed support in the README or on the demo website). I just uploaded the files since I plan to add it (which, I probably shouldn't have done haha). However, I do plan to add support for it in the next few days!
> 
> It will need a way to keep track of conversations, but I will look to HF's implementation for inspiration :)
> 
> (The error message you got is because I haven't uploaded the tokenizer yet ;) )

I believe that the Blenderbot model keeps track of a conversation using certain tokens to tell when a speaker stops and starts talking, like this:
`<s>Hello! How are you?</s> <s>I'm good. How are you?</s> <s>I'm doing pretty good.</s>`
From what I can tell, this is implemented by the user. My really bad code (in Python) for this is [here](https://github.com/zap8600/aimodels/blob/main/blenderbot/model.py). Even though this code is for Blenderbot, I believe the same goes for Blenderbot Small. However, there are _**way**_ better examples than my code. This is just what I've seen in multiple Spaces on Huggingface. I hope this helps!

**Comment by xenova** [comment]
Thanks @zap8600! I've seen similar examples for blenderbot, but the documentation for blenderbot small does not seem to be as clear. I raised an issue (https://github.com/huggingface/transformers/issues/22301), but it looks like it's been hidden already by other issues.

If possible, do you think you could look into how blenderbot small handles it? (Which is apparently different to normal blenderbot)

**Comment by zap8600** [comment]
> Thanks @zap8600! I've seen similar examples for blenderbot, but the documentation for blenderbot small does not seem to be as clear. I raised an issue (https://github.com/huggingface/transformers/issues/22301), but it looks like it's been hidden already by other issues.
> 
> If possible, do you think you could look into how blenderbot small handles it? (Which is apparently different to normal blenderbot)

I've look at the [Transformers doc](https://huggingface.co/docs/transformers/model_doc/blenderbot-small#transformers.BlenderbotSmallForConditionalGeneration.forward.example) (which is where I based my code on) and it appears to be the same way.

**Comment by xenova** [comment]
Right, but if you look at the vocabulary of the model, `<s>` is not one of the tokens.

**Comment by zap8600** [comment]
> Right, but if you look at the [vocabulary](https://huggingface.co/facebook/blenderbot_small-90M/raw/main/vocab.json) of the model, `<s>` is not one of the tokens.

My bad. I've taken a look at the vocabulary file, and the tokens appear to be `__start__` and `__end__`. I haven't tested this yet, but that is what I can tell.

**Comment by xenova** [comment]
Well, I'll test it once I implement it 😄 

One thing I find strange is that there isn't a way to say who is speaking? Is it just assumed by the alternating order of conversations?

**Comment by zap8600** [comment]
> Well, I'll test it once I implement it 😄 
> 
> One thing I find strange is that there isn't a way to say who is speaking? Is it just assumed by the alternating order of conversations?

No need to test it. It does seem to work. My code will be uploaded to my repo shortly.

**Comment by zap8600** [comment]
Yay!

**Comment by zap8600** [comment]
Thank you! I hope my testing code helped some!

**Comment by xenova** [comment]
It did! Thanks 🤗

**Comment by zap8600** [comment]
Np! I can't wait to use the BlenderBot model!
