### ISSUE TITLE
[Bug] RangeError: offset is out of bounds for text2text generation

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#370]
I am using [Xenova/LaMini-Flan-T5-783M](https://huggingface.co/Xenova/LaMini-Flan-T5-783M) for a simple RAG pipeline in [SemanticFinder](https://do-me.github.io/SemanticFinder/) and it works like a charm on the **first call**. Whenever I want to run a second query, i.e. running the same model again I get the following error "out of bounds/range".

For reproduction, simply click `Find` in SemanticFinder, then `Chat`, wait for the output to appear and then a second time `Chat`.

Chrome: 

![image](https://github.com/xenova/transformers.js/assets/47481567/1da168ec-0377-411e-936b-f6303f12e7d1)

Firefox:

![image](https://github.com/xenova/transformers.js/assets/47481567/d473e7fa-5042-43ff-b35f-6456fc3bb39d)

I'm using transformers.js 2.6.2.

The `worker.js` [here](https://github.com/do-me/SemanticFinder/blob/234b69fd4bb7101406b577f1e5c8efbe2e0a22bb/src/js/worker.js#L111-L141) is pretty standard:

```javascript

let tokenizer;

let chatModel = 'Xenova/LaMini-Flan-T5-783M';

async function token_to_text(beams){
    let chatTokenizer = await AutoTokenizer.from_pretrained(chatModel);
    let decoded_text =  chatTokenizer.decode(beams[0].output_token_ids, {
        skip_special_tokens: true
    });
    console.log(decoded_text);
    return decoded_text
}

// other code 

   case 'chat':
            text = message.text.trim()
            let max_new_tokens = message.max_new_tokens
            console.log(max_new_tokens, chatModel, text)

            let chatGenerator = await pipeline('text2text-generation', chatModel,
                {
                    progress_callback: data => {
                        self.postMessage({
                            type: 'chat_download',
                            data
                        });
                    }
                });

            let thisChat = await chatGenerator(text, {
                max_new_tokens: max_new_tokens,
                return_prompt: false,
                callback_function: async function (beams) {
                    //console.log(beams);
                    const decodedText = token_to_text(beams)
                    console.log(decodedText);
                }
            });

            self.postMessage({
                type: 'chat',
                chat: thisChat
            });

            break;

```

I was hesitant to create an issue here because I thought it was related to my code but it's weird that it's actually creating the first token of the answer and then fails. Also, I tested with e.g. `Xenova/t5-small` for text2text and didn't encounter the problem. 

Is it possible that there is some kind of memory issue here?

**Comment by felladrin** [comment]
Hi! It seems to be the same case from https://github.com/xenova/transformers.js/issues/8#issuecomment-1458867413; the solution, as Xenova mentions, is to call `await pipeline()` only once during the execution of the app.

And you probably didn't encounter the problem with `Xenova/t5-small` because it's small, and you haven't instantiated it enough times to fill up the memory.

**Comment by do-me** [comment]
Argh, that totally makes sense, thank you! I should have better searched through the closed issues too 🤦 
So I had the same issue all along in the summary function too, only that the model is small enough to be instantiated several times...
Thanks for the nice words! :)
