### ISSUE TITLE
[Feature request] Add Jina AI 8k models (onnx)

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#371]
I just took a stab at it with the default onnx quantization conversion instructions/scripts from this repo but apparently there is something wrong. See the [ongoing discussion here](https://huggingface.co/jinaai/jina-embeddings-v2-base-en/discussions/10).

Basically, the quantized versions (of base and small) produce very poor results (especially on short sequences) so I suppose some settings should be tweaked.

**Comment by Jackmin801** [comment]
Did you have to make any modifications to allow `trust_remote_code`? If `trust_remote_code` is not enabled, the weights are initialised randomly and you will see a bunch of warnings like [this](https://x.com/simonw/status/1716644983917392330?s=20).

**Comment by do-me** [comment]
These warnings look indeed familiar. So how could one pass this argument in \[the conversion script\](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py)? Or this parameter just be used when loading in transformers.js? If so, I didn't find it in the docs.

For reference \[link to optimum docs\](https://huggingface.co/docs/transformers/en/model_doc/auto#transformers.AutoModel.from_pretrained.trust_remote_code)

**Comment by xenova** [comment]
Good news, the [base](https://huggingface.co/Xenova/jina-embeddings-v2-base-en) and [small](https://huggingface.co/Xenova/jina-embeddings-v2-small-en) models are now both supported! 🤗 

Example usage:
```js
import { pipeline, cos_sim } from '@xenova/transformers';

// Create feature extraction pipeline
const extractor = await pipeline('feature-extraction', 'Xenova/jina-embeddings-v2-base-en',
    { quantized: false } // Comment out this line to use the quantized version
);

// Generate embeddings
const output = await extractor(
    ['How is the weather today?', 'What is the current weather like today?'],
    { pooling: 'mean' }
);

// Compute cosine similarity
console.log(cos_sim(output[0].data, output[1].data));  // 0.9341313949712492 (unquantized) vs. 0.9022937687830741 (quantized)
```

**Comment by xenova** [comment]
Just for completeness (and to respond to your other comments), I just used their [ONNX version](https://huggingface.co/jinaai/jina-embeddings-v2-base-en/blob/main/model.onnx), and modified the quantization script to use that model instead of generating its own.

However, I'm still interested in how they did their conversion (since I was running into missing op support when I tried). Hopefully they will respond in the [discussion](https://huggingface.co/jinaai/jina-embeddings-v2-base-en/discussions/10) linked above.

**Comment by do-me** [comment]
Awesome, thanks for looking into this. Updated in SemanticFinder too for anyone curious! :)   
Looks much better now, especially the small model returns reasonable results now. 

However, I'm still not 100% convinced of the quantized base model. Similarity for "food" for example. But maybe there is something I'm missing here... 

![](https://github.com/xenova/transformers.js/assets/47481567/f18a0ad2-2de2-4df4-9244-c6600936cd94)

**Comment by xenova** [comment]
> Looks much better now, especially the small model returns reasonable results now. 

Glad to hear!


> However, I'm still not 100% convinced of the quantized base model. Similarity for "food" for example. But maybe there is something I'm missing here... 

One possible issue is that (presumably) the model is trained on longer sequences, so it might struggle with these very short phrases? Just a total guess. In this case, you could also experiment with (1) other quantization settings, or (2) using the unquantized small model in place of the quantized base model.

**Comment by do-me** [comment]
That's what I was guessing too... I'll compare the performance with very long sequences shortly.
