### ISSUE TITLE
[Bug] Firefox fails to load large files from the cache when calling `pipeline()` from inside a worker

### ISSUE THREAD

**Issue by felladrin** [xenova/transformers.js#373]
**Bug Description**

Firefox fails to load large files from the cache when calling `pipeline()` from inside a worker.
The same files are loaded fine when calling `pipeline()` from the main thread.

I've checked if there was a similar Firefox open issue, and I only found this: <https://bugzilla.mozilla.org/show_bug.cgi?id=1436593.>

I made a local test using these two models: 
1. https://huggingface.co/Xenova/LaMini-Flan-T5-77M
2. https://huggingface.co/Xenova/LaMini-Flan-T5-248M

Facts:
- When not running inside a worker: Both load fine fine.
- When running inside a worker: The smaller always loads fine, but the larger loads fine on the first run (when it needs to download the model), but on the second time (when the model is loaded from the cache), it gets stuck loading.

It can be easily reproduced at https://huggingface.co/spaces/Xenova/react-translator

> **Note**
> It might be a _Firefox on MacOS_ specific issue.
> On MacOS, Chrome or Safari don't have this issue.
> I haven't tested it on any other OS.

**Environment**
- Transformers.js version: 2.x (Tested from 2.0.0 to 2.7.0)
- Browser: Firefox
- Operating system: MacOS

**Additional context**

When I set `env.useBrowserCache = false;` it always loads fine, which indicates the issue is about reloading the files from the browser cache.

**How to reproduce**

1. Access https://huggingface.co/spaces/Xenova/react-translator using Firefox
2. Let it run some translation for the first time.
3. Reload the page.
4. Try to run another translation, then note that the model is never loaded.

For example, notice that `onnx/decoder_model_merged_quantized.onnx` got stuck at `92.76%` for me:

<img width="1031" alt="image" src="https://github.com/xenova/transformers.js/assets/418083/9eee1378-34c0-445b-b363-6592912083d0">

**Expected behavior**

It's expected to load the models from the cache correctly, like on Chrome and Safari.

**Comment by felladrin** [comment]
I just noticed it's not a problem from Firefox failing to load larger files from the cache, but it's something with transformers.js lib.
Here's why I say that:
Tested the same model (flan-t5-base, quantized, with similar size from Xenova/LaMini-Flan-T5-248M, ~263MB) but compiled with Candle framework, and it loads fine from the cache in Firefox on every reload. Tested at <https://huggingface.co/spaces/radames/Candle-T5-Generation-Wasm>.

**Comment by xenova** [comment]
Hi there 👋 thanks for making the report. I've been able to reproduce this issue myself too (it just freezes at a different spot). Curiously, I don't see any warning or error messages in the console, which is quite odd.

It's worth pointing out that the model you are trying to load (https://huggingface.co/Xenova/nllb-200-distilled-600M) is significantly larger (476MB + 419MB = 895MB) than the ones you are testing with candle, so it's not quite a fair comparison. Also, considering that that it works with Chrome and Safari, I'm inclined to believe it is a Firefox bug.

The difference in caching code that you linked to also shouldn't be an issue. In fact, this is exactly how it was in an earlier version of Transformers.js, but it caused issues with certain LFS files. See [this commit](https://github.com/xenova/transformers.js/commit/9c449c151c1c35c3b04cd35d005a30f4ecb40c21) for where the change was made.

**Comment by felladrin** [comment]
Additional info:

I also tried using a custom cache like the following, but unfortunately, it didn't solve the issue.

```typescript
export class CustomCache {
  cacheName: string;

  constructor(cacheName: string) {
    this.cacheName = cacheName;
  }

  async match(request: Request | string) {
    const cacheName = this.cacheName;
    const cache = await caches.open(cacheName);
    return cache.match(request);
  }

  async put(request: Request | string, response: Response) {
    const cacheName = this.cacheName;
    const cache = await caches.open(cacheName);
    cache.put(request, response);
  }
}

env.useCustomCache = true;
env.customCache = new CustomCache("transformers-cache");
```

**Comment by felladrin** [comment]
Good news! 🙌 Found a way to make the cache work properly on Firefox using a custom cache, which might help develop a fix.

```typescript
const cacheName = "transformers-cache";
env.useBrowserCache = false;
env.useCustomCache = true;
env.customCache = {
  match: async (request: Request | string) => {
    const cache = await caches.open(cacheName);
    const cachedResponse = await cache.match(request);
    if (!cachedResponse) return;
    const cachedResponseBody = await cachedResponse.arrayBuffer();
    return new Response(cachedResponseBody, {
      headers: cachedResponse.headers,
    });
  },
  put: async (request: Request | string, response: Response) => {
    const cache = await caches.open(cacheName);
    await cache.put(
      request,
      new Response(response.body, {
        headers: response.headers,
      }),
    );
  },
};
```

The main difference from my previous attempt is that instead of `match()` returning the response found in the cache, it converts the response body into an `ArrayBuffer` and returns a `new Response`.
