### ISSUE TITLE
[Bug] Local Models Mode Not Usable in Web Extensions

### ISSUE THREAD

**Issue by MentalGear** [xenova/transformers.js#380]
It seems that Transformer.js uses the CacheAPI to cache models. However, the CacheAPI can't be used with urls like `chrome-extension:` or `moz-extension:` which results in `Transformer.js` failing with:
```shell
Failed to execute 'put' on 'Cache': 
Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch
```
when trying to use Local Models in Web Extensions.

**Describe the bug**
When trying to use local models in the example transformer.js chrome extension, the following error occurs.

**How to reproduce**
1. fork https://github.com/xenova/transformers.js/blob/main/examples/extension/src/background.js
2. Put the model / wasm files in a local folder
3. Use local mode in transformer.js

**Expected behavior**
Using local models.

**Logs/screenshots**
```shell
index.js:6 Unable to determine content-length from response headers. Will expand buffer when needed.
A @ index.js:6
3index.js:6 Unable to add response to browser cache: TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported.
(anonymous) @ index.js:6
index.js:6 Unable to determine content-length from response headers. Will expand buffer when needed.
A @ index.js:6
w @ index.js:6
index.js:6 Unable to add response to browser cache: TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported.
(anonymous) @ index.js:6
Promise.catch (async)
w @ index.js:6
index.js:1704 Uncaught (in promise) Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch
```

**Environment**
- Transformers.js version: 2.7.0
- Browser (if applicable): Chrome
- Operating system (if applicable): macOS

**Comment by MentalGear** [comment]
Never mind, the problem was that the wasm model was not made available in the manifest's 'web_accessible_resources'.

**Comment by MaxFrax** [comment]
@MentalGear @xenova Would either of you be able to share a working example of using local models within a Chrome extension?

I'm attempting to embed a model in the extension, but I'm running into issues with resolving the path. Any guidance would be greatly appreciated!

**Comment by MentalGear** [comment]
Don't know anymore.On 10 Sep 2024, at 16:03, Massimo ***@***.***> wrote:﻿
@MentalGear @xenova Would either of you be able to share a working example of using local models within a Chrome extension?
I'm attempting to embed a model in the extension, but I'm running into issues with resolving the path. Any guidance would be greatly appreciated!
