### ISSUE TITLE
[Feature request] Support for ahxt/llama2_xs_460M_experimental model

### ISSUE THREAD

**Issue by felladrin** [xenova/transformers.js#388]
**Support for ahxt/llama2_xs_460M_experimental model**

This text-generation model is based on llama2 and uses the gpt2 tokenizer. I think it would be a great addition to the models we can run with transformers.js.

Model on HF: https://huggingface.co/ahxt/llama2_xs_460M_experimental

I've converted it with [Optimum v1.14.0](https://github.com/huggingface/optimum/releases/tag/v1.14.0) and uploaded it [here](https://huggingface.co/Felladrin/onnx-int8-llama2_xs_460M_experimental) in case someone wants to try making it work.

**Reason for request**
The quantized version is small enough to run in desktop browsers, and it has reasonable outputs. It's trained on the RedPajama dataset.

**Comment by xenova** [comment]
Hi there 👋 Thanks for converting and contributing the model! 🤗 The issue seems to be in models.js, where the current version only supports multi head attention (and not grouped query attention; see below):

https://github.com/xenova/transformers.js/blob/c98073042f39d77eed9d52dab0e4a6c20ba3101a/src/models.js#L3038-L3040

should be

```js
this.num_heads = this.config.num_key_value_heads ?? this.config.num_attention_heads
this.num_layers = this.config.num_hidden_layers
this.dim_kv = this.config.hidden_size / this.config.num_attention_heads
```

From the [transformers codebase](https://github.com/huggingface/transformers/blob/7ee995fd9c692761c4601ddbffa2ac2ec9f27b0b/src/transformers/models/llama/configuration_llama.py#L53-L60):

> num_key_value_heads (`int`, *optional*):
>     This is the number of key_value heads that should be used to implement Grouped Query Attention. If
>     `num_key_value_heads=num_attention_heads`, the model will use Multi Head Attention (MHA), if
>     `num_key_value_heads=1 the model will use Multi Query Attention (MQA) otherwise GQA is used.

If you can test that locally, and it works, would you like to submit a PR to fix this? :)

Here's some sample code to help test (adapted from [here](https://huggingface.co/ahxt/llama2_xs_460M_experimental#using-with-huggingface-transformers)):
```js
import { AutoModelForCausalLM, AutoTokenizer } from '@xenova/transformers'

const model_path = 'Felladrin/onnx-int8-llama2_xs_460M_experimental'

const model = await AutoModelForCausalLM.from_pretrained(model_path)
const tokenizer = await AutoTokenizer.from_pretrained(model_path)

const prompt = 'Once upon a time,'
const input_ids = tokenizer(prompt).input_ids
const tokens = await model.generate(input_ids, { max_length: 20 })
console.log(tokenizer.decode(tokens[0], { skip_special_tokens: true }))
```

**Comment by felladrin** [comment]
Happy to help! I'll try it as soon as I can. Thanks for showing me the way!

**Comment by felladrin** [comment]
Great news! Got some time to test it today and it worked like a charm! 🎉 

```typescript
import { AutoModelForCausalLM, AutoTokenizer } from "http://localhost:8080/dist/transformers.js";
const model_path = "Felladrin/onnx-int8-llama2_xs_460M_experimental";
const model = await AutoModelForCausalLM.from_pretrained(model_path);
const tokenizer = await AutoTokenizer.from_pretrained(model_path);
const prompt = "Q: What is the largest bird?\nA:";
const input_ids = tokenizer(prompt).input_ids;
const tokens = await model.generate(input_ids, { max_length: 20 });
console.log(tokenizer.decode(tokens[0], { skip_special_tokens: true }));
```
<img width="361" alt="image" src="https://github.com/xenova/transformers.js/assets/418083/83ce5243-5c7e-47cf-95de-fa6db12289cf">

`Once upon a time,`:
<img width="458" alt="image" src="https://github.com/xenova/transformers.js/assets/418083/7f11007d-23e6-4ca8-bf1c-03c7ed08452a">

`"Girafatron is obsessed with giraffes, the most glorious animal on the face of this Earth. Giraftron believes all other animals are irrelevant when compared to the glorious majesty of the giraffe.\nDaniel: Hello, Girafatron!\nGirafatron:"` [[1](https://huggingface.co/tiiuae/falcon-rw-1b)] 😆 
<img width="695" alt="image" src="https://github.com/xenova/transformers.js/assets/418083/4e62a88b-a457-4c54-9ab0-8b14dfe220e9">


It's also working fine through `pipeline`!
```typescript
pipeline("text-generation", "Felladrin/onnx-int8-llama2_xs_460M_experimental")
```

Gonna open a PR with the two changed lines!
