### ISSUE TITLE
[Question] Is it possible to encode and decode with `AutoTokenizer.from_pretrained` and keep spaces?

### ISSUE THREAD

**Issue by daaain** [xenova/transformers.js#399]
I'm trying to build a pure JS online tokenizer, visually similar to https://github.com/1rgs/tokenwiz (but without the Python backend)

I'm doing something like:

```js
const model = await AutoTokenizer.from_pretrained('mistralai/Mistral-7B-v0.1')
const textInput = `[INST] <<SYS>>
You are a friendly Llama.
<</SYS>>

Do you spit at people? [/INST]`
const tokens = model.encode(textInput)
const tokenizedText = model.batch_decode(
  tokens.map((token) => [token]),
  { clean_up_tokenization_spaces: false }
)
console.log(tokenizedText)
```

And get:

```js
0: "<s>"
1: "["
2: "INST"
3: "]"
4: "<<"
5: "SYS"
6: ">>"
7: "\n"
8: "You"
9: "are"
10: "a"
11: "friendly"
12: "L"
13: "l"
14: "ama"
15: "."
16: "\n"
17: "<"
18: "</"
19: "SYS"
20: ">>"
21: "\n"
22: "\n"
23: "Do"
24: "you"
25: "sp"
26: "it"
27: "at"
28: "people"
29: "?"
30: "["
31: "/"
32: "INST"
33: "]"
```

So while newlines are there, all the spaces are gone. Is there any way to get the original text back but with token boundaries for visualisation?

**Comment by xenova** [comment]
Hi there 👋 So, although the library is functioning correctly (it is treating each new word as a separate sentence, and as a result, it is removing the initial space, if it is present). This logic can be found in the [tokenizer.json](https://huggingface.co/mistralai/Mistral-7B-v0.1/raw/main/tokenizer.json) from the repo:
```json
  "decoder": {
    "type": "Sequence",
    "decoders": [
      {
        "type": "Replace",
        "pattern": {
          "String": "▁"
        },
        "content": " "
      },
      {
        "type": "ByteFallback"
      },
      {
        "type": "Fuse"
      },
      {
        "type": "Strip",
        "content": " ",
        "start": 1,
        "stop": 0
      }
    ]
  }
```
(see the Strip decoder).

Fortunately, you can just remove this last step by adding:
```js
model.decoder.decoders.pop()
```

So,
```js
const model = await AutoTokenizer.from_pretrained('mistralai/Mistral-7B-v0.1')
model.decoder.decoders.pop()
const textInput = `[INST] <<SYS>>
You are a friendly Llama.
<</SYS>>

Do you spit at people? [/INST]`
const tokens = model.encode(textInput)
const tokenizedText = model.batch_decode(
  tokens.map((token) => [token]),
  { clean_up_tokenization_spaces: false }
)
console.log(tokenizedText)
```
which produces:
```
0: "<s>"
1: " ["
2: "INST"
3: "]"
4: " <<"
5: "SYS"
6: ">>"
7: "\n"
8: "You"
9: " are"
10: " a"
11: " friendly"
12: " L"
13: "l"
14: "ama"
15: "."
16: "\n"
17: "<"
18: "</"
19: "SYS"
20: ">>"
21: "\n"
22: "\n"
23: "Do"
24: " you"
25: " sp"
26: "it"
27: " at"
28: " people"
29: "?"
30: " ["
31: "/"
32: "INST"
33: "]"
```

---

Hope that helps! Also, I worked on a similar thing in the past, which you might find useful:
- [Demo](https://huggingface.co/spaces/Xenova/the-tokenizer-playground)
- [Code](https://github.com/xenova/transformers.js/tree/main/examples/tokenizer-playground)

**Comment by daaain** [comment]
Ah, that makes sense, thanks a lot for a quick and comprehensive answer!

Also thanks for sharing your web version, haven't come across it – probably Google isn't indexing HF Spaces?

Anyway, I was thinking of adding some extra features like models side by side and loading any model from HF, not just a preselected few. Though now seeing that each model might need some workarounds it could get tricky 🤔 

Will close this issue for now, might come back and share if I got it working!
