### ISSUE TITLE
Is it possible to run this in node?

### ISSUE THREAD

**Issue by Madd0g** [xenova/transformers.js#4]
I got this error when trying:

TypeError [ERR_WORKER_PATH]: The worker script or module filename must be an absolute path or a relative path starting with './' or '../'. Received "blob:nodedata:....

**Comment by xenova** [comment]
Hi there. Yes, this is actually a known bug in onnx runtime web. (Similar problem to this: https://github.com/microsoft/onnxruntime/issues/14445)

You can fix it as follows:
```

// 1. Fix "ReferenceError: self is not defined" bug when running directly with node
// https://github.com/microsoft/onnxruntime/issues/13072
global.self = global;

const { pipeline, env } = require('..')

// 2. Disable spawning worker threads for testing.
// This is done by setting numThreads to 1
env.onnx.wasm.numThreads = 1
```

---

You can see a working example in the testing script: https://github.com/xenova/transformers.js/blob/main/tests/index.js

(In that case, I also set `env.remoteModels=false`, for testing locally)

There

**Comment by Madd0g** [comment]
thanks, that made it work!

are you planning to integrate onnxruntime-node in the future? would be cool to be able to choose

**Comment by Madd0g** [comment]
(also seems like there's no caching when running this under node, so it redownloads the model every time)

**Comment by xenova** [comment]
> (also seems like there's no caching when running this under node, so it redownloads the model every time)

Yes, that is correct. At the moment, caching is only implemented with the [Cache Web API](https://developer.mozilla.org/en-US/docs/Web/API/Cache).

I will hopefully add that functionality soon, so that it acts in a similar way to huggingface's system, which downloads it to your file system.

**Comment by dkogut1996** [comment]
Im getting the `ReferenceError: self is not defined` bug when running in typescript and trying to import `Autotokenizer`.

I have `global.self = global` at the top of the file, and vscode complains with this error: 
`Type 'typeof globalThis' is not assignable to type 'Window & typeof globalThis'.
  Type 'typeof globalThis' is missing the following properties from type 'Window': name, yerba, nodeCrypto, __NEXT_DATA__`

Importing using `import { AutoTokenizer } from '@xenova/transformers'` and simply referencing the class produces the reference error.

Any ideas how this would work in ts?

**Comment by xenova** [comment]
> Im getting the `ReferenceError: self is not defined` bug when running in typescript and trying to import `Autotokenizer`.
> 
> I have `global.self = global` at the top of the file, and vscode complains with this error: `Type 'typeof globalThis' is not assignable to type 'Window & typeof globalThis'.`
> 
> Importing using `import { AutoTokenizer } from '@xenova/transformers'` and simply referencing the class produces the reference error.
> 
> Any ideas how this would work in ts?

I unfortunately haven't worked with typescript before, so, I wouldn't be able to give you very good advice 😅 ... However, I do intend to one day convert the library to TS!

In the meantime, I tried asking Chat-GPT. Here are some of its answers. Do take it with a grain of salt though, because I don't quite know 😅 
![image](https://user-images.githubusercontent.com/26504141/225717217-58c0d639-cf4a-44c1-a11d-c9d5123e5e3c.png)
![image](https://user-images.githubusercontent.com/26504141/225717257-f7d2bcc5-fc1a-4607-808c-f7f69a97d9f8.png)


--- 

In future, I will use the actual `onnxruntime-node` package (https://www.npmjs.com/package/onnxruntime-node)

**Comment by dkogut1996** [comment]
Ah ok, those didn't work but it was hilarious. 

I'm actually using your tokenizer classes so that I may use onnxruntime-node without having to rewrite the tokenizer libraries for the various LLMs out there. This repo is awesome and you've been very responsive, so thanks so much for all the help!

**Comment by xenova** [comment]
> Ah ok, those didn't work but it was hilarious.
> 
> I'm actually using your tokenizer classes so that I may use onnxruntime-node without having to rewrite the tokenizer libraries for the various LLMs out there. This repo is awesome and you've been very responsive, so thanks so much for all the help!

Great! 👍  No worries 😄 

getting this version working out-of-the-box for node + typescript is on the TODO list :)

**Comment by Madd0g** [comment]
> Ah ok, those didn't work but it was hilarious.

I have this on the top of the file:

```
(global as any).self = global;
```

Actually CGPT suggested better approaches, since this will not fly in a strict: true codebase.
