### ISSUE TITLE
[chinese characters] Transformers.js library’s pipeline output is inconsistent with transformers pipeline

### ISSUE THREAD

**Issue by skirodev** [xenova/transformers.js#40]
When using the pipeline from transformers.js library for inference, the output answer span and score are very different from the results obtained by using transformers Pipeline. Specifically, when inputting the same question and passage, the answer span output by transformers.js library is not in the passage, and has a low score; while the answer span output by transformers Pipeline is in the passage, and has a high score. This indicates that there is a problem with the question answering model from transformers.js library.

After testing, I found that under the condition of using the same model and input, the output results of fill mask and question answering are very different from transformers pipeline.

**Comment by xenova** [comment]
Hi. Could you provide code examples?

**Comment by skirodev** [comment]
**This is an example of fill-mask task:**
**Model:** voidful/albert_chinese_base (from hf)

**Python Code:**
```python
model_name = "uer/albert-base-chinese-cluecorpussmall"
text = "巴黎是[MASK]国的首都。"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForMaskedLM.from_pretrained(model_name)
pipe = FillMaskPipeline(model, tokenizer)
res = pipe(text)
print(res)
```

**Transformers Pipeline Output:**
```json
[{
	'score': 0.46445780992507935,
	'token': 3791,
	'token_str': '法',
	'sequence': '巴 黎 是 法 国 的 首 都 。'
}, {
	'score': 0.3918287456035614,
	'token': 5739,
	'token_str': '英',
	'sequence': '巴 黎 是 英 国 的 首 都 。'
}, {
	'score': 0.081468366086483,
	'token': 5401,
	'token_str': '美',
	'sequence': '巴 黎 是 美 国 的 首 都 。'
}, {
	'score': 0.02443750388920307,
	'token': 2548,
	'token_str': '德',
	'sequence': '巴 黎 是 德 国 的 首 都 。'
}, {
	'score': 0.014028741046786308,
	'token': 2349,
	'token_str': '巴',
	'sequence': '巴 黎 是 巴 国 的 首 都 。'
}]
```

**Javascript Code:**
```js
import pkg from '@xenova/transformers';
const { pipeline, env } = pkg;
env.localURL = '../python/models/onnx/';
env.remoteModels = false;

let text = "巴黎是[MASK]国的首都。"
let pipe = await pipeline("fill-mask", "unquantized/uer/albert-base-chinese-cluecorpussmall");
let out = await pipe(text);
console.log(res)
```

**Transformers.js Pipeline Output:**
```json
[{
		score: 0.050597261637449265,
		token: 4374,
		token_str: '王',
		sequence: '巴黎是 王 国的首都。'
	},
	{
		score: 0.04205408692359924,
		token: 704,
		token_str: '中',
		sequence: '巴黎是 中 国的首都。'
	},
	{
		score: 0.026475369930267334,
		token: 3791,
		token_str: '法',
		sequence: '巴黎是 法 国的首都。'
	},
	{
		score: 0.01747741736471653,
		token: 2270,
		token_str: '岛',
		sequence: '巴黎是 岛 国的首都。'
	},
	{
		score: 0.016568319872021675,
		token: 5401,
		token_str: '美',
		sequence: '巴黎是 美 国的首都。'
	}
]
```

**Comment by xenova** [comment]
Okay right, I remember having issues with huggingface's optimum library when exporting albert models in the past. I might need to raise an issue there.

I'll investigate and get back to you as soon as I can.

**Comment by xenova** [comment]
Could you perhaps try to export an unquantized version of the model, and see if that works? Albert models might have some issues when quantizing the weights. Still investigating.

**Comment by xenova** [comment]
While I look into this further, can you provide the command used to convert the pytorch model to ONNX?

**Comment by skirodev** [comment]
Yes, I am using the unquantized model.
```
let pipe = await pipeline("fill-mask", "unquantized/voidful/albert_chinese_base");
```

**Comment by xenova** [comment]
Okay thanks. I was able to reproduce it on my side, so this might be an issue with how the chinese characters are handled by the tokenizer. Looking into it!

**Comment by xenova** [comment]
Found the problem! I wasn't surrounding CJK characters with a space (which is what the model expects). And now, the quantized and unquantized versions produce the correct results:
```js
env.remoteModels = false;
env.localURL = '../models/onnx/unquantized/';
// env.localURL = '../models/onnx/quantized/';

// Allocate a pipeline for sentiment-analysis
let pipe = await pipeline('fill-mask', 'voidful/albert_chinese_base');

let out = await pipe('巴黎是[MASK]国的首都。');
console.log(out);
```

outputs:
```
[
  {"score":0.46445417404174805,"token":3791,"token_str":"法","sequence":"巴 黎 是 法 国 的 首 都 。"},
  {"score":0.391830176115036,"token":5739,"token_str":"英","sequence":"巴 黎 是 英 国 的 首 都 。"},
  {"score":0.08146943897008896,"token":5401,"token_str":"美","sequence":"巴 黎 是 美 国 的 首 都 。"},
  {"score":0.02443740703165531,"token":2548,"token_str":"德","sequence":"巴 黎 是 德 国 的 首 都 。"},
  {"score":0.014028149656951427,"token":2349,"token_str":"巴","sequence":"巴 黎 是 巴 国 的 首 都 。"}
]
```

and the quantized version outputs:
```
[
  {"score":0.5039321184158325,"token":3791,"token_str":"法","sequence":"巴 黎 是 法 国 的 首 都 。"},
  {"score":0.3531384766101837,"token":5739,"token_str":"英","sequence":"巴 黎 是 英 国 的 首 都 。"},
  {"score":0.0629461407661438,"token":5401,"token_str":"美","sequence":"巴 黎 是 美 国 的 首 都 。"},
  {"score":0.03310180827975273,"token":2548,"token_str":"德","sequence":"巴 黎 是 德 国 的 首 都 。"},
  {"score":0.012472438625991344,"token":2349,"token_str":"巴","sequence":"巴 黎 是 巴 国 的 首 都 。"}
]
```

Fixed in https://github.com/xenova/transformers.js/commit/b48a6095bb12ce3cb8406dab8c0559071d88b8a7

In the meantime (before I push a proper release), you can install the package from this repo.

**Comment by xenova** [comment]
I also added those model files to the HF repo: https://huggingface.co/Xenova/transformers.js/tree/main/quantized/voidful/albert_chinese_base

so, you can just use
`let pipe = await pipeline('fill-mask', 'voidful/albert_chinese_base');` now

**Comment by xenova** [comment]
These changes are now live in version 1.3.2! (https://www.npmjs.com/package/@xenova/transformers/v/1.3.2)

Closing the issues now :)
