### ISSUE TITLE
[Bug] Audio distortions in quantized speecht5_tts model

### ISSUE THREAD

**Issue by yeirr** [xenova/transformers.js#406]
**Describe the bug**
*A clear and concise description of what the bug is.*

Unexpected audio distortions from quantized speecht5_tts, non-quantized version do not output audio distortions.

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*
```
const { env, pipeline } = await import('https://cdn.jsdelivr.net/npm/@xenova/transformers@2.8.0/dist/transformers.min.js');

env.allowRemoteModels = true;
env.allowLocalModels = false;
env.localModelPath = '/models/';

self.speaker_embeddings = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/speaker_embeddings.bin';

self.synthesizer = await pipeline('text-to-speech', 'Xenova/speecht5_tts', {
    quantized: false, // quantized version output audio distortion
  });

let data = await synthesizer('Hello world', { speaker_embeddings });
```
**Expected behavior**
*A clear and concise description of what you expected to happen.*

Non-quantized speecht5_tts model to not produce audio distortions.

**Environment**
- Transformers.js version:2.8.0
- Browser (if applicable):chrome(v119|v120)
- Operating system (if applicable):ubuntu 22.04 lts

**Comment by xenova** [comment]
Hi there :wave: Yes, this is a known limitation of the quantized models (which is why the [code-snippets in the docs](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.TextToAudioPipeline) only use the unquantized versions). My understanding is that this is because the spectrogram calculations require a high-level of precision (8-bit is too low). @Vaibhavs10 can probably give some extra insight here.

**Comment by yeirr** [comment]
Hi @xenova, thanks for pointing me in the right direction.

May I clarify which models are you referring to? Because I only observed a single tts model under 'transformers/scripts/supported_models.py'

```py
'speecht5': [
        # Text-to-speech
        'microsoft/speecht5_tts',
],
```

**Comment by kungfooman** [comment]
Just a full reproduction for being able to listen to in directly in the browser:

```js
/**
 * @param {number} numFrames 
 * @param {object} [options]
 * @param {number} [options.numChannels]
 * @param {number} [options.sampleRate]
 * @param {number} [options.bytesPerSample]
 * @param {number} [options.format]
 * @returns {ArrayBuffer}
 */
function buildWaveHeader(numFrames, {
  numChannels    =     1, // 2...
  sampleRate     = 16000, // 44100, 48000, ...
  bytesPerSample =     2,
  format         =     3, // 1 = unsigned integers, 3 = floats
} = {}) {
  const blockAlign = numChannels * bytesPerSample;
  const byteRate   = sampleRate * blockAlign;
  const dataSize   = numFrames * blockAlign;
  const buffer     = new ArrayBuffer(44);
  const dv         = new DataView(buffer);
  let p = 0;
  function writeString(s) {
    for (var i = 0; i < s.length; i++) {
      dv.setUint8(p + i, s.charCodeAt(i));
    }
    p += s.length;
  }
  function writeUint32(d) {
    dv.setUint32(p, d, true);
    p += 4;
  }
  function writeUint16(d) {
    dv.setUint16(p, d, true);
    p += 2;
  }
  writeString('RIFF');              // ChunkID
  writeUint32(dataSize + 36);       // ChunkSize
  writeString('WAVE');              // Format
  writeString('fmt ');              // Subchunk1ID
  writeUint32(16);                  // Subchunk1Size
  writeUint16(format);              // AudioFormat
  writeUint16(numChannels);         // NumChannels
  writeUint32(sampleRate);          // SampleRate
  writeUint32(byteRate);            // ByteRate
  writeUint16(blockAlign);          // BlockAlign
  writeUint16(bytesPerSample * 8);  // BitsPerSample
  writeString('data');              // Subchunk2ID
  writeUint32(dataSize);            // Subchunk2Size
  return buffer;
}
/**
 * @param {Float32Array | Uint8Array} samples
 * @param {object} [options]
 * @param {number} [options.sampleRate]
 * @param {number} [options.numChannels]
 * @param {boolean} [options.isFloat]
 * @returns {HTMLAudioElement}
 */
function initAudio(samples, {
  sampleRate = 16000,
  numChannels = 1, // mono or stereo
  isFloat = true,  // integer or floating point
} = {}) {
  const buffer = samples.buffer;
  // create WAV header
  const format = isFloat ? 3 : 1;
  const header = buildWaveHeader(samples.length, {
    bytesPerSample: samples.BYTES_PER_ELEMENT,
    sampleRate,
    numChannels,
    format
  });
  // show audio player
  const audio = document.createElement('audio');
  // Create one blob containing header and PCM audio
  const blob = new Blob([header, samples], {type: 'audio/wav'});
  audio.src = URL.createObjectURL(blob);
  audio.controls = true;
  document.body.appendChild(audio);
  return audio;
}
const {pipeline} = await import('https://cdn.jsdelivr.net/npm/@xenova/transformers@2.8.0/dist/transformers.min.js');
const speaker_embeddings = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/speaker_embeddings.bin';
const synthesizer = await pipeline('text-to-speech', 'Xenova/speecht5_tts', {
  quantized: false, // quantized version output audio distortion
});
const data = await synthesizer('Hello world, don\'t count the days, make the days count. Wubba lubba dub dub!', { speaker_embeddings });
initAudio(data.audio);
```

**Comment by yeirr** [comment]
> Just a full reproduction for being able to listen to in directly in the browser:
> 
> ```js
> /**
>  * @param {number} numFrames 
>  * @param {object} [options]
>  * @param {number} [options.numChannels]
>  * @param {number} [options.sampleRate]
>  * @param {number} [options.bytesPerSample]
>  * @param {number} [options.format]
>  * @returns {ArrayBuffer}
>  */
> function buildWaveHeader(numFrames, {
>   numChannels    =     1, // 2...
>   sampleRate     = 16000, // 44100, 48000, ...
>   bytesPerSample =     2,
>   format         =     3, // 1 = unsigned integers, 3 = floats
> } = {}) {
>   const blockAlign = numChannels * bytesPerSample;
>   const byteRate   = sampleRate * blockAlign;
>   const dataSize   = numFrames * blockAlign;
>   const buffer     = new ArrayBuffer(44);
>   const dv         = new DataView(buffer);
>   let p = 0;
>   function writeString(s) {
>     for (var i = 0; i < s.length; i++) {
>       dv.setUint8(p + i, s.charCodeAt(i));
>     }
>     p += s.length;
>   }
>   function writeUint32(d) {
>     dv.setUint32(p, d, true);
>     p += 4;
>   }
>   function writeUint16(d) {
>     dv.setUint16(p, d, true);
>     p += 2;
>   }
>   writeString('RIFF');              // ChunkID
>   writeUint32(dataSize + 36);       // ChunkSize
>   writeString('WAVE');              // Format
>   writeString('fmt ');              // Subchunk1ID
>   writeUint32(16);                  // Subchunk1Size
>   writeUint16(format);              // AudioFormat
>   writeUint16(numChannels);         // NumChannels
>   writeUint32(sampleRate);          // SampleRate
>   writeUint32(byteRate);            // ByteRate
>   writeUint16(blockAlign);          // BlockAlign
>   writeUint16(bytesPerSample * 8);  // BitsPerSample
>   writeString('data');              // Subchunk2ID
>   writeUint32(dataSize);            // Subchunk2Size
>   return buffer;
> }
> /**
>  * @param {Float32Array | Uint8Array} samples
>  * @param {object} [options]
>  * @param {number} [options.sampleRate]
>  * @param {number} [options.numChannels]
>  * @param {boolean} [options.isFloat]
>  * @returns {HTMLAudioElement}
>  */
> function initAudio(samples, {
>   sampleRate = 16000,
>   numChannels = 1, // mono or stereo
>   isFloat = true,  // integer or floating point
> } = {}) {
>   const buffer = samples.buffer;
>   // create WAV header
>   const format = isFloat ? 3 : 1;
>   const header = buildWaveHeader(samples.length, {
>     bytesPerSample: samples.BYTES_PER_ELEMENT,
>     sampleRate,
>     numChannels,
>     format
>   });
>   // show audio player
>   const audio = document.createElement('audio');
>   // Create one blob containing header and PCM audio
>   const blob = new Blob([header, samples], {type: 'audio/wav'});
>   audio.src = URL.createObjectURL(blob);
>   audio.controls = true;
>   document.body.appendChild(audio);
>   return audio;
> }
> const {pipeline} = await import('https://cdn.jsdelivr.net/npm/@xenova/transformers@2.8.0/dist/transformers.min.js');
> const speaker_embeddings = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/speaker_embeddings.bin';
> const synthesizer = await pipeline('text-to-speech', 'Xenova/speecht5_tts', {
>   quantized: false, // quantized version output audio distortion
> });
> const data = await synthesizer('Hello world, don\'t count the days, make the days count. Wubba lubba dub dub!', { speaker_embeddings });
> initAudio(data.audio);
> ```

This is helpful @kungfooman, very much appreciated. I have success in implementing Web Audio API by sending the generated audio samples(Float32Array) as audiobuffer to web client audiocontext for playback using the default configurations provided by speecht5_tts.
