### ISSUE TITLE
Error: There was an error while processing timestamps, we haven't found a timestamp as last token.

### ISSUE THREAD

**Issue by ldenoue** [xenova/transformers.js#42]
On longer audio files (e.g. > 1 minute or so), I get this error:
```
Uncaught (in promise) Error: There was an error while processing timestamps, we haven't found a timestamp as last token.
    at Function._decode_asr (tokenizers.js:1497:23)
    at Function._call (pipelines.js:489:56)
```

My worker code is as this:
```
importScripts('https://cdn.jsdelivr.net/npm/@xenova/transformers/dist/transformers.min.js');
async function speech_to_text(data) {
	let pipe = await pipeline('automatic-speech-recognition','openai/whisper-tiny.en');
    return await pipe(data.audio, {
		top_k: 0,
		do_sample: false,
		chunk_length_s: 30,
		stride_length_s: 5,
		return_timestamps: true,
		force_full_sequences: false,
    })
}
```

Is there anything I can do to prevent this error?

**Comment by xenova** [comment]
Sure, let me try with a longer audio clip. In the meantime, could you try using these options:
```
max_new_tokens: Infinity,

// Greedy
top_k: 0,
do_sample: false,

// Sliding window
chunk_length_s: 30,
stride_length_s: 5,

// Return timestamps
return_timestamps: true,
```

**Comment by xenova** [comment]
Okay - in the meantime, I pushed this: https://github.com/xenova/transformers.js/commit/7b751ec71fe8cb8454714f863be4b4b0df39dd27

which means you can just call the pipeline with an option to not force full sequences:
```js
let output = await transcriber(audio, {
    max_new_tokens: Infinity,

    // Greedy
    top_k: 0,
    do_sample: false,

    // Sliding window
    chunk_length_s: 30,
    stride_length_s: 5,

    // Return timestamps
    return_timestamps: true,
    force_full_sequences: false,

    // Return finalised chunks
    return_chunks: true,

    // Run callback after each generation step
    callback_function: callback_function
});
```

This should serve as a suitable hot-fix while we wait for HF to respond: https://github.com/huggingface/optimum/issues/906. I'll make a full release once it is completely resolved.

**Comment by xenova** [comment]
Just an update. Looks like a new PR has been submitted which will fix this issue. I will update the models when it gets merged into main. 👍 
- https://github.com/huggingface/optimum/pull/919

**Comment by xenova** [comment]
While they clean up some additional issues:
- https://github.com/huggingface/optimum/issues/921

Is this still an issue in the later versions of Transformers.js? I am trying to reproduce on the latest version, but - even with older models - I can't seem to get the bug.

I'm not too sure if I changed anything, but I don't seem to get the error anymore.

**Comment by ldenoue** [comment]
This seems to have disappeared. We can probably close.
