### ISSUE TITLE
[Bug] Failed to Load Model due to Protobuf Parsing Issue in React Translator Demo

### ISSUE THREAD

**Issue by WildXBird** [xenova/transformers.js#420]
**Describe the bug**

The built-in demo is not running, and the same issue occurs when trying to call the function in my own project. Specifically, when using Yarn to compile the examples\react-translator and hosting it with IIS on my localhost's root directory, clicking "translate" results in an error: "Failed to load model because protobuf parsing failed."

```
Unable to determine content-length from response headers. Will expand buffer when needed.
worker-1384d3d3.js:1790 Unable to determine content-length from response headers. Will expand buffer when needed.
worker-1384d3d3.js:8 Failed to load model because protobuf parsing failed.
worker-1384d3d3.js:8 Failed to load model because protobuf parsing failed.
worker-1384d3d3.js:1789 Uncaught (in promise) Error: Can't create a session
    at n.createSessionFinalize (http://localhost/assets/worker-1384d3d3.js:1789:105945)
    at n.createSession (http://localhost/assets/worker-1384d3d3.js:1789:106543)
    at n.createSession (http://localhost/assets/worker-1384d3d3.js:1789:98867)
    at n.OnnxruntimeWebAssemblySessionHandler.loadModel (http://localhost/assets/worker-1384d3d3.js:1789:101717)
    at async Object.createSessionHandler (http://localhost/assets/worker-1384d3d3.js:9:114993)
    at async dn.create (http://localhost/assets/worker-1384d3d3.js:1:14796)
    at async constructSession (http://localhost/assets/worker-1384d3d3.js:1790:85994)
    at async Promise.all (index 1)
    at async M2M100ForConditionalGeneration.from_pretrained (http://localhost/assets/worker-1384d3d3.js:1790:93325)
    at async AutoModelForSeq2SeqLM.from_pretrained (http://localhost/assets/worker-1384d3d3.js:1790:129738)

```
I am encountering issues with both the built-in demo and my own project. 

**Logs/screenshots**
![QQ截图20231128185126](https://github.com/xenova/transformers.js/assets/32768476/8b6bf606-13e8-4119-ba77-9ac529f81c2e)

**Environment**
Transformers.js version: 2.9.0
Browser: Chrome Version 119
Operating system: Windows 10 (Version 21H2)

**Additional context**
I will also encounter the same error when I run this html:
```
<html lang="zh" sml:lang="zh">

<head>
    <meta charset="utf-8">
    <title>Frames</title>
    <script type="module">
        import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.9.0';
        // Allocate a pipeline for sentiment-analysis
        let pipe = await pipeline('sentiment-analysis');//Error at here
        let out = await pipe('I love transformers!');
        console.warn("out", out)
        // [{'label': 'POSITIVE', 'score': 0.999817686}]
    </script>

</head>

<body>
123
</body>

</html>
```

**Comment by xenova** [comment]
Could you try skipping the local model check?
```js
import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.9.0';
env.allowLocalModels=false;
```

I believe the issue you are facing is that the local model check does not fail with a 404 error, so it thinks the models are stored locally.

**Comment by WildXBird** [comment]
> Could you try skipping the local model check?
> 
> ```js
> import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.9.0';
> env.allowLocalModels=false;
> ```
> 
> I believe the issue you are facing is that the local model check does not fail with a 404 error, so it thinks the models are stored locally.

still the same

![QQ截图20231129095235](https://github.com/xenova/transformers.js/assets/32768476/76583396-9dde-41bd-a1c6-21b15acd2de5)
![QQ截图20231129095211](https://github.com/xenova/transformers.js/assets/32768476/ea8f9e16-b7d2-441f-bdfa-e307e3db307b)
![QQ截图20231129095149](https://github.com/xenova/transformers.js/assets/32768476/33cbb557-684f-42f5-9da0-c80d48489065)

```
    <script type="module">
        import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.9.0';
        env.allowLocalModels = false;

        let pipe = await pipeline('sentiment-analysis');
        let out = await pipe('I love transformers!');
        console.warn("out", out)//this works

        let translator = await pipeline('translation');//Error at here
        let output = await translator('hell');
       
    </script>
```

**Comment by xenova** [comment]
Could you try refresh your cache (/ try in incognito)? It might have cached the incorrect model.

**Comment by WildXBird** [comment]
> Could you try refresh your cache (In the Application tab) or try in incognito mode? It might have cached the incorrect model.

It works
Maybe it would be better to give a more detailed error message or automatically clear the model cache when loading fails

**Comment by WildXBird** [comment]
> Yes, it should do that, but it may be that your error page does not return the 404 error code, so the library thinks that the request was made successfully. If you are able to, could you try see what the error code is?

It looks like it tried to access the local model in the directory, but the server returned status code 200
![QQ截图20231129203202](https://github.com/xenova/transformers.js/assets/32768476/13e83b99-4fe6-4410-82c5-8b913b156e37)

**Comment by xenova** [comment]
> but the server returned status code 200

As I expected :) So, I believe that is the root of the issue. If you ensure that your 404 error page does return the 404 error code, then transformers.js will ignore the contents returned, and fallback to the remote server.

**Comment by Mihaiii** [comment]
@xenova 

I have the exact same error, but in my case I actually do try to load the model from local.
The path seems to be ok since the tokenizer seems to be loaded:

![image](https://github.com/xenova/transformers.js/assets/8951553/3748c9ce-1d25-4bbe-8a15-50b9dc1ca56b)

```js
    const getPipeline = async () =>  {
      let tokenizer = await AutoTokenizer.from_pretrained('bert-base-cased_onnx-quantized')
      debugger;
      let model = await AutoModel.from_pretrained('bert-base-cased_onnx-quantized')
      //embeddingsPipeline.current = await pipeline("embeddings", "bert-base-cased_onnx-quantized")
    }
    console.log('was here');
    env.allowLocalModels = true;
    env.allowRemoteModels = false;
    env.localModelPath = 'm';
    //TODO: remove
    env.useBrowserCache = false;
    getPipeline()
```


I got the files downloaded through `git clone` and the model file size seems ok (as in "not an git lfs" issue).

![image](https://github.com/xenova/transformers.js/assets/8951553/a94c5932-f648-4f68-acfd-08f5963a7f91)

Any ideas?

**Comment by Mihaiii** [comment]
@xenova Hello! :) It works! Thank you very much! 🙏

**Comment by Mihaiii** [comment]
@xenova Thanks again for all the help! I launched a React component based on transformers.js .

Your work is truly awesome! I thanked you in the readme.md of my repo - all the magic is done inside transformers.js . Let me know if I can do anything to promote your work. 💜
