### ISSUE TITLE
[Question] feature-extraction discrepancies across different platforms

### ISSUE THREAD

**Issue by devfacet** [xenova/transformers.js#426]
I'm observing discrepancies in feature-extraction results across different platforms. Here's the code:

```js
import { pipeline, env } from '@xenova/transformers'

const extractor = await pipeline('feature-extraction', 'Xenova/gte-small', {
  quantized: false,
  cache_dir: './.cache',
  local_files_only: false,
})

const text = 'hello'
const embedding = await extractor(text, { pooling: 'mean', normalize: true })
const response = Array.from(embedding.data)
console.log(JSON.stringify(response, null, 2))

// Node v20
// "@xenova/transformers": "^2.9.0"
```

The results differ between macOS 13 (Apple Silicon/Arm) and Ubuntu 23.1 (Raspberry Pi/Arm). I've tried various configurations (e.g., pooling, normalize, with and without Array.from) and still observe different results. It's worth noting that sequential calls on the same platform produce consistent results.

I have a few questions:

1. Is this discrepancy expected due to the nature of float32 precision and rounding, even though the calculations are performed on ARM architecture?
2. Given that the difference is extremely small, could it still impact accuracy in any significant way?

[mean-nonorm-mac-01.json](https://github.com/xenova/transformers.js/files/13530082/mean-nonorm-mac-01.json)
[mean-nonorm-pi-01.json](https://github.com/xenova/transformers.js/files/13530083/mean-nonorm-pi-01.json)
[mean-norm-mac-01.json](https://github.com/xenova/transformers.js/files/13530084/mean-norm-mac-01.json)
[mean-norm-pi-01.json](https://github.com/xenova/transformers.js/files/13530086/mean-norm-pi-01.json)

**Comment by devfacet** [comment]
Great! Thank you for quick response.

**Comment by 4ortytwo** [comment]
@xenova Hi! Sorry for randomly posting here. Wasn't sure if it was ok to create an issue for that so I chose one of the more recent ones. Really appreciate all the work you're doing. 

I'd like to created embeddings for social posts and comments, and I'm using `Supabase/gte-small` right now with verctor dimensions of 384. 

I was just wondering if there is a better model you'd recommend and whether 384 is enough to implement semantic search, sentiment analysis, and recommendations later on. 

Sorry for this random post!

**Comment by xenova** [comment]
Hey @4ortytwo 👋 You can check out the [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard) to help inform your decision: it ranks models across a wide variety of benchmarks, categorized by tasks. There are even categories for retrieval, classification, and clustering which you can sort by.

Regarding embedding dimension - and as you probably already saw - Supabase has a great [article](https://supabase.com/blog/fewer-dimensions-are-better-pgvector) on this: where they show the benefits of using fewer dimensions. Ultimately, it is use-case-specific, but I generally think 384 is good enough for simple tasks like the ones you are describing. As of today, `gte-small` is the 2nd-highest ranked open model w/ 384 dimensions (and 20 overall), only beaten by `bge-small-en-v1.5` which is ranked 13 overall. See transformers.js compatible [version](https://huggingface.co/Xenova/bge-small-en-v1.5)) for example usage in transformers.js.

You can also try use the unquantized versions if you'd like to trade higher memory with improved accuracy:
```js
const extractor = await pipeline('feature-extraction', 'Supabase/gte-small', { quantized: false });
```

**Comment by 4ortytwo** [comment]
Thank you a lot for finding the time to reply and pointing me toward these resources, @xenova 🙏❤️
