### ISSUE TITLE
Add VITS model

### ISSUE THREAD

**Issue by gramedcart** [xenova/transformers.js#429]
**VITS pipeline**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

pipeline: [VITS](https://huggingface.co/docs/transformers/v4.35.2/en/model_doc/vits#overview)

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

I would like to add this pipeline so vits model can be used in the browser. because the VITS have wide variety of models other than T5 TTS.

**Comment by xenova** [comment]
Hi there 👋 This is indeed something we are working on! The first step is to get the ONNX export working with optimum, which @echarlaix is working on! 🚀 

I'll keep you updated with the progress 👍

**Comment by xenova** [comment]
PR opened here: https://github.com/xenova/transformers.js/pull/466 🥳
