### ISSUE TITLE
SigLIP model support

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#430]
SigLIP seems quite good/efficient!

https://twitter.com/giffmana/status/1717999891937394990

> On retrieval, even the smallest SigLIP ViT-B/16 (86M params) outperforms the largest public EVA CLIP ViT-e/14 (3926M params), META ViT-H, CLIPA ViT-H etc.

https://twitter.com/wightmanr/status/1717577862381994176

> The results tables in OpenCLIP were updated by gabriel_ilharco yesterday to break out more detailed retrieval oriented tasks into their own csv. SigLIP is wow!

https://twitter.com/gabriel_ilharco/status/1718007897517609173

![image](https://github.com/xenova/transformers.js/assets/1167575/97fe8cd3-84fe-47a4-9d7e-93ec531caf30)

![image](https://github.com/xenova/transformers.js/assets/1167575/ff9c477a-61b7-4f2a-87b8-e457a98d3df7)

**Comment by xenova** [comment]
The model is currently being added to the python library ([PR](https://github.com/huggingface/transformers/pull/26522)), and when it is ready, we can add it here too :)

**Comment by xenova** [comment]
PR here: https://github.com/xenova/transformers.js/pull/473
