### ISSUE TITLE
`zero-shot-object-detection` percentage: true does not work

### ISSUE THREAD

**Issue by tobiascornille** [xenova/transformers.js#433]
### System Info

transformers.js v2.9.0

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

```js
const output = await detector(img, candidate_labels, { percentage: true });
```
returns results with absolute pixel values for the bounding boxes.

### Reproduction

Look at the console logs when running this space: [https://huggingface.co/spaces/segments-tobias/owlvit-transformers-js](https://huggingface.co/spaces/segments-tobias/owlvit-transformers-js)

**Comment by xenova** [comment]
Thanks for the bug report - you're right, we are not saving the image sizes correctly before computing the bounding boxes. I've opened a PR with the fix: https://github.com/xenova/transformers.js/pull/434

Will merge soon and push a release once tests pass

**Comment by tobiascornille** [comment]
Nice, now it's working as expected!
[https://huggingface.co/spaces/segments-tobias/owlvit-transformers-js](https://huggingface.co/spaces/segments-tobias/owlvit-transformers-js)
