### ISSUE TITLE
error TS2510: Base constructors must all have the same return type.

### ISSUE THREAD

**Issue by devfacet** [xenova/transformers.js#437]
### System Info

Node: v20.9.0
tsc: The TypeScript Compiler - Version 5.2.2

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I've been building my app with `tsc` for quite a while. Today, I tried to upgrade `@xenova/transformers` from `2.7.0` to `2.10.1` but if tailed due to the error below. `2.8.0` works fine, but it doesn't work `2.9.0` and afterward.

### Reproduction

```
npm install @xenova/transformers@2.10.1
echo "import { pipeline, Pipeline } from '@xenova/transformers'" > index.ts
tsc index.ts
```

```
node_modules/@xenova/transformers/types/utils/tensor.d.ts:75:29 - error TS2510: Base constructors must all have the same return type.

75 export class Tensor extends Tensor_base {
                               ~~~~~~~~~~~
Found 1 error in node_modules/@xenova/transformers/types/utils/tensor.d.ts:75
```

**Comment by parhammmm** [comment]
just a note it's happening inside https://github.com/run-llama/LlamaIndexTS as well, ran into it today

**Comment by devfacet** [comment]
🎉 Thank you, I can't wait for the next release.
