### ISSUE TITLE
Error: failed to call OrtRun(). error code = 1. with gpt2-danish model

### ISSUE THREAD

**Issue by uahmad235** [xenova/transformers.js#457]
### System Info

transformers.js v2.11.0
Python v3.8.10

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I am trying to generate text using [this gpt2](https://huggingface.co/KennethTM/gpt2-small-danish) model and getting following error:
![Screenshot from 2023-12-16 20-39-59](https://github.com/xenova/transformers.js/assets/30628125/a899874b-ace4-4db0-a23d-f1d23bfabbaf)

### Reproduction

Install scripts dependencies from [here](https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt). The convert model using following command: 
```python -m scripts.convert --model_id KennethTM/gpt2-small-danish --task text-generation-with-past```
The output shows succesful model conversion. Put model in `/models` directory and load it using followiing code:

```js
import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.11.0';

env.localModelPath = '/models/';
const text_generation_pipe = await pipeline(
    'text-generation',
    'gpt2-small-danish',
   {
        quantized: false,
   },
)
  const input = longTextInput.value;  // getting from text field
  const result = await text_generation_pipe(input, {
      max_new_tokens: 50,
  });

```

**Comment by xenova** [comment]
The first warning message suggests an error with the conversion. I am able to run the model with the following code:
```js
env.localModelPath = './models/';
const text_generation_pipe = await pipeline(
    'text-generation',
    'KennethTM/gpt2-small-danish',
   {
        quantized: false,
   },
)
const input = 'Test';  // getting from text field
const result = await text_generation_pipe(input, {
    max_new_tokens: 50,
});
console.log(result);
// [ { generated_text: 'Test, der er en del af den nye app, er at det er muligt at få en række forskellige funktioner, som du kan bruge til at forbedre din brugeroplevelse.\nDu kan få en række forskellige funktioner, som du kan bruge til at forbedre din brugeroplevelse' } ]
```

Can you please provide the versions of `onnx`, `onnxruntime`, `transformers`, and `optimum`?

**Comment by uahmad235** [comment]
Ah nice.
Here are the versions you asked for.
Let me try uploading the converted model to HF hub as well.
```
transformers==4.33.2
onnx==1.13.1
onnxruntime==1.15.1
optimum==1.13.2
```

**Comment by uahmad235** [comment]
Here are model weights @xenova 
https://huggingface.co/uahmad235/gpt2-small-danish/tree/main

**Comment by xenova** [comment]
Hmm, very strange: I am able to run it without any issue:
```js
import { pipeline } from '@xenova/transformers';

const text_generation_pipe = await pipeline('text-generation', 'uahmad235/gpt2-small-danish', { quantized: false });
const input = 'Test';  // getting from text field
const result = await text_generation_pipe(input, {
    max_new_tokens: 50,
});
console.log(result);
```
outputs:
```
[ { generated_text: 'Test, der er en del af den nye app, er at det er muligt at få en række forskellige funktioner, som du kan bruge til at forbedre din brugeroplevelse.\nDu kan få en række forskellige funktioner, som du kan bruge til at forbedre din brugeroplevelse'}]
```
Can you provide the input for which it fails?

Here's a JSFiddle link showing it working in-browser: https://jsfiddle.net/Ln230bfs/

**Comment by uahmad235** [comment]
Oh. It was due to some caching issue with browser. I changed my browser and it worked!
Thank you again for the help.

**Comment by xenova** [comment]
Glad to hear! :)
