### ISSUE TITLE
Missing decoder_model_merged.onnx file when using the converter tool to convert a flan-alpaca model to onnx

### ISSUE THREAD

**Issue by CSFM93** [xenova/transformers.js#460]
### System Info

transformer.js version 2.12.1

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I tried to use the latest version of the convert to onnx script to convert an alpaca-flan pytorch model to onnx, but it didn't generate the `decoder_model_merged.onnx` file . 

### Reproduction

Because of this I am getting the following error when I try to create a pipeline:
```text
@xenova/transformers/src/utils/hub.js:462
                    throw Error(`\`local_files_only=true\` or \`env.allowRemoteModels=false\` and file was not found locally at "${localPath}".`);
                          ^
Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "models/flan-alpaca-base/onnx/decoder_model_merged_quantized.onnx".
```

I tried to rename the existing decoder file to `decoder_model_merged.onnx` but when I try to run an inference I get the following:
Code:
```js  
let generator = await pipeline('text2text-generation', 'flan-alpaca-base', { quantized: true });
let res = await generator('What is python?', { max_new_tokens: 1024 })
console.log("res", res)
```
Output:
```text
WARNING: Too many inputs were provided (51 > 3). The following inputs will be ignored: "past_key_values.0.encoder.key, past_key_values.0.encoder.value, past_key_values.0.decoder.key, past_key_values.0.decoder.value, past_key_values.1.encoder.key, past_key_values.1.encoder.value, past_key_values.1.decoder.key, past_key_values.1.decoder.value, past_key_values.2.encoder.key, past_key_values.2.encoder.value,... ".
res [ { generated_text: 'Python' } ]
```
Thanks for creating such an amazing tool :smile:

**Comment by xenova** [comment]
Hi there 👋 Could you confirm whether your versions of `onnx`, `onnxruntime`, and `transformers` match those specified [here](https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt) in the conversion script requirements? I just did a conversion on https://huggingface.co/declare-lab/flan-alpaca-large (which I just guessed since it has the same name as the one you are trying to run), and it seems to work without an issue:
```js
import { pipeline } from "@xenova/transformers";

// Create a text2text-generation pipeline
const generator = await pipeline('text2text-generation', 'Xenova/flan-alpaca-base');

// Generate text
const output = await generator('What is Python?', { max_length: 128, do_sample: true, top_k: 10, });
console.log(output);
// [{ generated_text: 'Python is a programming language used in many applications, such as machine learning, database management, and graphical application development. It is a multi-functional language which works across various data sets and platforms.' }]
```

I've uploaded the ONNX weights to https://huggingface.co/Xenova/flan-alpaca-base.

**Comment by CSFM93** [comment]
@xenova The error was on my end. I selected the wrong task when using the convert script.

The task I entered was `text2text-generation`:
```bash
python -m convert --quantize --model_id "declare-lab/flan-alpaca-base" --task text2text-generation
```

Instead of the correct one which is `text2text-generation-with-past`:
```bash
python -m convert --quantize --model_id "declare-lab/flan-alpaca-base" --task text2text-generation-with-past
```
The model you uploaded is working as expected. Thank you for your help.

**Comment by xenova** [comment]
That's great to hear! :) For future, you shouldn't need to specify the task in most cases, as this is auto-determined from the model configuration.

**Comment by CSFM93** [comment]
I specified the task because I was using a locally hosted version of the flan-alpaca model and unfortunately, the convert script was unable to recognize the task.

**Comment by xenova** [comment]
Oh yes that's correct. The model type is determined from the tags on the Hugging Face Hub. Anyway, glad you got your problem solved!
