### ISSUE TITLE
[Model request] mT5 (for more languages to use for translation)

### ISSUE THREAD

**Issue by fakerybakery** [xenova/transformers.js#47]
Hello!
Thanks for making this great repository!
I was trying to implement machine translation and found that any language other than `en`, `de`, and `ro` does not work. Might it be possible to implement a more multilingual t5 model, such as [Google's multilingual t5](https://github.com/google-research/multilingual-t5)?
Thank you!

**Comment by xenova** [comment]
> Hi, I actually don't have a Python version (I'm starting from JavaScript) but thank you for your fast response!

No worries! I'll see what I can do 😉

**Comment by xenova** [comment]
mT5 is now supported (https://github.com/xenova/transformers.js/commit/4e967885b8f5bdcf1c5bbd36ad04c93ba27f3438).

However, please note that the [google/mt5-small](https://huggingface.co/google/mt5-small) model has **NOT been finetuned** on downstream tasks like translation.

This means that you would need to finetune a model if you want to perform translation (or something else). For more information, check out this issue:
 - https://github.com/huggingface/transformers/issues/8704
