### ISSUE TITLE
throw 'Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON' when computing vision embeddings with `CLIPVisionModelWithProjection`

### ISSUE THREAD

**Issue by cloydlau** [xenova/transformers.js#472]
### System Info

@xenova/transformers@2.12.1
chrome@120.0.6099.129
mac@14.1.2
node@20.10.0
vite@5.0.10

### Environment/Platform

- [x] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

When I run this example code from: https://github.com/xenova/transformers.js/blob/4112429d3807d07349817cda9d3d62ec7e61047a/src/models.js#L3053
It throws 'Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON'

```js
// CLIP Vision Model with a projection layer on top (a linear layer on top of the pooled output)

// **Example:** Compute vision embeddings with `CLIPVisionModelWithProjection`.

import { AutoProcessor, CLIPVisionModelWithProjection, RawImage } from '@xenova/transformers'

// Load processor and vision model
const processor = await AutoProcessor.from_pretrained('Xenova/clip-vit-base-patch16')
const vision_model = await CLIPVisionModelWithProjection.from_pretrained('Xenova/clip-vit-base-patch16')

// Read image and run processor
const image = await RawImage.read('https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/football-match.jpg')
const image_inputs = await processor(image)

// Compute embeddings
const { image_embeds } = await vision_model(image_inputs)
console.log(image_embeds)
// Tensor {
//   dims: [ 1, 512 ],
//   type: 'float32',
//   data: Float32Array(512) [ ... ],
//   size: 512
// }
```

### Reproduction

1. Setup a bare enviroment like `npm create vite@latest`
2. Copy the example code from: https://github.com/xenova/transformers.js/blob/4112429d3807d07349817cda9d3d62ec7e61047a/src/models.js#L3053

**Comment by xenova** [comment]
Hi there 👋 In most cases, this in intentional and is because (like the python library), we check your local server first for the model files before downloading them from the Hugging Face Hub. If your server correctly returns the 404 status when the model file is not found, it will fallback to the server. If you want to avoid this local model check, you can add the following to the top of your code:
 
```js
import { env } from '@xenova/transformers';
env.allowLocalModels=false;
```

You can then refresh your cache and try again.

**Comment by cloydlau** [comment]
Thank you for your the prompt response, but even if I tried:

```js
import { AutoProcessor, CLIPVisionModelWithProjection, RawImage, env } from '@xenova/transformers'

// CLIP Vision Model with a projection layer on top (a linear layer on top of the pooled output)

// **Example:** Compute vision embeddings with `CLIPVisionModelWithProjection`.

env.allowLocalModels = false

// Load processor and vision model
const processor = await AutoProcessor.from_pretrained('Xenova/clip-vit-base-patch16')
const vision_model = await CLIPVisionModelWithProjection.from_pretrained('Xenova/clip-vit-base-patch16')

// Read image and run processor
const image = await RawImage.read('https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/football-match.jpg')
const image_inputs = await processor(image)

// Compute embeddings
const { image_embeds } = await vision_model(image_inputs)
console.log(image_embeds)
// Tensor {
//   dims: [ 1, 512 ],
//   type: 'float32',
//   data: Float32Array(512) [ ... ],
//   size: 512
// }
```

I got the same result.

**Comment by xenova** [comment]
Are you sure you cleared the cache correctly? If you did, could you please inspect the network tab to see what page is being returned from Hugging Face? Here's a JSFiddle link which should show correct behaviour: https://jsfiddle.net/r6ext9a0/ (i.e., a float array being printed to the console).

**Comment by cloydlau** [comment]
Your JSFiddle link works fine.

When enabling incognito mode my local repo works fine too:
![image](https://github.com/xenova/transformers.js/assets/31238760/be6a52e4-d964-4b4b-a9f9-1042f2817fda)

Without incognito mode + disable cache + cleared cache in all time + hard reload:
![image](https://github.com/xenova/transformers.js/assets/31238760/7b455903-2123-4545-81a6-2de1fbd755c3)

I'm confused.

**Comment by xenova** [comment]
Transformers.js caches files using the Web Cache API, which won't be disabled by selecting "disable cache" (which is the network cache). You should be able to clear the cache by visiting the "Application" section in chrome dev tools.

**Comment by cloydlau** [comment]
Solved, thanks!
