### ISSUE TITLE
mms-tts model errors

### ISSUE THREAD

**Issue by escottgoodwin** [xenova/transformers.js#476]
### System Info

Vite react app based on text-to-speech example app from repo

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

https://huggingface.co/Xenova/mms-tts-eng

Unknown tokenizer class "VitsTokenizer", attempting to construct from base class.

@xenova_transformers.js?v=93977bdd:25175 Uncaught (in promise) Error: Unsupported model type: vits
    at AutoModelForTextToSpectrogram.from_pretrained (@xenova_transformers.js?v=93977bdd:25175:13)
    at async @xenova_transformers.js?v=93977bdd:29306:21

GET https://huggingface.co/Xenova/mms-tts-eng/resolve/main/preprocessor_config.json 404 (Not Found)

### Reproduction

Use code example from 
https://huggingface.co/Xenova/mms-tts-eng

**Comment by xenova** [comment]
Hi there 👋 this is because the PR which adds support for VITS has not been merged yet. https://github.com/xenova/transformers.js/pull/466

**Comment by xenova** [comment]
The next version ([2.13.0](https://www.npmjs.com/package/@xenova/transformers/v/2.13.0)) has been released, which adds support for VITS.
