### ISSUE TITLE
[Feature request] Improve technical debt

### ISSUE THREAD

**Issue by DavidGOrtega** [xenova/transformers.js#48]
To allow proper collaboration and healthiness we need to reduce some current technical debt. Something like [CML](https://github.com/iterative/cml/). Disclaimer: I did that

 - [ ] linter
 - [ ] unit tests
 - [ ] Github actions checks
 - [ ] Github actions releases

**Comment by xenova** [comment]
I do plan on reworking the repo to fit a set of standards, which will definitely help potential contributors get started. One day! 🤣

**Comment by xenova** [comment]
These are now all implemented.
