### ISSUE TITLE
Unrecognized token '<' when running

### ISSUE THREAD

**Issue by philg-204** [xenova/transformers.js#483]
### Question

I downloaded the react translation example. When I start the app everything seems to render fine, but as soon as I press translate, nothing happens and I get this error in the console on the browser: 
`Unhandled Promise Rejection: SyntaxError: JSON Parse error: Unrecognized token '<'`

I've gotten this same issue trying to run other models keeping things very basic as found here: https://huggingface.co/docs/transformers.js/pipelines

UPDATE: This error only happens in Safari, but it works fine in Chrome. 

If I try to make the simplest example with react like in the tutorial link it fails in both chrome and safari

**Comment by xenova** [comment]
Hi there 👋 This is most likely a duplicate of https://github.com/xenova/transformers.js/issues/472. Could you try adding the following to the top of your code:
```js
import { env } from '@xenova/transformers';
env.allowLocalModels=false;
```

Please note you may need to reset your cache, since the local version (which does not exist) may have been cached.

**Comment by philg-204** [comment]
That was it. Thanks!
