### ISSUE TITLE
TypeScript Pipline Types for different models?

### ISSUE THREAD

**Issue by wesbos** [xenova/transformers.js#484]
### Question

Is there a suggested way to get types for the different models? Right now after I create a pipline, like one of the following:

```
const segmenter = await pipeline('image-segmentation', 'Xenova/face-parsing');
// or 
const extractor = await pipeline(`feature-extraction`, `Xenova/UAE-Large-V1`, {
  quantized: true, // Set this to false to use the full (unquantized) model
});
```

All the methods and returned values are `(...args: any[]) => any` - finding it hard to work with the methods and returned values.

I realize each model returns different outputs, and I'm fairly new to the whole convertion process, but are these types kept somewhere in the Python or the json files with the model that could be used as typescript types? 

Ideally `pipeline` would infer the types, but I'm also ok with importing (or generating the types myself) and using it as a generic:

```
const whateve = pipeline<ReturnType>(`task`, `model`)
```

**Comment by xenova** [comment]
Hi there 👋 Yes, this is absolutely something that needs improving. The correct types for the input parameters should be taken from the `_call` function, but I haven't gotten around to doing that. Here are the docs which show the valid input parameters: https://huggingface.co/docs/transformers.js/api/pipelines.

Perhaps you know of a good way to do this with JSDoc?

**Comment by xenova** [comment]
@kungfooman might have some insight here.

[Here's](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgArAA4QDahQbwF8BYAKFElkRQBUIAPMAYWzgGc3gZgE4xgA9iHRZcIAiXLho8JMgCSAWzgBzCC3aduvfkJE48yImTJgAnlmQ0LKALzIA5JEYBaBKw5cefQSAfIAH0dgZTU3Dy1vXT8AbmQAenjkOBAAE2Q2AWQhADo8k1IyGABXEARo5AxMA3EAHhpkBkg0tisbZHsAImcwcM0vHV9OgD4ACmK2aGssAH4ALisASjmyZCtGxggWxx6+z20fIX8ZqyaNfajffTEIVeQFhqat1NaHENUIPcjBo+QTpQ+52+h2E1RudwW1zwZHwdzWUAgYGKUBARkIyVaKTMMTIkiqojwoycTS+AxBDkWCSSdEYQLJ0Sh4jI+JqECJ7zC7n6B2iFKpClC6gi9KuYLwQA) a basic TS version which seems to work:

```ts
interface Pipeline {}
interface TextClassificationPipeline {}
interface ImageClassificationPipeline {}

type Type = 'text-classification' | 'image-classification'; // and so on...


function pipeline<T extends Type = "text-classification">(userType?: T):
  T extends 'text-classification' ? TextClassificationPipeline
  : T extends 'image-classification' ? ImageClassificationPipeline
  : Pipeline
{
    return {} as any;
}
pipeline('text-classification') // TextClassificationPipeline
pipeline('image-classification') // ImageClassificationPipeline
```
