### ISSUE TITLE
Output different from sentence transformers

### ISSUE THREAD

**Issue by leodalcin** [xenova/transformers.js#486]
### Question

Hello, i'm not sure if i'm doing something wrong, but the pooled outputs from sentence transformers and this library seem to be different.
The results are the same if I use `pooling: 'none'` in js and `output_value='token_embedding` in python.
I've seen some other similar issues, but this seems to be a different problem.

```js
const fs = require('fs');
class MyClassificationPipeline {
  static task = 'feature-extraction';
  static model = 'Xenova/distiluse-base-multilingual-cased-v2';
  static instance = null;

  static async getInstance(progress_callback = null) {
    if (this.instance === null) {
      // Dynamically import the Transformers.js library
      let { pipeline, env } = await import('@xenova/transformers');

      // NOTE: Uncomment this to change the cache directory
      // env.cacheDir = './.cache';

      this.instance = pipeline(this.task, this.model, { progress_callback, quantized: false });
    }

    return this.instance;
  }
}

// Comment out this line if you don't want to start loading the model as soon as the server starts.
// If commented out, the model will be loaded when the first request is received (i.e,. lazily).
MyClassificationPipeline.getInstance();

async function main() {
  const classifier = await MyClassificationPipeline.getInstance();
  const res = await classifier('This is an example sentence', { pooling: 'mean', normalize:false });
  fs.writeFileSync('./xenova-embedding.json', JSON.stringify(res.data, null, 2), 'utf-8');
}

main();
```

```python
import json
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v2')
embedding = model.encode("This is an example sentence")

with open('embeddings.json', 'w') as f:
    json.dump(embedding.tolist(), f)
```

Am i missing something?

**Comment by leodalcin** [comment]
I just noticed the size of the vector is also different 512 for python and 768 for js.
Could it be that the final model layer is missing? Here is the model architecture:
```
SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: DistilBertModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Dense({'in_features': 768, 'out_features': 512, 'bias': True, 'activation_function': 'torch.nn.modules.activation.Tanh'})
)
```

**Comment by leodalcin** [comment]
> I just noticed the size of the vector is also different 512 for python and 768 for js. Could it be that the final model layer is missing? Here is the model architecture:
> 
> ```
> SentenceTransformer(
>   (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: DistilBertModel 
>   (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
>   (2): Dense({'in_features': 768, 'out_features': 512, 'bias': True, 'activation_function': 'torch.nn.modules.activation.Tanh'})
> )
> ```

By removing this layer from the original python model I achieved a similar output between the libraries. Around 6 digits of precision, so i suppose it's the same results.

I wonder how and if this impacts training though.

**Comment by xenova** [comment]
Hi there 👋 Yes, these models were exported before sentence-transformers support was added to Optimum ([PR](https://github.com/huggingface/optimum/pull/1589); [original issue](https://github.com/huggingface/optimum/issues/1519)). So, if you upgrade to the latest version of optimum (or install from main), you should be able to export and get the same outputs + shape.

**Comment by leodalcin** [comment]
Thank you for the answer!
I'll close this since i think it's solved.

**Comment by leodalcin** [comment]
Hey hey, just to give some context if somebody faces this issue, it seems like converting `distiluse-base-multilingual-cased-v2` still has some issues, you can follow up here: https://github.com/huggingface/optimum/issues/1621
