### ISSUE TITLE
[Feature request] Split out the demo site from the library

### ISSUE THREAD

**Issue by DavidGOrtega** [xenova/transformers.js#49]
The site source code should be removed from the library.
There are several solutions:

 - Make this repo a monorepo: I would use Lerna to keep and maintain the examples and the library all together with many packages:
    - transformers
    - demo
  - Split out the demo in another repo

**Comment by xenova** [comment]
Agreed 👍 What about moving it to another branch? GitHub pages allows hosting from a specific branch.

**Comment by DavidGOrtega** [comment]
> What about moving it to another branch?

It might be a bit confusing for contributors? I only worked that way within a project that I did with Lucene having a branch per version. Outcome: a total craziness 😆

**Comment by xenova** [comment]
This is also done. The demo site and example apps have been moved to the [examples](https://github.com/xenova/transformers.js/tree/main/examples) folder.
