### ISSUE TITLE
Support for the phi-1.5 model in transformers.js

### ISSUE THREAD

**Issue by bil-ash** [xenova/transformers.js#492]
### Model description

Please add support for the microsoft/phi-1.5 model to transformers.js. The model is really powerful when considering the size and should also fit in the 2gb model size limit. It is alo supported by optimum.

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [X] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Your contribution

none

**Comment by thekevinscott** [comment]
[I'm trying to run this model via this URL](https://huggingface.co/Xenova/phi-1_5_dev).

In Chrome Version 120.0.6099.216 (Official Build) (arm64) I see the following for the sample code:

```
An error occurred during model execution: "RangeError: offset is out of bounds".
```

Models are being loaded off of Hugging Face. I'm on an M3 Max.

<img width="925" alt="Screenshot 2024-01-11 at 10 05 13 AM" src="https://github.com/xenova/transformers.js/assets/151596/0f0245ed-718a-4860-9bd0-09c6ec23b0f0">

**Comment by xenova** [comment]
Hi there 👋  This is indeed a known issue (see https://github.com/xenova/transformers.js/issues/499), and will hopefully be fixed when we upgrade the onnxruntime-web version.

**Comment by thekevinscott** [comment]
Ah gotcha, thanks @xenova ! I'll follow along there.
