### ISSUE TITLE
in-browser inference slower than node inference to be expected?

### ISSUE THREAD

**Issue by carlojoerges** [xenova/transformers.js#494]
### Question

i noticed that i get much higher performance when i run inference in node vs in the browser (latest chrome, m2 mac, ). is that generally to be expected? for context - i'm creating embeddings for chunks of text using the gte-small model. 
thank you!

**Comment by xenova** [comment]
Hi there 👋 Yes, this is indeed expected, as the browser version uses [onnxruntime-web](https://www.npmjs.com/package/onnxruntime-web)'s WASM backend (slower), while the node version uses [onnxruntime-node](https://www.npmjs.com/package/onnxruntime-node)'s CPU backend (and runs at native speeds using pre-built binaries).

**Comment by carlojoerges** [comment]
Makes sense, thanks for the quick response!

**Comment by paschaldev** [comment]
I also noticed I got a better performance on 32GB RAM M1 mac. However, it was way slower on a 16GB core i7, the 900b translation model in the example takes more than 2 minutes to run and return a result in the browser after loading the models.

@xenova any tips for performance gain?
