### ISSUE TITLE
Service worker in Typescript

### ISSUE THREAD

**Issue by spencekim** [xenova/transformers.js#5]
I am trying to duplicate your example service worker code here in order to run the models outside of the main thread: https://github.com/xenova/transformers.js/blob/main/assets/js/worker.js 

However, my codebase is written in Typescript rather than Javascript, and I get the error `Cannot find name 'env'` because you set the path to the wasm files like so: `env.onnx.wasm.wasmPaths = DIST_DIR;`. 

Where is the `env` object initialized?

**Comment by xenova** [comment]
The line above it:
```javascript
importScripts(DIST_DIR + 'transformers.min.js');
```

imports the library and makes the necessary exports (including env) available:
(see [here](https://github.com/xenova/transformers.js/blob/main/src/transformers.js#LL24-LL46))

**Comment by spencekim** [comment]
Got it. Closing this issue. Thank you!
