### ISSUE TITLE
[Model request] GPT-Neo

### ISSUE THREAD

**Issue by zap8600** [xenova/transformers.js#50]
Would it be possible to add [GPT-Neo](https://huggingface.co/docs/transformers/model_doc/gpt_neo) as an available model? I believe it is pretty similar to GPT-2, as they both use `GPT2Tokenizer`, so I don't think it should be too difficult to implement. It would also be pretty cool to have a model that knows things like quantum entanglement since it was trained on The Pile.

**Comment by xenova** [comment]
Do you have an example of which exact model you are looking to use? I believe some GPT-Neo models are quite large (>4 GB). And currently, ONNX uses 32-bit WASM, meaning a theoretical max model size of 4GB. (64-bit WASM is in the works though).

**Comment by xenova** [comment]
GPT Neo is now supported :) (https://www.npmjs.com/package/@xenova/transformers/v/1.3.4)

**Comment by zap8600** [comment]
Thanks! This is a pretty interesting repo, and I can't wait to get further into it.
