### ISSUE TITLE
Error: Can't create a session

### ISSUE THREAD

**Issue by wizardAEI** [xenova/transformers.js#502]
### System Info

os: mac-arm
node: v18.18.2
electron: "28.0.0",
electron-vite: "^1.0.27",

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Hello! I want to use transformers.js in an Electron application, but I've encountered some issues. Can you please take a look?

An error occurred when importing ONNX file in the main process of Electron.

### Reproduction

when i want to load the model:
```ts
export async function embedding(text: string) {
  const { AutoTokenizer, CLIPTextModelWithProjection, env } = await import('@xenova/transformers')
  env.localModelPath = getResourcesPath('models')
  env.backends.onnx.wasm.numThreads = 1
  env.cacheDir = getResourcesPath('cache')
  let tokenizer = await AutoTokenizer.from_pretrained('Xenova/bert-base-chinese')
  const text_model = await CLIPTextModelWithProjection.from_pretrained('Xenova/bert-base-chinese', {
    model_file_name: 'model'
  })
  // Run tokenization
  let text_inputs = tokenizer([text], { padding: true, truncation: true })
  // Compute embeddings
  const res = await text_model(text_inputs)
  console.log(res.logits.data)
}
```
there is the error:

```
Error: Can't create a session
    at e.createSessionFinalize (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-web/dist/ort-web.node.js:6:450535)
    at e.createSession (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-web/dist/ort-web.node.js:6:451133)
    at e.createSession (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-web/dist/ort-web.node.js:6:443359)
    at e.OnnxruntimeWebAssemblySessionHandler.loadModel (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-web/dist/ort-web.node.js:6:446253)
    at async Object.createSessionHandler (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-web/dist/ort-web.node.js:6:156051)
    at async m.create (/Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/onnxruntime-common/dist/ort-common.node.js:6:11924)
    at async constructSession (file:///Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/@xenova/transformers/src/models.js:143:16)
    at async Promise.all (index 1)
    at async BertModel.from_pretrained (file:///Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/@xenova/transformers/src/models.js:785:20)
    at async AutoModel.from_pretrained (file:///Users/wangdejiang/Desktop/Gomoon/Gomoon/node_modules/@xenova/transformers/src/models.js:4993:20)

Node.js v18.18.2
```

**Comment by wizardAEI** [comment]
Additionally, I'm confused why the error is reported in the '/node_modules/onnxruntime-web' directory instead of onnxruntime-node.

**Comment by xenova** [comment]
Hi there 👋  Have you tried our example electron app template ([link](https://github.com/xenova/transformers.js/tree/main/examples/electron))?

**Comment by wizardAEI** [comment]
I just tried it on an Electron instance and got the same error. Could it be that I made a mistake in my operation?
![image](https://github.com/xenova/transformers.js/assets/61337085/b1e32163-42c9-460f-b97f-fc2ff6eea928)

**Comment by xenova** [comment]
The onnxruntime backend (web or node) is selected using this line:
https://github.com/xenova/transformers.js/blob/07df34ff3308cf3b1ab830a547bd9bcf22869783/src/backends/onnx.js#L32

Could you manually check the values of these?

**Comment by wizardAEI** [comment]
i cant console there. but when I commented out part of the code but still got errors.
![image](https://github.com/xenova/transformers.js/assets/61337085/2c3d6dbb-7282-4c52-82ab-c092234e70cf)

**Comment by wizardAEI** [comment]
and I log in the /node_modules/@xenova/transformers/src/utils/hub.js :

![image](https://github.com/xenova/transformers.js/assets/61337085/b2ef7fed-7b2e-4c47-98f3-c5e008e17f49)

print the node in the terminal

**Comment by wizardAEI** [comment]
> > I just tried it on an Electron template and got the same error. Could it be that I made a mistake in my operation?
> 
> Are you saying that without any modifications to the example template, you are experiencing these issues?

No, I made some changes, mainly to introduce local model. All the modifications are annotated in the above picture.

**Comment by xenova** [comment]
Can you confirm that the path does indeed map to the correct location? Also, if you are able to add debug statements, could you try see what paths are used here:

https://github.com/xenova/transformers.js/blob/07df34ff3308cf3b1ab830a547bd9bcf22869783/src/utils/hub.js#L331

**Comment by wizardAEI** [comment]
its right path
![image](https://github.com/xenova/transformers.js/assets/61337085/4cc34fd6-717d-4b04-9015-69fc95e9902e)

**Comment by wizardAEI** [comment]
I'm really sorry, I just noticed that my onnx file somehow became an empty file at some point.

**Comment by wizardAEI** [comment]
I'll try again after re-downloading the onnx file.

**Comment by xenova** [comment]
No worries! 😇 Let's hope that's the fix! 🤞

**Comment by wizardAEI** [comment]
I succeeded in running!

Really sorry, my negligence has caused you such a long delay!

Thank you very much.
![image](https://github.com/xenova/transformers.js/assets/61337085/7645a7cf-c2c0-48e4-80b0-40da821270f9)

**Comment by xenova** [comment]
Great! 🥳 Absolutely no worries :) Glad it's sorted 🚀
