### ISSUE TITLE
how can I view all the results in text-classification

### ISSUE THREAD

**Issue by sammwafy** [xenova/transformers.js#506]
I am using text-classifications for labels and I wanted to see all scores not the final prediction like in python
is there a way in transformers.js ?

**Comment by xenova** [comment]
Hi there 👋 As stated [here](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.TextClassificationPipeline) in the documentation, you can set `topk` to `null` to return all classes:

```js
const classifier = await pipeline('text-classification', 'Xenova/toxic-bert');
const output = await classifier('I hate you!', { topk: null });
// [
//   { label: 'toxic', score: 0.9593140482902527 },
//   { label: 'insult', score: 0.16187334060668945 },
//   { label: 'obscene', score: 0.03452680632472038 },
//   { label: 'identity_hate', score: 0.0223250575363636 },
//   { label: 'threat', score: 0.019197041168808937 },
//   { label: 'severe_toxic', score: 0.005651099607348442 }
// ]
```

**Comment by sammwafy** [comment]
I was adding it as a third argument to pipeline
it works, thank you
