### ISSUE TITLE
Discrepancy between transformers.js and Python transformers

### ISSUE THREAD

**Issue by pkesseli** [xenova/transformers.js#517]
### System Info

Framework: Next.js
transformers.js: 2.14.0
Python: 3.11.7
Python transformers: 4.36.2

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Tokenizing the same string in Python using `BertTokenizer` works, whereas in transformers.js I receive `undefined` elements in the tokenised array and transformers.js throws an exception.

### Reproduction

1. Generate Python output
```python
tokenizer: BertTokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")
print(tokenizer("Hallo Dunkelheit, mein alter Freund!"))
# > {'input_ids': [101, 11763, 10133, 14925, 53770, 10161, 15543, 117, 70273, 42141, 42624, 106, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
```
2. Generate transformers.js output (will throw an exception)
```typescript
let tokenizer: PreTrainedTokenizer = await BertTokenizer.from_pretrained("bert-base-multilingual-cased");
tokenizer("Hallo Dunkelheit, mein alter Freund!");
```
```
tokenizers.js:2734 Uncaught (in promise) TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at Array.map (<anonymous>)
    at Function._call (tokenizers.js:2734:75)
    at closure (core.js:77:28)
    at eval (tokenizer.ts:8:3)
```
4. To check the value of the encoded tokens, put a breakpoint here:
```javascript
result[key] = new _utils_tensor_js__WEBPACK_IMPORTED_MODULE_3__.Tensor('int64',BigInt64Array.from(encodedTokens.flatMap(x=>x[key]).map(BigInt)),dims); // Line 2733
```
5. Show the value of `encodedTokens` in the browser console:
```
> encodedTokens
[{…}]
- 0:
 - attention_mask: (9) [1, 1, 1, 1, 1, 1, 1, 1, 1]
 - input_ids: (9) [101, undefined, undefined, 117, 70273, 42141, 42624, 106, 102]
 - token_type_ids: (9) [0, 0, 0, 0, 0, 0, 0, 0, 0]
```

It looks like the two environments would generally generate the same encoded tokens, but the tensorflow.js one is shorter and contains `undefined` elements which cause an exception. Am I misusing the API somehow?

**Comment by xenova** [comment]
Hi there 👋 This is because the tokenizer_config of `bert-base-multilingual-cased` is incomplete: https://huggingface.co/bert-base-multilingual-cased/blob/main/tokenizer_config.json (it was exported with a very old version of transformers/tokenizers). You can use the updated version `Xenova/bert-base-multilingual-cased` as follows:

```js
import { BertTokenizer } from '@xenova/transformers';

const tokenizer = await BertTokenizer.from_pretrained("Xenova/bert-base-multilingual-cased");
const { input_ids } = tokenizer("Hallo Dunkelheit, mein alter Freund!");

console.log(input_ids)
// Tensor {
//     dims: [ 1, 13 ],
//     type: 'int64',
//     data: BigInt64Array(13) [
//         101n, 11763n, 10133n,
//       14925n, 53770n, 10161n,
//       15543n,   117n, 70273n,
//       42141n, 42624n,   106n,
//         102n
//     ],
//     size: 13
// }  
```

**Comment by pkesseli** [comment]
Excellent, that appears to resolve it. Thank you!
