### ISSUE TITLE
Error with convert script, failed at this line: optimize_model=False as unexpected parameter, and also MatMul error

### ISSUE THREAD

**Issue by gidzr** [xenova/transformers.js#527]
### System Info

Debian, running convert.py script in CLI

latest onnx, optimum, and python3.10

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Hi Xenova

When running the latest convert.py script, get:

Quantizing:   0%|                                         | 0/4 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/home/admin/convert.py", line 428, in <module>
    main()
  File "/home/admin/convert.py", line 404, in main
    quantize([
  File "/home/admin/convert.py", line 237, in quantize
    quantize_dynamic(
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model

I hashed out #optimize_model=False, to remove it from the script and re-ran, but then got: Ignore MatMul due to non constant B:

### Reproduction

python3.10 xenova_convert.py --model_id facebook/mbart-large-50-many-to-many-mmt --quantize true --output_parent_dir /home/admin/ONNX_QUANT/MBART50-MMT_xenova_text2textwithpast --task text2text-generation-with-past --opset 18 --device cpu --per_channel true --reduce_range true;

**Comment by gidzr** [comment]
I came across this:

https://github.com/facebookresearch/segment-anything/issues/585
https://github.com/tensorflow/tensorrt/issues/93

and am testing this approach:

pip uninstall onnxruntime
pip install onnxruntime==1.15.1

**Comment by gidzr** [comment]
Yup.. this fixed it.

What's with onnxruntime==1.16 issues? when will this get fixed?

**Comment by kaamlaS** [comment]
hey, was anyone able to fix the "ignore matmul due to non constant b" issue?
