### ISSUE TITLE
BertTokenizer fails on specific words with 'cannot convert undefined to a BigInt'

### ISSUE THREAD

**Issue by jobergum** [xenova/transformers.js#532]
### System Info

React with @xenova/transformers ^ 2.14.0

```
"dependencies": {
    "@xenova/transformers": "^2.14.0",
    "onnxruntime-web": "^1.16.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.1",
    "typescript": "^4.5.4",
    "wasm-feature-detect": "^1.2.11",
    "web-vitals": "^2.1.2"
  },
```

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

The transformer.js BertTokenizer implementation seems to fail with certain subwords, for example, "oppen" which is split into two subwords in the transformer Python implementation and encoded as [6728, 11837] sub-word ids. 

```python
from transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_tokenizer("oppen", add_special_tokens=False)
```

With the transformers.js implementation this fails: (it does not matter if add_special_tokens is false/true) 

```javascript
import { BertTokenizer } from '@xenova/transformers'

const bert_tokenizer = await BertTokenizer.from_pretrained('bert-base-uncased');
await bert_tokenizer("oppen", {add_special_tokens:false})
```
Fails with 
```
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at Array.map (<anonymous>)
    at Function._call (tokenizers.js:2693:1)
    at closure (core.js:62:1)
```

### Reproduction

```javascript
import { BertTokenizer } from '@xenova/transformers'

const bert_tokenizer = await BertTokenizer.from_pretrained('bert-base-uncased');
await bert_tokenizer("oppen", {add_special_tokens:true})
```

**Comment by xenova** [comment]
Hi there, this is because the model you are trying to use has an incomplete tokenizer config. Please use `Xenova/bert-base-uncased`

**Comment by jobergum** [comment]
Thank you, that resolves it!
