### ISSUE TITLE
Text to speech generation using Xenova/mms-tts-por

### ISSUE THREAD

**Issue by Darksoulsong** [xenova/transformers.js#547]
### Question

Hi! First of all, thank you for the awesome library, it's been handy so far!

I've got 2 questions regarding TTS:

- I'm using the model above to create a Brazilian Portuguese spoken audio and would like to know if there are options for this model, eg.: changing the voice from male to female, and the intonation.

- I discovered another model `facebook/mms-tts-por` in the compatible languages list, but I'm getting the following error: "'Could not locate file: "https://huggingface.co/facebook/mms-tts-por/resolve/main/tokenizer.json".'". Is transformer.js compatible with it?

Thanks in advance

**Comment by xenova** [comment]
> I'm using the model above to create a Brazilian Portuguese spoken audio and would like to know if there are options for this model, eg.: changing the voice from male to female, and the intonation.

If you can't find a suitable checkpoint on the [HF Hub](https://huggingface.co/models?other=vits&sort=downloads), your best option will probably be to check out [this repo](https://github.com/ylacombe/finetune-hf-vits) by @ylacombe, which shows how to finetune VITS and MMS models for your use-case.

> I discovered another model facebook/mms-tts-por in the compatible languages list, but I'm getting the following error: "'Could not locate file: "https://huggingface.co/facebook/mms-tts-por/resolve/main/tokenizer.json".'". Is transformer.js compatible with it?

The transformers.js-compatible version of that model can be found at https://huggingface.co/Xenova/mms-tts-por (replace `facebook` with `Xenova` in your code).

**Comment by Darksoulsong** [comment]
> If you can't find a suitable checkpoint on the [HF Hub](https://huggingface.co/models?other=vits&sort=downloads), your best option will probably be to check out [this repo](https://github.com/ylacombe/finetune-hf-vits) by @ylacombe, which shows how to finetune VITS and MMS models for your use-case.

Great, I'll check that out. Thank you for giving me directions.

**Comment by kallebysantos** [comment]
>  It's the exact same model, just with ONNX weights and a tokenizer.json file so it works.

Hi Xenova, I'm currently tying [Kokoro-82M](https://huggingface.co/hexgrad/Kokoro-82M) and seems to have the same `tokenizer.json` problem. Would be possible to paste some resources about how can generate an transformers.js tokenizer compatible file?
