### ISSUE TITLE
Can models from user disks load and run in my HF space?

### ISSUE THREAD

**Issue by saferugdev** [xenova/transformers.js#564]
### Question

Im fiddling around with the react-translator template.
What I have accomplished so far:
- Run local (on disk in public folder) model in localhost webapp.
- Run hosted (on HF) model in localhost webapp.
- Run hosted (on HF) model in HF Space webapp.

What i want to accomplish but can't figure out:
- Use local (on disk in any folder) model in HF Space webapp.

Is this possible? 

From what i understand so far, local models have to be in the public folder of the webapp, but that defeats the purpose of my webapp, which would be to allow users to benchmark models from any folder of their disk in my HF Space. 

Preferably the user would provide a path or use drag'n'drop to provide their model folder location on the disk and the webapp would then proceed to load the model from the provided location into the application cache. 

The reason i need this specific setup is because i work on a benchmarking tool and I don't want to force users to host their models on HF in order to be able to benchmark them.

**Comment by saferugdev** [comment]
UPDATE: 
I spent an evening building a react input form which allows users to drag n drop their models folder and then proceeds to load the folder into application storage. I even got transformers.js to accept the uploaded cache data as valid and use it to do NLP stuff. But now theres another problem. This wont work on HF spaces because of their content policy. Obviously they dont want Spaces to mess with peoples cache data. I have now given up on this issue for now and will put local model files on the "add later" list.  Maybe you guys will implement a clean solution sooner or later but i think the use case of loading models from user disk into HF Space is just to specific to be relevant for now.

**Comment by CodyBontecou** [comment]
Hey @saferugdev any chance you can share how you accepted the local model into your local web app example?
