### ISSUE TITLE
text to sql

### ISSUE THREAD

**Issue by vinayakathavale** [xenova/transformers.js#566]
### Model description

Based on [t5-small](https://huggingface.co/t5-small), this model generates SQL from text given table list with "CREATE TABLE" statements. Supports multiple tables with joins. This is a very light weight model and could be used in multiple analytical applications.

 
Model link:
https://huggingface.co/cssupport/t5-small-awesome-text-to-sql

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [ ] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Additional information

Model already supported by transformers [here](https://huggingface.co/cssupport/t5-small-awesome-text-to-sql)

### Your contribution

Happy to make a PR for this

**Comment by xenova** [comment]
Cool! Luckily, since transformers.js already supports t5 models, you can use it after converting to ONNX (using Optimum, or our [conversion script](https://huggingface.co/docs/transformers.js/custom_usage#convert-your-models-to-onnx)).

**Comment by vinayakathavale** [comment]
Thanks!
