### ISSUE TITLE
jina-embeddings-v2-base-code

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#568]
### Model description

Brand new model for English code embeddings: https://huggingface.co/jinaai/jina-embeddings-v2-base-code

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [X] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Additional information

I don't know whether quantization might require some additional tweaks as [last time with the base version](https://huggingface.co/jinaai/jina-embeddings-v2-base-en/discussions/10).

### Your contribution

I could convert it with the standard script too but as mentioned in the base version discussion there might be some additional parameters to tweak.

**Comment by xenova** [comment]
Good news! The model is now compatible with transformers.js
![image](https://github.com/xenova/transformers.js/assets/26504141/39a05a17-e73d-47e6-84bc-88fc287d1015)

Example usage:
```js
// npm i @xenova/transformers
import { pipeline, cos_sim } from '@xenova/transformers';

const extractor = await pipeline('feature-extraction', 'jinaai/jina-embeddings-v2-base-code', {
    quantized: false, // Comment out this line to use the 8-bit quantized version
});

const texts = [
    'How do I access the index while iterating over a sequence with a for loop?',
    '# Use the built-in enumerator\nfor idx, x in enumerate(xs):\n    print(idx, x)',
]
const embeddings = await extractor(texts, { pooling: 'mean' });

const score = cos_sim(embeddings[0].data, embeddings[1].data);
console.log(score);
// 0.7281748759529421
```
