### ISSUE TITLE
Can we please add support for SAM HQ?

### ISSUE THREAD

**Issue by moneyhotspring** [xenova/transformers.js#578]
### Feature request

We have new version SAM HQ that is better than original SAM.
https://github.com/SysCV/sam-hq

### Motivation

It will generate better results.

### Your contribution

....

**Comment by xenova** [comment]
To be able to use it in transformers.js, the models must first be compatible with the python [transformers](https://github.com/huggingface/transformers) library. I would recommend that you make a feature request either in transformers, or the sam-hq repo to add compatibility with the transformers implementation.

**Comment by moneyhotspring** [comment]
Sure, Thanks!
