### ISSUE TITLE
undefined token from pretrained bert-base-uncased tokenizer

### ISSUE THREAD

**Issue by paoloach** [xenova/transformers.js#583]
### System Info

Browser => Chrome version 21.0.6167.139 
@xenova/transformers =>  2.15.0
react version => 18.2.0
vite version =>  5.1.1
python transformer version => 4.35.2

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I loaded the tokenizer as
`tokenizer = await AutoTokenizer.from_pretrained('bert-base-uncased');`
then use as
`const tokens = tokenizer(text,{return_tensor:false})`

where text is for example:
`const text = yeading face newcastle in fa cup premiership side newcastle united`

the result input_ids field is an array with these values
   ` 101, undefined, 2227, 8142, 1999, 6904, 2452, 11264, 2217, 8142, 2142, 102`

I have to use return_tensor:false to have a result. If return_tensor:true the tokenizer throw an exception because it try to convert the undefined value to a bigint.

The same text, tokenized in pyhton using this code:
```
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
a = tokenizer(text)
a
```
return these tokens:
`{'input_ids': [101, 6300, 23782, 2227, 8142, 1999, 6904, 2452, 11264, 2217, 8142, 2142, 102]...`

### Reproduction

javascript code to repreduce the issue.

```
import {AutoTokenizer } from '@xenova/transformers';
import { env } from '@xenova/transformers';
env.useBrowserCache=false
env.allowLocalModels=false
env.allowRemoteModels=true
const tokenizer = await AutoTokenizer.from_pretrained('bert-base-uncased');
const text = 'yeading face newcastle in fa cup premiership side newcastle united'
const tokens = tokenizer(text,{return_tensor:false})
console.log("tokens: ", tokens)
```

**Comment by xenova** [comment]
Duplicate of https://github.com/xenova/transformers.js/issues/532.

Please use `Xenova/bert-base-uncased` instead of `bert-base-uncased`.

**Comment by paoloach** [comment]
It works 
thanks you very  much

**Comment by xenova** [comment]
For posterity, this now works correctly in Transformers.js v3 (https://github.com/huggingface/transformers.js/pull/1151). Example code:
```js
import { AutoTokenizer } from '@huggingface/transformers'

const tokenizer = await AutoTokenizer.from_pretrained('bert-base-uncased')
const text = 'yeading face newcastle in fa cup premiership side newcastle united'
const tokens = tokenizer.encode(text)
console.log(tokens)
// [101, 6300, 23782, 2227, 8142, 1999, 6904, 2452, 11264, 2217, 8142, 2142, 102]
```

which matches the python library.
