### ISSUE TITLE
Default summarizer doesn't work

### ISSUE THREAD

**Issue by Madd0g** [xenova/transformers.js#6]
Just wanted to mention that I tried `pipeline('summarization')` without a second parameter and it didn't work (default is `sshleifer/distilbart-cnn-12-6`)

it did work when I provided the model that is specified in the test - `sshleifer/distilbart-cnn-6-6`.

I saw that 12-6 is an existing model on huggingface, is there a process that makes a model compatible? I'm sorry if these newbie questions are answered somewhere? I saw the section on how to convert a model to onnx... was it done for all the models manually?

Another questions is how to integrate a model that works slightly differently - for example [this model](https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-dot-v1) that is oriented for Q&A?

Thanks

**Comment by xenova** [comment]
> Just wanted to mention that I tried `pipeline('summarization')` without a second parameter and it didn't work (default is `sshleifer/distilbart-cnn-12-6`)
> 
> it did work when I provided the model that is specified in the test - `sshleifer/distilbart-cnn-6-6`.

Oh yes, looks like I didn't upload the `sshleifer/distilbart-cnn-12-6` model. Thanks for reporting! I will upload that model, and update the default to be `sshleifer/distilbart-cnn-6-6`.

> I saw that 12-6 is an existing model on huggingface, is there a process that makes a model compatible? I'm sorry if these newbie questions are answered somewhere? I saw the section on how to convert a model to onnx... was it done for all the models manually?

Yes, models need to be converted to ONNX for it to work in JS. This can easily be done using the conversion script (./scripts/convert.py). For example, this is the command I will use to create the distilbart-cnn-12-6 model:
```bash
python ./scripts/convert.py --model_id sshleifer/distilbart-cnn-12-6 --from_hub --quantize --task seq2seq-lm-with-past
``` 

As the project progresses, I am accumulating a large repository of these converted models for easy access: https://huggingface.co/Xenova/transformers.js/tree/main/quantized


> Another questions is how to integrate a model that works slightly differently - for example [this model](https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-dot-v1) that is oriented for Q&A?
> 
> Thanks

As stated in the README, the current supported models are [BERT](https://huggingface.co/docs/transformers/model_doc/bert), [DistilBERT](https://huggingface.co/docs/transformers/model_doc/distilbert), [T5](https://huggingface.co/docs/transformers/model_doc/t5), [T5v1.1](https://huggingface.co/docs/transformers/model_doc/t5v1.1), [FLAN-T5](https://huggingface.co/docs/transformers/model_doc/flan-t5), [GPT2](https://huggingface.co/docs/transformers/model_doc/gpt2), and [BART](https://huggingface.co/docs/transformers/model_doc/bart). The model you linked has type [MPNet](https://huggingface.co/docs/transformers/model_doc/mpnet), which currently isn't supported. But of course, the goal of the project is to support [all models](https://huggingface.co/docs/transformers/index#supported-models) that HuggingFace supports. So, I will add MPNet to my TODO list :)

**Comment by Madd0g** [comment]
great, it's good to see the list of all supported models, thanks!

**Comment by xenova** [comment]
> great, it's good to see the list of all the files for the supported models, thanks!

Writing better documentation is also on the TODO list! 😆 Currently focused on getting more models and tasks supported.

**Comment by xenova** [comment]
Closing for now, but feel free to reopen or create a new issue if you find anything else or just want to ask a question 👍
