### ISSUE TITLE
The large md file cannot be opened, the program crashes after clicking

### ISSUE THREAD

**Issue by zhaoxiaozhao07** [xenova/transformers.js#604]
### System Info

My system is win11, using qwen1.5-7b.gguf,bge-large-zh-v1.5

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [X] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Put large md file cannot be opened, click on the md file program immediately crashes

### Reproduction

1.Open large md file program crashes

**Comment by xenova** [comment]
Hi there. 👋  I think this issue is meant for another repo (since we do not support running .gguf models). If it is for transformers.js, please provide more information and you can reopen the issue.
