### ISSUE TITLE
next-server example does not work on WSL2

### ISSUE THREAD

**Issue by davies-w** [xenova/transformers.js#615]
### System Info

WSL2

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

~/transformers.js/examples/next-server$ ls 
Dockerfile  README.md  jsconfig.json  next.config.js  package-lock.json  package.json  postcss.config.js  public  src  tailwind.config.js
~/transformers.js/examples/next-server$ npm run dev

> next@0.1.0 dev
> next dev

'\\wsl.localhost\Ubuntu\~\transformers.js\examples\next-server'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'next' is not recognized as an internal or external command,
operable program or batch file.

### Reproduction

clone the repo.

Follow step 1 of the README....

**Comment by xenova** [comment]
> 'next' is not recognized as an internal or external command,
operable program or batch file.

This sounds like you forgot to run `npm install`.

**Comment by davies-w** [comment]
Thanks so much!

Ok, that opened a whole new can of worms (npm package manager hanging). But that's not a transformers.js issue.

**Comment by davies-w** [comment]
ok, if anyone else ends up here. I fixed the issues with npm by

doing:

sudo npm install -g n
sudo n lts
sudo n latest
sudo n prune
sudo npm install
npm run dev

I can't swear this will help you, but it did seem to fix all the problems I was getting, including "hanging" on NPM.

**Comment by davies-w** [comment]
Ok, next problem :-D 

I replaced the test example model with my private model, and set the HF_TOKEN in pipeline.js

import { pipeline } from "@xenova/transformers";

process.env.HF_TOKEN = 'hf_yyyyyyyyyyy'


Error: Unauthorized access to file: "https://huggingface.co/xxxxxx/question-in-text/resolve/main/tokenizer.json" (it's there, it works fine on beam.cloud for example).

**Comment by davies-w** [comment]
Ok, on the off chance this needed me to save my model as an ONNX model, I followed the instructions here (https://huggingface.co/blog/convert-transformers-to-onnx) and saved it to wdavies/public-onnx-test and it still failing. Seems to be looking for a quantized version of ONNX. 

 ⨯ Error: Could not locate file: "https://huggingface.co/wdavies/public-onnx-test/resolve/main/onnx/model_quantized.onnx".
    at handleError (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/utils/hub.js:221:11)
    at getModelFile (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/utils/hub.js:387:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async constructSession (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/models.js:208:18)
    at async Promise.all (index 1)
    at async DistilBertForSequenceClassification.from_pretrained (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/models.js:668:20)
    at async AutoModelForSequenceClassification.from_pretrained (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/models.js:2406:20)
    at async Promise.all (index 1)
    at async pipeline (webpack-internal:///(rsc)/./node_modules/@xenova/transformers/src/pipelines.js:1480:17)

**Comment by davies-w** [comment]
Ok, so this is borderline useless to me - according to this blog section, https://huggingface.co/blog/optimum-inference#34-use-the-ortquantizer-to-apply-dynamic-quantization , you have to "predecide" what CPU architecture you're going to run on????
