### ISSUE TITLE
How do I convert a DistilBERT Model to Quantized ONNX -

### ISSUE THREAD

**Issue by davies-w** [xenova/transformers.js#618]
### Question

Note, https://huggingface.co/docs/transformers.js/en/index#convert-your-models-to-onnx is a broken link.

I have a simple DistilBERT model I'm trying to load with the examples/next-server (wdavies/public-question-in-text)

I tried the simplest version of converting to ONNX  (wdavies/public-onnx-test following https://huggingface.co/docs/transformers/en/serialization#exporting-a--transformers-model-to-onnx-with-optimumonnxruntime), but I'm still getting an error message saying its looking for quantized_onnx. 

According to all I can see, including this blog post, you seem to have choose a specific hardware architecture? Is this true? How will I know what the client browser (or even mine) is running on? Help? I just want to run this simple model in example/next-server ?

https://huggingface.co/blog/optimum-inference#34-use-the-ortquantizer-to-apply-dynamic-quantization

**Comment by xenova** [comment]
Hi there 👋 The correct link is https://huggingface.co/docs/transformers.js/en/custom_usage#convert-your-models-to-onnx

Can you let us know where you encountered that broken link? We'll fix it!

**Comment by davies-w** [comment]
So does the architecture not matter then? I'll dig into that script and see what the settings are.

**Comment by davies-w** [comment]
Looks like this link map isn't being executed properly?

https://github.com/xenova/transformers.js/blob/b5a548fc650c6d3ab7ab0b8f9da7036a6d5a70dd/docs/scripts/build_readme.py#L79
