### ISSUE TITLE
model conversion script fails

### ISSUE THREAD

**Issue by davies-w** [xenova/transformers.js#619]
### System Info

WSL2, latest transformers.js, pip installed latest modules:

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

(base) wdavies:~/transformers.js$ python -m scripts.convert --quantize --model_id "wdavies/public-question-in-text"
config.json: 100%|███████████████████████████████████████████████████████████████████████████████| 728/728 [00:00<00:00, 3.46MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████| 1.20k/1.20k [00:00<00:00, 10.5MB/s]
vocab.txt: 100%|███████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 1.92MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████| 711k/711k [00:00<00:00, 3.94MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████| 125/125 [00:00<00:00, 1.19MB/s]
Framework not specified. Using pt to export the model.
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████| 268M/268M [00:02<00:00, 108MB/s]
Automatic task detection to text-classification (possible synonyms are: sequence-classification, zero-shot-classification).
Using the export variant default. Available variants are:
    - default: The default ONNX variant.
Using framework PyTorch: 2.2.1+cu121
/home/wdavies/anaconda3/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py:246: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask, torch.tensor(torch.finfo(scores.dtype).min)
Post-processing the exported models...
Weight deduplication check in the ONNX export requires accelerate. Please install accelerate to run it.
Validating ONNX model models/wdavies/public-question-in-text/model.onnx...
        -[✓] ONNX model output names match reference model (logits)
        - Validating ONNX Model output "logits":
                -[✓] (2, 2) matches (2, 2)
                -[✓] all values close (atol: 0.0001)
The ONNX export succeeded and the exported model was saved at: models/wdavies/public-question-in-text
Quantizing:   0%|                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wdavies/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wdavies/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wdavies/transformers.js/scripts/convert.py", line 523, in <module>
    main()
  File "/home/wdavies/transformers.js/scripts/convert.py", line 499, in main
    quantize([
  File "/home/wdavies/transformers.js/scripts/convert.py", line 272, in quantize
    quantize_dynamic(
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'

### Reproduction

Nothing but following the instructions:

python -m scripts.convert --quantize --model_id "wdavies/public-question-in-text"

**Comment by xenova** [comment]
This is due to an incompatible version of `onnx`. If you use the version specified in scripts/requirements.txt, it should work correctly.

**Comment by davies-w** [comment]
ah ok, I just installed directly from github, and then started using it (after installing the failed imports manually!)

**Comment by davies-w** [comment]
![image](https://github.com/xenova/transformers.js/assets/6550854/5a4c9f03-b14b-4f5f-aee3-55c5b1b69794)

woot!! Thank you so much for all your patient hand-holding!!

**Comment by davies-w** [comment]
I sent a pull request for a change to the documentation (I just added a pip install scripts/requirements.txt)
