### ISSUE TITLE
Contribution Question-What's next after run scripts.convert?

### ISSUE THREAD

**Issue by pacozaa** [xenova/transformers.js#644]
### Question

Hi @xenova I am trying to figure out how to contribute. I am new to huggingface. Just 2 months down the rabbit hole.

I ran
`python -m scripts.convert --quantize --model_id SeaLLMs/SeaLLM-7B-v2` 
command 

Here is a list of file I got in `models/SeaLLMs/SeaLLM-7B-v2` folder

```
_model_layers.0_self_attn_rotary_emb_Constant_5_attr__value
_model_layers.0_self_attn_rotary_emb_Constant_attr__value
config.json
generation_config.json
model.onnx
model.onnx_data
special_tokens_map.json
tokenizer.json
tokenizer.model
tokenizer_config.json
```
Does it work? 

What's next from here? Do I upload the models to huggingface?

Do you have example commits or PR I should take a look? I have been scanning the model PR but none of which mentioned what happen after you ran `scripts/convert`

I have seen some other issues mentioned the need for document. I know you don't have it yet. That's fine. That's why I am only asking for a hint or a little guidiance.

**Comment by xenova** [comment]
Hi there 👋 Apologies for the delayed response! Unfortunately, the model you are attempting to run is too large (7B params) to currently be used with Transformers.js, but this will be fixed in [v3](https://github.com/xenova/transformers.js/pull/545).
