### ISSUE TITLE
`aggregation_strategy` in TokenClassificationPipeline

### ISSUE THREAD

**Issue by boat-p** [xenova/transformers.js#648]
### Question

Hello, from Transformers original version they have aggregation_strategy parameter to group the token corresponding to the same entity together in the predictions or not. But in transformers.js version I haven't found this parameter. Is it possible to provide this parameter? I want the prediction result as same as the original version.

**Comment by xenova** [comment]
Duplicate of https://github.com/xenova/transformers.js/issues/648. Will answer there :)
