### ISSUE TITLE
Depth anything in Python

### ISSUE THREAD

**Issue by VladimirYugay** [xenova/transformers.js#653]
### Question

Amazing demo for the depth-anything! 

I want to have a similar point cloud, but in Python, and wondering what's the logic behind your js [implementation](https://github.com/xenova/transformers.js/blob/main/examples/depth-anything-client/main.js).

Specifically:
1. How do you set up the intrinsic matrix and backproject the depth map and color to the 3D space?
2. What is the difference between `Xenova/depth-anything-small-hf` and `LiheYoung/depth-anything-small-hf`?

**Comment by xenova** [comment]
1. Fortunately [three.js](https://threejs.org/) handles all the complicated 3D scene management for me. All the logic can be found in the `setupScene` function [here](https://github.com/xenova/transformers.js/blob/8c731fa54befb2b2a9527b88644551902ede2ff1/examples/depth-anything-client/main.js#L79-L150). If you want to achieve something similar, you can use the gradio [3D model component](https://www.gradio.app/guides/how-to-use-3D-model-component). You will need to convert the depth image to a glb trimesh (see example code [here](https://huggingface.co/spaces/whitphx/gradio-lite-transformers-js-depth-estimation/blob/29e6cefe88d22619c2d64fdaed30ba6c46cab240/index.html#L35-L69)).
2. As stated in the README of Xenova/depth-anything-small-hf, it is the same as LiheYoung/depth-anything-small-hf, but with ONNX weights to be compatible with transformers.js (so it can run in the browser).
