### ISSUE TITLE
Optical Character Recognition

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#672]
### Feature request

I was thinking it would be awesome if you could scan text or documents with your phone's camera.

This is not at all important, since there seem to be solutions to doing in the browser already:
- Tensorflow.js has [a demo](https://blog.tensorflow.org/2022/06/ocr-in-browser-using-tensorflowjs.html)
- [Tesseract.js](https://github.com/naptha/tesseract.js) seems to be popular too. 
### Motivation

Allowing a device to 'read' the world could be a valuable building block. It could simplify creating interesting pipelines when combined with the existing Transformers.js features. E.g.
- Detect signs and other objects in public space, OCR them, translate them, and speak them out loud, or show the translation on top of the image. This could be useful during travel, or for people who aren't great at reading.
- Aid in scanning in documents, which can them be analyzed with the endless other text manipulation features. Create summaries of texts, scan for safe/good options in restaurant menus, save businesscards, read licenseplates, create games, etc.

### Your contribution

I can help research models, aid in testing and design/build a demo.

**Comment by flatsiedatsie** [comment]
Seems it's already supported through:

https://huggingface.co/Xenova/donut-base-finetuned-docvqa

More details:
https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa

**Comment by kungfooman** [comment]
Did you experiment more with it @flatsiedatsie ?

I had a go for convert math equations back to LaTeX and it fails miserably:

```html
<body>
<script type="module">
import { pipeline } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.2.4";
// Create a document question answering pipeline
const qa_pipeline = await pipeline('document-question-answering', 'Xenova/donut-base-finetuned-docvqa');
// Generate an answer for a given image and question
//const image = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/invoice.png';
const image = "http://127.0.0.1/WebREDUCE/cam/test-ocr-2.png";
const question = 'Convert the equation to LaTeX!';
const start = Date.now();
const output = await qa_pipeline(image, question);
const end = Date.now();
const delta = (end - start) / 1000;
console.log(`Time taken: ${delta}ms`);
// [{ answer: 'us-001' }]
console.log("output", output);
Object.assign(window, {pipeline, qa_pipeline, image, question, output});
</script>
</body>

```

On this image:

![Image](https://github.com/user-attachments/assets/873bfec1-8a0c-47ef-a486-83d18d36783b)

Output:

![Image](https://github.com/user-attachments/assets/fa257d9a-314c-483c-b7ed-676de8d91cfc)

Not only did it take more than 90 seconds for that small image, but the result is just as useless as it gets.

But maybe I'm just using it wrong. Did you experiment more with it?
