### ISSUE TITLE
Is dit-base supported

### ISSUE THREAD

**Issue by Maxzurek** [xenova/transformers.js#673]
### Question

There is a [Huggingface repo](https://huggingface.co/Xenova/dit-base) for the ONNX version of the dit-base model but I can't seem to make it work.
I keep getting the following error:
![image](https://github.com/xenova/transformers.js/assets/74398804/4b0ab09e-640e-47ee-ae05-27f759830424)

Is the model currently supported?

**Comment by xenova** [comment]
Could you please provide the code you are using? I'm guessing you're using the `feature-extraction` pipeline instead of the `image-feature-extraction` pipeline?

**Comment by Maxzurek** [comment]
I was indeed using the feature-extraction pipeline. I still get an error after updating my code:
```js
const pipe = await pipeline("image-feature-extraction", "xenova/dit-base");
const rawImage = await RawImage.fromBlob(blob);
const output = await pipe(rawImage);
console.log(output);
```

Error:
![image](https://github.com/xenova/transformers.js/assets/74398804/1a7d5dbe-1836-4c8e-bcd9-6ed04b5a1abc)

**Comment by xenova** [comment]
See here for how to fix that: https://github.com/xenova/transformers.js/issues/670#issuecomment-2027474209

That setting will not be required in the next major version of transformers.js

**Comment by Maxzurek** [comment]
Great, it is working now! Thank you so much!
