### ISSUE TITLE
How to use fp16 version of the model file?

### ISSUE THREAD

**Issue by cyio** [xenova/transformers.js#676]
### Question

example files: https://huggingface.co/Xenova/modnet/tree/main/onnx

**Comment by xenova** [comment]
This requires the experimental v3 branch: https://github.com/xenova/transformers.js/pull/545
where you can specify:
```js
import { pipeline } from '@xenova/transformers';

// Create feature extraction pipeline
const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2', {
    // device: 'webgpu', (Optional)
    dtype: 'fp32', // or 'fp16'
});
```

**Comment by cyio** [comment]
step: 
1. `npm install xenova/transformers.js#v3`
2. for vite project, resolve `Top await error`  with https://github.com/remix-run/remix/issues/7969#issuecomment-1916042039
