### ISSUE TITLE
[Bug] Helsinki Multilingual models errors when using required >>id<< tokens

### ISSUE THREAD

**Issue by takoyaro** [xenova/transformers.js#70]
**Describe the bug**
*A clear and concise description of what the bug is.*

Helsinki multilingual models (`Helsinki-NLP/opus-mt-en-mul` and `Helsinki-NLP/opus-mt-mul-en`) require a specific token in the shape of `>>id<<` as per the [models documentation](https://huggingface.co/Helsinki-NLP/opus-mt-en-mul). However when using those tokens will cause the `models.js` file to throw an error:

`models.js:73 An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.".`

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

```js
const pipe = await pipeline('translation','Helsinki-NLP/opus-mt-en-mul')
const result = await pipe(">>jpn<< I love transformer.js, it's a wonderful library");
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

I expect to get the translated text

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*
<img width="1513" alt="Screenshot 2023-04-06 at 11 27 58" src="https://user-images.githubusercontent.com/54836677/230257010-a4eabf26-e5e1-4001-82e2-bec485f9da24.png">

**Environment**
- Transformers.js version: 1.4.0
- Browser (if applicable): Arc 0.96.0
- Operating system (if applicable): macOS Ventura 13.2
- Other:

**Additional context**
*Add any other context about the problem here.*

It should be noted that the models do not error without the `>>id<<` token and run just fine without them (although the translation is obviously wrong because the source/target language wasn't specified)

**Comment by xenova** [comment]
You're right! I didn't account for that, my bad! Let me work on that.

**Comment by ldenoue** [comment]
Could this be related to https://github.com/xenova/transformers.js/issues/66 ?

**Comment by xenova** [comment]
> Could this be related to #66 ?

Although the error message is the same, I think that's just a general error that onnxruntime throws when something goes wrong :/ That's the reason I added the extra logging statements so that we can perhaps see what the actual issue is.

One thing that might be causing it is an out-of-memory issue which can happen if too many beams are being run (which happens since the default config, which comes from the python library, has num_beams set to something > 1). I'll have to look into it a bit more though.

**Comment by xenova** [comment]
https://github.com/xenova/transformers.js/commit/12163dd28bd859d9d610fe7859883999308f0a71 should fix this 👍  Let me know if it works!

I will close the issue once I publish a full release.

**Comment by takoyaro** [comment]
> You're right! I didn't account for that, my bad! Let me work on that.
> 
> Here's the part of the code I missed: https://github.com/huggingface/transformers/blob/12d51db243a00726a548a43cc333390ebae731e3/src/transformers/models/marian/tokenization_marian.py#L204-L213

Good catch! 

https://github.com/xenova/transformers.js/commit/12163dd28bd859d9d610fe7859883999308f0a71 indeed fixes the issue, thank you!

**Comment by xenova** [comment]
Awesome! Closing now 😄
