### ISSUE TITLE
How to unload/destroy a pipeline?

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#715]
### Question

I tried to find how to unload a pipeline to free up memory in the documentation, but couldn't find a mention of how to do that properly.

If there a proper way to "unload" a pipeline?

I'd be happy to add the answer to the documentation.

**Comment by xenova** [comment]
Hi there 👋 You can use `pipeline.dispose()`, which returns a promise that resolves when the pipeline has been disposed (see [here](https://huggingface.co/docs/transformers.js/api/pipelines#pipelinesdisposable--code-promise--void--code)). However, I definitely agree this should be documented and handled better... Let me know if you have any ideas!

**Comment by flatsiedatsie** [comment]
Is there a way to edit the documentation
