### ISSUE TITLE
Adding support for MobileViTV2 model

### ISSUE THREAD

**Issue by laszlokiss-szelena** [xenova/transformers.js#720]
### Model description

Hi,

I would love to use MobileViTV2 in my application. I am definitely not an expert, but it seems that its architecture is pretty similar to MobileViT, so adding it seems fairly straightforward to me.

Laszlo

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [ ] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Your contribution

I experimented with this model on my fork here: https://github.com/KLaci/transformers.js/commit/e1e02b1d5876c1ffe4cadb53a01d592efee623a3

I can submit a PR too if needed.

**Comment by xenova** [comment]
Hi there 👋 Looks like the ONNX export isn't as simple as I originally thought (see [here](https://github.com/huggingface/optimum/pull/1823)). Is this something you'd be able to look into? :)

**Comment by xenova** [comment]
Okay I might have got it working. Feel free to open a PR for your fork.

**Comment by xenova** [comment]
Example code:
```js
import { pipeline } from '@xenova/transformers';

const url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/tiger.jpg';
const classifier = await pipeline('image-classification', 'Xenova/mobilevitv2-1.0-imagenet1k-256', {
    quantized: false,
});
const output = await classifier(url);
// [{ label: 'tiger, Panthera tigris', score: 0.6491137742996216 }]
```
