### ISSUE TITLE
Unknown PostProcessor type: Sequence

### ISSUE THREAD

**Issue by zcbenz** [xenova/transformers.js#739]
### System Info

Using Node.js 20 with transformers.js 2.17.1.

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

It seems that following post preprocessor in `tokenizer.json` is not supported:

```json
  "post_processor": {
    "type": "Sequence",
    "processors": [
      {
        "type": "ByteLevel",
        "add_prefix_space": true,
        "trim_offsets": false,
        "use_regex": true
      },
      {
        "type": "TemplateProcessing",
        "single": [
          {
            "SpecialToken": {
              "id": "<|begin_of_text|>",
              "type_id": 0
            }
          },
          {
            "Sequence": {
              "id": "A",
              "type_id": 0
            }
          }
        ],
        "pair": [
          {
            "SpecialToken": {
              "id": "<|begin_of_text|>",
              "type_id": 0
            }
          },
          {
            "Sequence": {
              "id": "A",
              "type_id": 0
            }
          },
          {
            "SpecialToken": {
              "id": "<|begin_of_text|>",
              "type_id": 1
            }
          },
          {
            "Sequence": {
              "id": "B",
              "type_id": 1
            }
          }
        ],
        "special_tokens": {
          "<|begin_of_text|>": {
            "id": "<|begin_of_text|>",
            "ids": [
              128000
            ],
            "tokens": [
              "<|begin_of_text|>"
            ]
          }
        }
      }
    ]
  },
```

### Reproduction

```js
import {AutoTokenizer} from '@xenova/transformers'

AutoTokenizer.from_pretrained('yujiepan/llama-3-tiny-random')
```

Throws error:

```
                throw new Error(`Unknown PostProcessor type: ${config.type}`);
                      ^

Error: Unknown PostProcessor type: Sequence
    at PostProcessor.fromConfig (file:///private/tmp/tinyllama/node_modules/@xenova/transformers/src/tokenizers.js:1596:23)
    at new PreTrainedTokenizer (file:///private/tmp/tinyllama/node_modules/@xenova/transformers/src/tokenizers.js:2465:45)
    at AutoTokenizer.from_pretrained (file:///private/tmp/tinyllama/node_modules/@xenova/transformers/src/tokenizers.js:4424:16)
```

**Comment by xenova** [comment]
Hi there 👋 Thanks for the report!

Luckily, we already support the [ByteLevel](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L1726) and [TemplateProcessing](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L1674) post-processors, so the only thing needed is to implement the Sequence post-processor.

Similarly, we already support sequences of [normalizers](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L1118), [decoders](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L2098), and [pre-tokenizers](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L2293), and a similar pattern can be adapted for post-processors. Is this something you'd be interested in adding? If so, I'd be happy to review a PR.

**Comment by zcbenz** [comment]
Sorry I don't plan to work on this issue, I'm just reporting a random issue I met.

**Comment by xenova** [comment]
No worries! It's super simple, so I'll add it soon. Thanks again for reporting!

**Comment by domleboss97** [comment]
@xenova I am also encountering this issue. I was going to take a pass at it, but I don't understand the internals well enough to understand how to meaningfully accumulate the `token_type_ids` generated by post processors ([ref](https://github.com/xenova/transformers.js/blob/8bb8c5a33c39aaf33eca286c0c271ed60a94e0da/src/tokenizers.js#L1549)).

**Comment by xenova** [comment]
Here's the rust code for it: https://github.com/huggingface/tokenizers/blob/25aee8b88c8de3c5a52e2f9cb6281d6df00ad516/tokenizers/src/processors/sequence.rs and it should be easy to translate into JS.

**Comment by xenova** [comment]
I added support for it in #771. See [here](https://github.com/xenova/transformers.js/pull/771#issue-2311740039) for example usage.

**Comment by domleboss97** [comment]
@xenova 💯 thank you, that is awesome. What cadence are you doing releases on?

**Comment by xenova** [comment]
Will most likely do one tomorrow. Just finalizing a few other things. :)
