### ISSUE TITLE
[Question] WavLM support 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [xenova/transformers.js#75]
This is a really good project. I was wondering if WavLM is supported in the project, I wanted to run a voice conversation model in the browser, also if Hifi-gan for voice synthesis.

**Comment by xenova** [comment]
Hi! So, text-to-speech is on its way (https://github.com/xenova/transformers.js/issues/59)... we are just waiting for the python library to implement the pipeline first (https://github.com/huggingface/transformers/issues/22487)

As for WavLM, can you give some example models and usage? From what I can see, it's just used for feature extraction? I assume you'll use the output of it as input to Hifi-gan?

If possible, can you provide example python code for how you would do it with the python library? (https://github.com/huggingface/transformers/) I'll make sure the usage is similar here.

**Comment by Ashraf-Ali-aa** [comment]
@xenova This is the model https://github.com/interspeech2023blind/knn-vc I wanted to run via the browser, I wanted to use the WavLM for feature extraction so that I can extract the speech representation for either generating the speech or getting  Phoneme recognition using https://github.com/ASR-project/Multilingual-PR, my overall goal is to try to produce a model that can help users with the pronunciation of a foreign language
