### ISSUE TITLE
Support decision transformers

### ISSUE THREAD

**Issue by emilx-cell** [xenova/transformers.js#794]
### Model description

Hi,
I would love to see decision transformers added to the list of supported models:
https://huggingface.co/docs/transformers/model_doc/decision_transformer
Thank you,
EM.

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [ ] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Additional information

An example decision model:
https://huggingface.co/edbeeching/decision_transformer_atari

### Your contribution

I apologize, but this is beyond my coding skills.

**Comment by xenova** [comment]
Here we go: https://github.com/xenova/transformers.js/pull/795

I will add example Transformers.js code now too. I'll also look at the model you linked.
