### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by inisis** [xenova/transformers.js#797]
### Feature request

Thank you for your awesome project, can [onnxslim ](https://github.com/inisis/OnnxSlim)be in your pipeline, there are still some space for onnx optimization after [Optimum](https://github.com/huggingface/optimum) export.

### Motivation

I believe there are still some performance increase after onnxslim

### Your contribution

I can submit a pr with [onnxslim](https://github.com/inisis/OnnxSlim)

**Comment by xenova** [comment]
I would love that! 🔥 If you'd like, you can integrate it into the v3 conversion script: https://github.com/xenova/transformers.js/blob/v3/scripts/convert.py. There are many improvements to make there, and a huge refactor is certainly needed. Let me know if that's something you'd be interested in!

**Comment by inisis** [comment]
@xenova I started from following README,
```
python -m scripts.convert --quantize --model_id bert-base-uncased
```
and I find that after optimum export, we can use onnxslim to further optimize it, here are the slimmed result.
![image](https://github.com/xenova/transformers.js/assets/46103969/dc1278d3-71ad-4e19-93f1-891f04138307)

and the quanzation works fine, so I wonder if you have benchmark test on CI or how can I test the slimmed performance.

**Comment by inisis** [comment]
Hi @xenova 

I found your repo on huggingface and I have tested some models manually, 

like [esm2_t30_150M_UR50D](https://huggingface.co/Xenova/esm2_t30_150M_UR50D/blob/main/onnx/model_fp16.onnx)

![image](https://github.com/xenova/transformers.js/assets/46103969/f2f890c1-746a-4025-9bf1-8fd1ffffe27f)

and [Phi-3-mini-4k-instruct-onnx-web](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx-web/blob/main/onnx/model_q4f16.onnx_data)
![image](https://github.com/xenova/transformers.js/assets/46103969/2966a21e-b98a-4fb3-b1b5-fd9802a41ac1)

the results are promising.
