### ISSUE TITLE
Add support for Florence 2?

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#815]
### Feature request

It describes images

Test on HF:
https://www.reddit.com/r/LocalLLaMA/comments/1djwf4v/try_microsofts_florence2_yourself/
https://huggingface.co/spaces/SixOpen/Florence-2-large-ft

Benchmarks:
https://www.reddit.com/r/LocalLLaMA/comments/1djhqzz/microsoft_florence2_vision_benchmarks/

### Motivation

While there is already support for Moondream 2, this model is an order of magnitude much smaller, yet performs similarly.

> Wait is a 200M model beating a 80B?

> Looks like it.

https://www.reddit.com/r/LocalLLaMA/comments/1diz8en/microsoft_releases_florence2_vision_foundation/

This would greatly speed-up image description, making it easier to incorporate images in RAG queries.

### Your contribution

I could aid in implementing a demo, and would happily integrate it in my soon to be released project.

![sneak](https://github.com/xenova/transformers.js/assets/805405/a2a98f78-8f30-4346-94c7-15ed5d12d88c)

Models

https://huggingface.co/microsoft/Florence-2-base/
https://huggingface.co/microsoft/Florence-2-large/
https://huggingface.co/microsoft/Florence-2-base-ft/
https://huggingface.co/microsoft/Florence-2-large-ft/

**Comment by xenova** [comment]
Hey! 👋 This is something I'm working on! :)

**Comment by xenova** [comment]
ONNX weights ✅ https://huggingface.co/onnx-community/Florence-2-base-ft
Integrating into transformers.js now

**Comment by inisis** [comment]
> ONNX weights ✅ https://huggingface.co/onnx-community/Florence-2-base-ft
> 
> Integrating into transformers.js now

Can this be slimmed🫣

**Comment by xenova** [comment]
@inisis that's right! Already slimmed :)

**Comment by inisis** [comment]
@xenova so is onnxslim ready to be merged.  ^-^

**Comment by xenova** [comment]
@inisis Soon! 🚀 I'm still testing across the set of ~1000 Transformer.js models ([link](https://huggingface.co/models?library=transformers.js)) to find issues like https://github.com/inisis/OnnxSlim/issues/10, and it will be merged into the v3 branch soon!

**Comment by inisis** [comment]
@xenova btw, if all tests finished, can onnxslim be merged into optimum 🚀

**Comment by xenova** [comment]
@inisis I think that's a great idea! Feel free to open a feature request on that repo and I'll voice my support there 😎

**Comment by inisis** [comment]
@xenova I believe that you are a member of huggingface, can you have me 😎

**Comment by xenova** [comment]
@flatsiedatsie Got it working! :) Available in dev/v3 branch: https://github.com/xenova/transformers.js/pull/545#issuecomment-2183625876

**Comment by flatsiedatsie** [comment]
I've just tried implementing it.

I'm seeing an error, but will keep trying.

```
image_to_text_worker.js:715 IMAGE TO TEXT WORKER: caught error calling model.generate:  TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Function.getGeneratedNgrams (logits_process.js:370:1)
    at Function.calcBannedNgramTokens (logits_process.js:387:1)
    at Function._call (logits_process.js:401:1)
    at closure (generic.js:20:1)
    at Function._call (logits_process.js:89:1)
    at closure (generic.js:20:1)
    at Function.generate (models.js:1466:1)
```

*some time later

I tried to run your code example in a clean simple example, to rule out issues with my integration. But unfortunately the same error was raised:

<img width="537" alt="Screenshot 2024-06-22 at 17 09 31" src="https://github.com/xenova/transformers.js/assets/805405/c0eca782-c015-493b-a7d4-a06fc07ff6cd">

**Comment by xenova** [comment]
Ah whoops I've updated that in my local branch but forgot to push. I've pushed and you can try again now.

**Comment by flatsiedatsie** [comment]
Ah cool. I had also just fixed it :-D

```
const generatedNgram = new Map();
		let nn = 0;
        for (const ngram of ngrams) {
            const prevNgram = ngram.slice(0, ngram.length - 1);
            const prevNgramKey = nn++; //JSON.stringify(prevNgram);
            const prevNgramValue = generatedNgram.get(prevNgramKey) ?? [];
            prevNgramValue.push(ngram[ngram.length - 1]);
            generatedNgram.set(prevNgramKey, prevNgramValue);
        }
        return generatedNgram;
```

**Comment by flatsiedatsie** [comment]
Wow, it's definitely much faster. Very nice!

The descriptions aren't as useful though? But I'm going to keep playing around with that.

<img width="1171" alt="Screenshot 2024-06-22 at 18 20 37" src="https://github.com/xenova/transformers.js/assets/805405/cd7bdc07-e7ff-4653-9855-202cbcfa4d28">


Odd that this prompt results in less detail :-D
<img width="502" alt="Screenshot 2024-06-22 at 18 27 27" src="https://github.com/xenova/transformers.js/assets/805405/c6c7c5ac-db0a-4b7f-b1ca-b4d22623fd2a">

**Comment by xenova** [comment]
> Wow, it's definitely much faster. Very nice!

Great! 🥳 

> The descriptions aren't as useful though? But I'm going to keep playing around with that.

You might need to use one of their pre-selected prompts: https://huggingface.co/microsoft/Florence-2-base-ft/blob/e7a5acc73559546de6e12ec0319cd7cc1fa2437c/processing_florence2.py#L115-L117
- caption: `'What does the image describe?'`
- detailed: `'Describe in detail what is shown in the image.'`
- more detailed: `'Describe with a paragraph what is shown in the image.'`

I've also uploaded the larger (800M) models: https://huggingface.co/onnx-community/Florence-2-large-ft or https://huggingface.co/onnx-community/Florence-2-large, which you can try out.

**Comment by flatsiedatsie** [comment]
I'll try that, thank you!

Could it be that with the new V3 the MusicGen streamer progress callback no longer works properly? I haven't tested these separately from my code though, could just be an issue with my code.

<img width="388" alt="Screenshot 2024-06-22 at 21 00 40" src="https://github.com/xenova/transformers.js/assets/805405/d37f579d-cc14-4446-af43-a6168eb8f68b">

I'm also seeing an error with nanoLlava. It's just a number:
<img width="388" alt="Screenshot 2024-06-22 at 21 05 03" src="https://github.com/xenova/transformers.js/assets/805405/4e725614-a982-4b52-9648-7dd0c96e5ce5">

**Comment by flatsiedatsie** [comment]
I'm finding that the larger models are hit or miss.

good:
<img width="375" alt="Screenshot 2024-06-26 at 19 22 30" src="https://github.com/xenova/transformers.js/assets/805405/84323e36-11a5-4cc8-b125-48014ba16c80">

bad:
<img width="438" alt="Screenshot 2024-06-26 at 19 45 10" src="https://github.com/xenova/transformers.js/assets/805405/c98f8d90-6c62-4d96-bfee-d6c09904f2d3">

```
- caption: 'What does the image describe?'
- detailed: 'Describe in detail what is shown in the image.'
- more detailed: 'Describe with a paragraph what is shown in the image.'
```

Does this list of captions mean that the model isn't designed for free-form question asking?

it sure seems like it:

good:
<img width="442" alt="Screenshot 2024-06-26 at 19 55 29" src="https://github.com/xenova/transformers.js/assets/805405/dc646fee-1b40-4789-8a90-dbb9d6b9536d">

bad:
<img width="444" alt="Screenshot 2024-06-26 at 19 57 16" src="https://github.com/xenova/transformers.js/assets/805405/ba11876b-414b-4af2-a3d5-7a085fa09b8a">

**Comment by flatsiedatsie** [comment]
I think with the WebGPU support this issue can be closed. Awesome stuff, thank you so much for your amazing work as always.

**Comment by Vasanthengineer4949** [comment]
i need to export my own custom florence2 model. how can I do it?

**Comment by dragen1860** [comment]
> ONNX weights ✅ https://huggingface.co/onnx-community/Florence-2-base-ft Integrating into transformers.js now

hi, @xenova I encounter some difficulty to export onnx. Could you kindly share your method on how to export onnx for florence2? thank you.

**Comment by JohnRSim** [comment]
I'm running into the following error

worker-Bo2tVEHN.js:5 Uncaught (in promise) Error: no available backend found. ERR: [webgpu] TypeError: e.requestAdapterInfo is not a function
    at gs (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:5:1599)
    at async H0.create (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:5:17973)
    at async rm (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:2353:12683)
    at async Zr (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:2373:27270)
    at async Promise.all (index 0)
    at async Zm.from_pretrained (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:2373:34092)
    at async Promise.all (index 0)
    at async N3 (https://xenova-florence2-webgpu.static.hf.space/assets/worker-Bo2tVEHN.js:2373:114960)

**Comment by gyagp** [comment]
@JohnRSim There is a breaking change in WebGPU spec and Chrome impl, and GPUAdapter.requestAdapterInfo() is no longer supported. This was fixed in a recent onnxruntime-web, so we need to upgrade the example to use the latest @huggingface/transformers release, which includes the recent onnxruntime-web fix. 
I just uploaded a PR to fix this, and the related HF space needs to be updated accordingly.

**Comment by ir2718** [comment]
@xenova Any chances on releasing the ONNX conversion script? I'm looking to convert the weights of a tuned model, but haven't had any luck so far.
