### ISSUE TITLE
Blog on walkthrough with transformers js

### ISSUE THREAD

**Issue by ArijitCloud** [xenova/transformers.js#819]
### Question

Hey, So I am writing this blog part of sharing knowledge in a blog series called Running AI/ML in the client. I am using transformer js example walkthrough in this part to validate some concepts. Can I get some feedback before it goes live? How do we connect?

**Comment by xenova** [comment]
Hey! 👋 Feel free to post any questions you may have here :)

**Comment by ArijitCloud** [comment]
Hey, thanks for responding! I don't have any specific questions at the moment, but I was wondering if you could take a moment to look at it and share any thoughts you might have :)
