### ISSUE TITLE
Add support for Gemma 2 templating

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#828]
### Feature request

I'm currently using the Transformers.js engine to turn conversation history for various LLM's into the proper strings to feed them with.

### Motivation

Gemma 2 support has just been added to Llama.cpp. and thus to Wllama. I'm doing a quick experiment with adding it to my project, but noticed it's not supported yet.

### Your contribution

If you tell/teach me where I can add this to the codebase I could try to do so.

**Comment by xenova** [comment]
Hi there 👋 I've uploaded the tokenizer files to https://huggingface.co/Xenova/gemma-2-tokenizer, and it's already compatible with Transformers.js :) 

![image](https://github.com/xenova/transformers.js/assets/26504141/f523cca5-92d6-444b-8da4-2cb0b6dd6790)

You can just update the id in your code and it should work out-the-box!

**Comment by flatsiedatsie** [comment]
Thank you!
