### ISSUE TITLE
Helsinki models error if used in a worker

### ISSUE THREAD

**Issue by escottgoodwin** [xenova/transformers.js#83]
I get the following error if I call  a Helsinki NLP model with the pipeline in a web worker (as in demo example). It works if called in the main app on the main thread (not ideal). Other hugging face models work fine in the worker.

utils.js:423 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at softmax (utils.js:423:1)
    at Function.sample (samplers.js:227:1)
    at Function._call (samplers.js:31:1)
    at closure (utils.js:544:1)
    at Function.generate (models.js:742:1)
    at async Function._call (pipelines.js:373:1)

**Comment by escottgoodwin** [comment]
Actually, it seemed to only happen with es-en model. fr-en and de-en, en-fr, fr-en worked just fine. Perhaps the es-en got corrupted on my initial download.

**Comment by xenova** [comment]
https://github.com/xenova/transformers.js/commit/1b9fe0f27c78831a6526fec0233fa7483deb6fca should fix it. I will merge into main and make a full release in the next day or so.

**Comment by xenova** [comment]
> Actually, it seemed to only happen with es-en model. fr-en and de-en, en-fr, fr-en worked just fine. Perhaps the es-en got corrupted on my initial download.

Well, the es-en model has a vocabulary size of 64937, while the fr-en only has 59513 tokens. Perhaps the "limit" is somewhere in between haha. Either way, no worries - since the above changes should fix it.

**Comment by xenova** [comment]
Published a new version ([v1.4.3](https://www.npmjs.com/package/@xenova/transformers/v/1.4.3)) which fixes this. Closing the issue now :)
