### ISSUE TITLE
How to load version 3 from CDN? 

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [xenova/transformers.js#832]
### Question

The [README.md file on v3 branch](https://github.com/xenova/transformers.js/tree/v3?tab=readme-ov-file#installation) has a html snippet to import transformers version 3 from a CDN.

```html
<script type="module">
    import { pipeline } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@3.0.0-alpha.0';
</script>
```

That URL is unresolved by the CDN.

Is version 3 available on any CDN? If so what is the URL? If not is there an alternative to import from browser?

**Comment by xenova** [comment]
Hi there 👋 We're planning on releasing a version for this soon. 👍

**Comment by snat-s** [comment]
Is there a timeline or just vibes based? Love the project!

**Comment by biojazzard** [comment]
https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.0.0-alpha.20
