### ISSUE TITLE
How do I free up memory after transliteration

### ISSUE THREAD

**Issue by raodaqi** [xenova/transformers.js#836]
### Question

After I executed the translation in the worker, it seems that the memory could not be reclaimed when I called pipely. dispose(), and the memory would be reclaimed only when the woker was closed. Can you help me with this question?

**Comment by Th3G33k** [comment]
The memory can only grow, and cannot be reduce.
Using dispose(), it will tell that the memory is no longer used, and can be use for another pipeline.
To completely free the memory, you will need to close the worker, or reload the webpage.

You can check it in the browser devtools. Example :
Pipeline(task_1)
memory 1x
Dispose()
Memory 1x
Pipeline(task_2)
Memory 1x (the memory used for task_1, is now use for task_2)
