### ISSUE TITLE
Add Bitnet tokenizer

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#838]
### Feature request

Would it be possible to add support for the Bitnet tokenizer?

Perhaps this is useful:
https://huggingface.co/1bitLLM/bitnet_b1_58-3B/blob/main/tokenization_bitnet.py

### Motivation

I'm trying to get Bitnet to run in the browser :-)

### Your contribution

If it works, then I will use it in my project.

**Comment by xenova** [comment]
Luckily, it already works! :) You will get a warning saying the BitnetTokenizer isn't officially supported, but since the repo has a tokenizer.json and tokenizer_config.json, it will work correctly.

[Example JsFiddle](https://jsfiddle.net/sojbacy8/1/).

```js
import { AutoTokenizer } from '@xenova/transformers';
    
const tokenizer = await AutoTokenizer.from_pretrained('1bitLLM/bitnet_b1_58-3B');
const ids = tokenizer.encode('Hello world!')
console.log(ids);
// [1, 15043, 3186, 29991]
```

**Comment by flatsiedatsie** [comment]
Thank you!

I actually discovered what the issue was. It was that I had to add `<s>` before the prompt. Then it all magically started working.

Demo of Bitnet in the Browser: https://flatsiedatsie.github.io/bitnet_in_the_browser/
