### ISSUE TITLE
My extension was rejected from the Chrome Web Store for "including remotely hosted code in a Manifest V3 item"

### ISSUE THREAD

**Issue by Vectorrent** [xenova/transformers.js#839]
### System Info

Transformers.js: v2.17.2
Chromium: v126.0.6478.126

### Environment/Platform

- [ ] Website/web-app
- [X] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

![image](https://github.com/xenova/transformers.js/assets/94832312/471e667e-4ef1-4842-85a4-3a13acfdc0e4)

[A link to this policy.](https://developer.chrome.com/docs/webstore/troubleshooting/#additional-requirements-for-manifest-v3)

After working well for over a month, the latest version of [my Chrome extension](https://github.com/0-5788719150923125/ext) was just rejected by Google, for "including remotely hosted code in a Manifest V3 item." Yet, without `script-src 'self' 'wasm-unsafe-eval'` - Transformer.js does not work:
```
Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because neither 'wasm-eval' nor 'unsafe-eval' is an allowed source of script in the following Content Security Policy directive: "script-src 'self'"). Build with -sASSERTIONS for more info.
```
This really sucks. I spent a lot of time working on this extension, because it was accepted early - and I never expected to run into this kind of problem (i.e. a fundamental one, which may not have a clean or fast resolution). 

Is there any way to bundle all of the WASM code I would need along with my extension? Or, is this a fatal ONNX flaw - where models simply need the ability to "compile themselves", after download? Am I dead in the water?

Your advice would be greatly appreciated. I will continue searching for answers on my end.

### Reproduction

Instructions to build my extension can be found in the [README of my Github repo](https://github.com/0-5788719150923125/ext).

That said, you would have to submit a built extension to the Chrome Web Store, to reproduce this error precisely.

**Comment by Vectorrent** [comment]
I have tried copying all *.wasm files into my extension's build, and including them with:
```js
env.backends.onnx.wasm.wasmPaths = '/ort/'
```
I think this is working, but it doesn't prevent Webpack from continuing to include things like this:
```js
a={locateFile:(t,e)=>i&&t.endsWith(".worker.js")&&"undefined"!=typeof Blob?URL.createObjectURL(new Blob([n(154)],{type:"text/javascript"})):t===b?null!=g?g:(null!=y?y:e)+m:e+t};if(i)if("undefined"==typeof Blob)a.mainScriptUrlOrBlob=u.join("/","ort-wasm-threaded.js");else{const t=`var ortWasmThreaded=(function(){var _scriptDir;return ${r.toString()}})();
```
Since `ortWasmThreaded` is named here, I am guessing that there are specific calls within these WASM modules, which are dynamically-creating object URLs.

Nevertheless, I tried replacing my own URL-creation calls with `chrome.runtime.getURL() `, as suggested by Google. Sadly, this does not prevent Webpack from generating these `URL.createObjectURL` calls, regardless.

And so, I am stuck. While I may choose to submit the extension as-is, perhaps with a lengthy justification... maybe this is "good enough", for now? I will wait for a day or two, to see if I can get an response from @xenova, before submitting an extension again.

Thanks in advance for any help you can offer!

**Comment by Vectorrent** [comment]
So, decided to bundle all of the ORT WASM files with my extension directly, rather than allowing Transformers.js to fetch them from a CDN. This seemed to work, and Google has accepted the new version of my extension. Will close this issue for now.

**Comment by benjick** [comment]
Hey. I want to bundle my files too. Any pointers on how to do that?

**Comment by Vectorrent** [comment]
> Hey. I want to bundle my files too. Any pointers on how to do that?

[Feel free to copy from me](https://github.com/0-5788719150923125/ext), @benjick. I got most of this figured out a couple months ago 🙂

**Comment by benjick** [comment]
Thanks a lot! I'll check it out
