### ISSUE TITLE
V3 audio transcription: aud.subarray is not a function

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#845]
### System Info

Cutting edge version of V3 (just compiled)

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I attempted a drop-in replacement of the V3 version in a V2 webworker, just to see if it would even work.

And it does! Trying to enable WebGPU is the next step.

However, while it works, I do see an error:

<img width="419" alt="Screenshot 2024-07-10 at 18 18 35" src="https://github.com/xenova/transformers.js/assets/805405/f1008c1f-276e-4faa-abb6-98236627d601">

### Reproduction

I could share code if need be.

**Comment by flatsiedatsie** [comment]
I spotted a small typo in the demo:

`PipelineSingeton` is missing an L

**Comment by flatsiedatsie** [comment]
A small question: is there a downside to simply always using the timestamp version?

**Comment by flatsiedatsie** [comment]
And some more questions:

The V2 demo has a number of values that could be manipulated. Are they still useful?

- const isDistilWhisper = model.startsWith("distil-whisper/");
- quantized

and these:

```
	        /// Greedy
	        //top_k: 0,
	        //do_sample: false,

	        // Sliding window
	        //chunk_length_s: isDistilWhisper ? 20 : 30,
	        //stride_length_s: isDistilWhisper ? 3 : 5,

	        // Language and task
	        //language: language,
	        task: subtask,

	        // Return timestamps
	        //return_timestamps: true,
	        //force_full_sequences: false,
```

**Comment by flatsiedatsie** [comment]
I saw this error once: 
<img width="352" alt="Screenshot 2024-07-11 at 00 55 30" src="https://github.com/xenova/transformers.js/assets/805405/79b7906e-ffb5-45d2-9c0f-6f21fbbd778f">

**Comment by flatsiedatsie** [comment]
I'm having some trouble getting it to respond with more than 1 word when using WebGPU. It usually thinks it heard 'And'.

<img width="353" alt="Screenshot 2024-07-11 at 01 07 14" src="https://github.com/xenova/transformers.js/assets/805405/1ab1f6a1-b75d-4101-8a19-6d93461ce2b1">

**Comment by flatsiedatsie** [comment]
FP32 was the key

**Comment by xenova** [comment]
Thanks for the report! The function does require `Float32Array` or `Float64Array` inputs, but we could use `.slice()` if `.subarray` isn't present (for normal arrays)

**Comment by flatsiedatsie** [comment]
Nah, no worries. With what you're saying I believe the issue was that I was feeding it a fake array to get it to preload. That worked with the V2 version, but no longer worked with the V3 version. But that's fine as there are plenty of new ways to handle pre-loading.
