### ISSUE TITLE
[Model request] OwlV2

### ISSUE THREAD

**Issue by pachacamac** [xenova/transformers.js#877]
### Model description

Thought [this](https://huggingface.co/docs/transformers/main/model_doc/owlv2#usage-example) could be a cool add-on for the object-detection pipeline. Zero- and one-shot object detection with (as far as I understood) arbitrary (embedding based?) labels. Wdyt?

### Prerequisites

- [ ] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [X] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Your contribution

Happy to beta test

**Comment by xenova** [comment]
Hi there! Luckily, OwlV2 is already supported: https://huggingface.co/models?library=transformers.js&other=owlv2&sort=trending

Example usage:
```js
import { pipeline } from '@xenova/transformers';

const detector = await pipeline('zero-shot-object-detection', 'Xenova/owlv2-base-patch16-finetuned');

const url = 'http://images.cocodataset.org/val2017/000000039769.jpg';
const candidate_labels = ['a photo of a cat', 'a photo of a dog'];
const output = await detector(url, candidate_labels);
console.log(output);
// [
//   { score: 0.6951543688774109, label: 'a photo of a cat', box: { xmin: 326, ymin: 23, xmax: 650, ymax: 376 } },
//   { score: 0.5766839385032654, label: 'a photo of a cat', box: { xmin: 6, ymin: 63, xmax: 315, ymax: 487 } }
// ]
```
