### ISSUE TITLE
Expected iterable type in for loop: got UndefinedValue

### ISSUE THREAD

**Issue by zcbenz** [xenova/transformers.js#879]
### System Info

@xenova/transformers 2.17.2

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Calling `tokenizer.apply_chat_template` with Llama3.1's tokenizer throws exception.

### Reproduction

1. Download the tokenizer of https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct.
2. Run following code to create chat:
```js
import fs from 'node:fs'
import {PreTrainedTokenizer} from '@xenova/transformers'

const tokenizer = new PreTrainedTokenizer(
  JSON.parse(fs.readFileSync('./tokenizer.json')),
  JSON.parse(fs.readFileSync('./tokenizer_config.json')))
const chat = [
  { "role": "user", "content": "Hello, how are you?" },
  { "role": "assistant", "content": "I'm doing great. How can I help you today?" },
  { "role": "user", "content": "I'd like to show off how chat templating works!" },
]
const text = tokenizer.apply_chat_template(chat)
```
3. Error is thrown: `Error: Expected iterable type in for loop: got UndefinedValue`

**Comment by xenova** [comment]
Hi there 👋 I believe this is because the template assumes tools is set to `null` by default. While we update that, you should be able to get around it with:
```js
const text = tokenizer.apply_chat_template(chat, { tools: null })
```

**Comment by xenova** [comment]
Just letting you know this is now available in Transformers.js v3: `@huggingface/transformers`

```js
// npm i @huggingface/transformers
import { AutoTokenizer } from '@huggingface/transformers'

const tokenizer = await AutoTokenizer.from_pretrained('Xenova/Meta-Llama-3.1-Tokenizer');
const chat = [
  { "role": "user", "content": "Hello, how are you?" },
  { "role": "assistant", "content": "I'm doing great. How can I help you today?" },
  { "role": "user", "content": "I'd like to show off how chat templating works!" },
]
const text = tokenizer.apply_chat_template(chat)
console.log(text);
```

(https://huggingface.co/Xenova/Meta-Llama-3.1-Tokenizer is the same tokenizer as https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct)
