### ISSUE TITLE
[Bug] Not working on Firefox under Windows

### ISSUE THREAD

**Issue by do-me** [xenova/transformers.js#88]
Unfortunately the library can't be loaded on Firefox under Windows due to missing OffscreenCanvas support. Context [here](https://fosstodon.org/@wizzwizz4/110203268723485167)

Tested on the most recent Firefox version 112.0 (on Windows) with transformers.js [homepage](https://xenova.github.io/transformers.js/)

```
SecurityError: The operation is insecure.
```

Does anyone know a way to make it work anyway? Like [wizzwizz4](https://fosstodon.org/@wizzwizz4/110203268723485167) said it would be also ok to simply wait for a browser update.

On Ubuntu it works fine for me.

**Comment by xenova** [comment]
I've tested Firefox (v110.0) on Windows, and I didn't run into any issues - even for the image tasks (which is what OffsceenCanvas is needed for).

I just updated to v112.0, and ran the demo, and everything seems to work correctly?
![image](https://user-images.githubusercontent.com/26504141/232246227-2f3bc493-1c33-485b-9f45-5b242ade7f7d.png)

Are you using the latest version of Transformers.js (v1.4.2)?

**Comment by do-me** [comment]
Found the error! I forgot I had very strict privacy settings activated. I simply ticked off "always start in private mode" under history (Chronik in German) and now it works perfectly! Sorry for the trouble.  
 

![](https://user-images.githubusercontent.com/47481567/232247468-24cc616d-cd5f-4936-bd05-818f9c1e69b2.png)

**Comment by xenova** [comment]
Great! 🥳 Although, if there is a way to make it work with those settings, it would probably be good to do that :) If you are able to find a way to fix it, please feel free to share!
