### ISSUE TITLE
VSCode Interpolation

### ISSUE THREAD

**Issue by lukemovement** [xenova/transformers.js#887]
### Question

I'm finding that VSCode is extremely slow when reading type definitions from the `@xenova/transformers` path. Is there anything I might be doing wrong? I've noticed that it uses JS comments to define the types instead of a type definition file, is the issue I am having a known issue with using that type of markup?

**Comment by xenova** [comment]
Hi there 👋 Does the same thing happen for Transformers.js v3 (`@huggingface/transformers`)?

**Comment by lukemovement** [comment]
`@huggingface/transformers` Seems to be working fine. Is `@xenova/transformers` an old version?

**Comment by xenova** [comment]
Right, `@huggingface/transformers` is the updated version we are working on (Transformers.js V3), which is currently in development and will eventually replace `@xenova/transformers` (Transformers.js V2).

It is still not 100% stable, so we haven't merged it into main yet, but you can follow along at https://github.com/xenova/transformers.js/pull/545.
