### ISSUE TITLE
Model not cacheing after download (@huggingface/transformers)

### ISSUE THREAD

**Issue by tobowers** [xenova/transformers.js#889]
### System Info

`"@huggingface/transformers": "3.0.0-alpha.5"`

Macos

Bun 1.1.22 and node v22.2.0 (under tsx) show same behavior.

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Using the newest @huggingface/transformers package my models are no longer cacheing after download from hugging face. Even when specifying a cache dir and a localModelDir.

You can see a minimal example failing in both tsx (node) and bun (bun test) https://github.com/tobowers/minimal-failure-model-cacheing-transformers.

The model will download again at every run.

### Reproduction

https://github.com/tobowers/minimal-failure-model-cacheing-transformers

**Comment by tobowers** [comment]
I should note that v2 (via @xenova/transformers) works and the sroussey port of 3.0.0-alpha.2 also caches fine, but the @huggingface/transformers alpha.2 also fails to cache.

**Comment by flatsiedatsie** [comment]
Just to check: are you setting any environment variables? see: https://github.com/xenova/transformers.js/issues/685

**Comment by tobowers** [comment]
> Just to check: are you setting any environment variables? see: #685

in the example you can see I try setting localModelPath and cache path and neither of those seem to do anything, but if you have anything specific to try I can... there used to be a sensible default.

**Comment by xenova** [comment]
`@huggingface/transformers@3.0.0-alpha.6` should fix this ([here](https://www.npmjs.com/package/@huggingface/transformers/v/3.0.0-alpha.6))! :)
(I believe the issue was that `fs` wasn't being marked as "external" in the build, meaning we couldn't access the filesystem).

Feel free to re-open if this wasn't the case!
