### ISSUE TITLE
[Model Request] gte-multilingual-base

### ISSUE THREAD

**Issue by mldljyh** [xenova/transformers.js#891]
### Model description

[Alibaba-NLP/gte-multilingual-base](https://huggingface.co/Alibaba-NLP/gte-multilingual-base) 
This model is relatively small among multilingual text embedding models. It should be helpful for developers looking for compact multilingual embedding models.

### Prerequisites

- [ ] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [ ] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Your contribution

Happy to beta test

**Comment by xenova** [comment]
Done :) https://huggingface.co/onnx-community/gte-multilingual-base

Example code in model card 👍
