### ISSUE TITLE
[Feature request] AutoTokenizer

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#90]
**Name of the feature**
Loading just the tokenizer for a model, given a Hugging Face repo path/name/url.

**Reason for request**
I have a use case where, given a Hugging Face [text-generation](https://huggingface.co/models?pipeline_tag=text-generation) model URL, I need to be able to load the tokenizer only.

IIUC, what I'm looking for is a port of AutoTokenizer?

I'm not sure what the best approach here is, or whether this is something that you want to support with transformers.js, but just putting it out there because it might be helpful to hear about a use case.

**Additional context**
My specific use case is that I have [a web app](https://josephrocca.github.io/OpenCharacters) where people can swap out the OpenAI endpoing for their own OpenAI-compatible endpoint using an inference server like [hyperonym/basaran](https://github.com/hyperonym/basaran). They specify a huggingface model but I need to download the tokenizer because some tokenization operations (specifically for context limit calculations) are done on the client (eventually, thanks to transformers.js and friends, inference will be possible on the client too, but waiting for WebGPU & models that meet the quality threshold for this particular use case).

Potentially related/useful:
* https://github.com/pyodide/pyodide/pull/3422
* https://github.com/josephrocca/tokenizers-pyodide
* https://github.com/mithril-security/tokenizers-wasm

**Comment by xenova** [comment]
Hi! Sorry for the delayed response, but to answer your question... It's already supported :)

Here's example code:
```js

let url = 'https://huggingface.co/Xenova/transformers.js/resolve/main/quantized/gpt2/causal-lm-with-past/';
let tokenizer = await AutoTokenizer.from_pretrained(url);

let tokens = await tokenizer('I love Transformers.js!');
console.log(tokens);
```

Which will output:
![image](https://user-images.githubusercontent.com/26504141/232345815-8a115b17-af34-4681-9161-a8c674bd6e96.png)

---
Just be sure to use the url which contains `/resolve/main`. Another thing, is that the model should contain `tokenizer.json` and `tokenizer_config.json` (which should be exported when using `.save_pretrained()` from Python

**Comment by xenova** [comment]
The arguments for `tokenizer(...)` can be found here:

https://github.com/xenova/transformers.js/blob/83308707524deb8b97eeb1535850a99c43125379/src/tokenizers.js#L1523-L1547

---

Proper documentation is coming soon though! (see [here](https://github.com/xenova/transformers.js/tree/docs))

**Comment by josephrocca** [comment]
Ah that's great - thank you!!
