### ISSUE TITLE
[v3] `NoBadWordsLogitsProcessor` breaks when the size of `bad_word_ids` exceeds the size of the input ids

### ISSUE THREAD

**Issue by tarekziade** [xenova/transformers.js#910]
### System Info

v3

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

this block breaks for me with `mozilla/distilvit` where we have a long list of bad words

```
                for (let i = 1; i <= bad_word_ids.length - 1 && bad_word_ids.length < input_ids[i].length; ++i) {

                    // NOTE: We use != instead of !== to compare bigint and number
                    // @ts-ignore
                    if (bad_word_ids.at(-i - 1) != input_ids[i].at(-i)) {
                        // We have found a mismatch
                        mark = false;
                        break;
                    }
                }
```

with: 

```
Uncaught (in promise) TypeError: can't access property "length", input_ids[i] is undefined
```

my input_ids has just one entry when I use the regular pipeline function with dtype=q4 and devide=wasm
The code is a bit confusing because `i` is reused in both the inner and outer loop.

I fixed it by changing the inner loop with : 

```
// using `j` to avoid confusion with the outer loop
for (let j = 1; j <= bad_word_ids.length - 1; ++j) {
    // Ensure input_ids[i] is defined and has sufficient length before accessing
    if (input_ids[i] && bad_word_ids.length < input_ids[i].length) {
        // NOTE: We use != instead of !== to compare bigint and number
        if (bad_word_ids.at(-j - 1) != input_ids[i].at(-j)) {
            // We have found a mismatch
            mark = false;
            break;
        }
    } else {
        mark = false;
        break;
    }
}
```
I am not sure if that is the correct fix. Happy to do a PR

### Reproduction

.

**Comment by xenova** [comment]
Whoops my bad - a silly issue of reusing variables (`input_ids[i].at(-i)` should have been a dead giveaway). Probably some bad replace all 🤷 

Fixed by https://github.com/xenova/transformers.js/commit/d21c87cdda2cb54c65183606dd39fe75a139ed14.

Let me know if you face any other issues 👍
