### ISSUE TITLE
Error with Using require for ES Modules in @xenova/transformers Package

### ISSUE THREAD

**Issue by qamarali205** [xenova/transformers.js#922]
### System Info

Node.js

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

trying to use require to import the Pipeline class from the @xenova/transformers package, but encounter the following error:

const { Pipeline } = require('@xenova/transformers');
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Z-charity\dating_app_backend\node_modules\@xenova\transformers\src\transformers.js from D:\Z-charity\dating_app_backend\controllers\authController.js not supported.
Instead change the require of transformers.js in D:\Z-charity\dating_app_backend\controllers\authController.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\Z-charity\dating_app_backend\controllers\authController.js:10:22) {  
  code: 'ERR_REQUIRE_ESM'

Issue with Dynamic Import

const getPipeline = async () => {
	const { Pipeline } = await import('@xenova/transformers');
	return new Pipeline('text-classification', 'xenova/bert-base-uncased');
};

{
    "message": "Server error",
    "error": "Must implement _call method in subclass"
}

### Reproduction

trying to use require to import the Pipeline class from the @xenova/transformers package, but encounter the following error:

const { Pipeline } = require('@xenova/transformers');
                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Z-charity\dating_app_backend\node_modules\@xenova\transformers\src\transformers.js from D:\Z-charity\dating_app_backend\controllers\authController.js not supported.
Instead change the require of transformers.js in D:\Z-charity\dating_app_backend\controllers\authController.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\Z-charity\dating_app_backend\controllers\authController.js:10:22) {  
  code: 'ERR_REQUIRE_ESM'

Issue with Dynamic Import

const getPipeline = async () => {
	const { Pipeline } = await import('@xenova/transformers');
	return new Pipeline('text-classification', 'xenova/bert-base-uncased');
};

{
    "message": "Server error",
    "error": "Must implement _call method in subclass"
}

**Comment by xenova** [comment]
See https://github.com/xenova/transformers.js/issues/922

**Comment by Onixarts** [comment]
> See #922

@xenova this links to the same page.

**Comment by xenova** [comment]
Whoops, that's embarrassing! Meant to link to https://github.com/huggingface/transformers.js/issues/927. (the OP asked the same question twice).
