### ISSUE TITLE
[Feature Request] "slow tokenizer" format (`vocab.json` and `merges.txt`)

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#93]
Wondering whether this code is supposed to work (or some variation on the repo URL - I tried a few different things):
```js
await import("https://cdn.jsdelivr.net/npm/@xenova/transformers@1.4.2/dist/transformers.min.js");
let tokenizer = await AutoTokenizer.from_pretrained("https://huggingface.co/cerebras/Cerebras-GPT-1.3B/resolve/main");
```
The `cerebras/Cerebras-GPT-1.3B` repo only has a `config.json` (no `tokenizer.json`), but the `config.json` has `"model_type": "gpt2",` and has `vocab.json` and `merges.txt`. It does load successfully with the Python Transformers lib.

**Comment by xenova** [comment]
This is because the library currently doesn't support the "slow tokenizer" format (which is with vocab.json and mergex.txt). Ours only accepts the fast_tokenizer format (which is constructed directly from the single `tokenizer.json`; see "fast_tokenizer_file" in the code below)

https://github.com/huggingface/transformers/blob/ac2bc50a10522f15671e351150e03ecd6268da1e/src/transformers/tokenization_utils_fast.py#L95-L126

What's happening in the background of the python library, is that when you load the slow tokenizer, it gets converted to the fast tokenizer format. I'm not too sure why the creators of the model didn't include the tokenizer.json and tokenizer_config.json files, as it should be output when running `save_pretrained()`.

For the moment (since adding support for the slow tokenizer format is not the biggest priority), you can just load the tokenizer and then just save it again (which saves the fast format, by default)

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('cerebras/Cerebras-GPT-1.3B')
tokenizer.save_pretrained('output')
# Will output merges.txt, special_tokens_map.json, tokenizer.json, tokenizer_config.json, and vocab.json.
```

**Comment by josephrocca** [comment]
Ah, okay - thanks for that! I've changed the title of this issue, but please feel free to close this. In my case it's end users who enter a Hugging Face repo name in order to run the model on OpenCharacters, so most won't know how to do that in Python, but hopefully this isn't an issue for many repos, and I can always create forks on Hugging Face and add the files for the popular repos (that use the slow tokenizer format) that users want.

Again, please feel absolutely free to close this - from what you're saying it sounds like the "slow" format is on its way out and might be a waste time to implement.

**Comment by xenova** [comment]
Indeed - the slow format is "legacy", see here:

https://github.com/huggingface/transformers/blob/5bb4ec6233d6414a922ad2818f0bcf879de81c28/src/transformers/tokenization_utils_base.py#L2085-L2095

Of course, the main use-case is to load models from repos that contain the .onnx files, which (if correctly converted) should have the tokenizer.json file. I'll close the issue since, as you mentioned, it will probably be a waste of time to implement the legacy format. 

That said, I am working with the HF team to get web-ready versions of model files (.onnx and the associated files) in the officially supported model repos. And if a user wants to publish their own model, it should be their responsibility to make it support various formats (e.g., pytorch, safetensors, onnx, tensorflow)

**Comment by josephrocca** [comment]
> I am working with the HF team to get web-ready versions of model files (.onnx and the associated files) in the officially supported model repos

:eyes: :eyes: :eyes: :eyes: :eyes:

**Comment by josephrocca** [comment]
@xenova Can I confirm: The repo needs to have both `tokenizer.json` and `tokenizer_config.json`? I expected this to work:
```js
await import("https://cdn.jsdelivr.net/npm/@xenova/transformers@1.4.3/dist/transformers.min.js");
let tokenizer = await AutoTokenizer.from_pretrained("https://huggingface.co/distilgpt2/resolve/main");
```
Since `distilgpt2` has a `tokenizer.json` file, but I get this error:
```
caught Error: File not found. Could not locate "https://huggingface.co/distilgpt2/resolve/main/tokenizer_config.json".
    at u (utils.js:244:23)
    at async fetchJSON (utils.js:297:9)
    at async Promise.all (:3001/index 1)
    at async AutoTokenizer.from_pretrained (tokenizers.js:2591:29)
```
I ran the code below on the first two pages of the [text-generation pipeline tag on huggingface.co/models](https://huggingface.co/models?pipeline_tag=text-generation).
```js
let urls = [...document.querySelectorAll("a.block.p-2")].map(el => el.href+"/resolve/main");
let output = "";
for(let url of urls) {
  await import("https://cdn.jsdelivr.net/npm/@xenova/transformers@1.4.3/dist/transformers.min.js");
  let tokenizer = await AutoTokenizer.from_pretrained(url).catch(e => false);
  let success = !!tokenizer;
  console.log(url, success);
  output += `\n${success ? "SUCCESS" : "fail"}: ${url}`;
}
```
Output:
```
fail: https://huggingface.co/gpt2/resolve/main
fail: https://huggingface.co/distilgpt2/resolve/main
fail: https://huggingface.co/gpt2-medium/resolve/main
fail: https://huggingface.co/openai-gpt/resolve/main
fail: https://huggingface.co/gpt2-large/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloom-560m/resolve/main
fail: https://huggingface.co/EleutherAI/gpt-neo-2.7B/resolve/main
fail: https://huggingface.co/decapoda-research/llama-7b-hf/resolve/main
SUCCESS: https://huggingface.co/bigscience/test-bloomd-6b3/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloom-7b1/resolve/main
fail: https://huggingface.co/EleutherAI/gpt-neo-1.3B/resolve/main
SUCCESS: https://huggingface.co/Salesforce/codegen-350M-multi/resolve/main
fail: https://huggingface.co/gpt2-xl/resolve/main
fail: https://huggingface.co/bigcode/santacoder/resolve/main
fail: https://huggingface.co/cerebras/Cerebras-GPT-111M/resolve/main
fail: https://huggingface.co/xlnet-base-cased/resolve/main
SUCCESS: https://huggingface.co/Salesforce/codegen-2B-multi/resolve/main
fail: https://huggingface.co/facebook/opt-1.3b/resolve/main
fail: https://huggingface.co/facebook/opt-125m/resolve/main
fail: https://huggingface.co/facebook/opt-350m/resolve/main
SUCCESS: https://huggingface.co/TehVenom/PPO_Pygway-V8p4_Dev-6b/resolve/main
fail: https://huggingface.co/facebook/opt-66b/resolve/main
fail: https://huggingface.co/decapoda-research/llama-13b-hf/resolve/main
SUCCESS: https://huggingface.co/EleutherAI/gpt-j-6b/resolve/main
fail: https://huggingface.co/facebook/opt-13b/resolve/main
fail: https://huggingface.co/facebook/opt-6.7b/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloomz-560m/resolve/main
SUCCESS: https://huggingface.co/codeparrot/codeparrot/resolve/main
fail: https://huggingface.co/KoboldAI/OPT-6.7B-Erebus/resolve/main
SUCCESS: https://huggingface.co/Gustavosta/MagicPrompt-Stable-Diffusion/resolve/main
fail: https://huggingface.co/sshleifer/tiny-gpt2/resolve/main
fail: https://huggingface.co/cerebras/Cerebras-GPT-1.3B/resolve/main
fail: https://huggingface.co/decapoda-research/llama-30b-hf/resolve/main
SUCCESS: https://huggingface.co/codeparrot/codeparrot-small/resolve/main
fail: https://huggingface.co/rinna/japanese-gpt-1b/resolve/main
fail: https://huggingface.co/facebook/opt-2.7b/resolve/main
fail: https://huggingface.co/EleutherAI/gpt-neo-125m/resolve/main
SUCCESS: https://huggingface.co/Salesforce/codegen-350M-mono/resolve/main
fail: https://huggingface.co/robertmyers/bpt-rm-6b/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloom/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloomz-7b1-mt/resolve/main
fail: https://huggingface.co/SkyWork/SkyTextTiny/resolve/main
SUCCESS: https://huggingface.co/Salesforce/codegen-16B-mono/resolve/main
SUCCESS: https://huggingface.co/EleutherAI/gpt-neox-20b/resolve/main
SUCCESS: https://huggingface.co/KoboldAI/PPO_Pygway-6b-Mix/resolve/main
SUCCESS: https://huggingface.co/bigscience/bloom-3b/resolve/main
fail: https://huggingface.co/skt/kogpt2-base-v2/resolve/main
fail: https://huggingface.co/facebook/opt-30b/resolve/main
fail: https://huggingface.co/uer/gpt2-chinese-cluecorpussmall/resolve/main
fail: https://huggingface.co/KoboldAI/OPT-2.7B-Erebus/resolve/main
SUCCESS: https://huggingface.co/TehVenom/Dolly_Shygmalion-6b/resolve/main
fail: https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2/resolve/main
SUCCESS: https://huggingface.co/OpenAssistant/oasst-sft-1-pythia-12b/resolve/main
fail: https://huggingface.co/PascalNotin/Tranception_Small/resolve/main
fail: https://huggingface.co/microsoft/biogpt/resolve/main
fail: https://huggingface.co/trl-internal-testing/tiny-random-GPTNeoXForCausalLM/resolve/main
SUCCESS: https://huggingface.co/KoboldAI/GPT-NeoX-20B-Erebus/resolve/main
SUCCESS: https://huggingface.co/togethercomputer/GPT-JT-6B-v1/resolve/main
SUCCESS: https://huggingface.co/togethercomputer/GPT-NeoXT-Chat-Base-20B/resolve/main
fail: https://huggingface.co/decapoda-research/llama-65b-hf/resolve/main
```
If this is expected behavior, and I haven't made any mistakes here, then I think the new tokenizer format might be "too new" - i.e. I think it would make sense to support the old format given the "hit rate" here?
