### ISSUE TITLE
[Bug] Invalid regular expression when loading `bigscience/bloomz-3b` with `AutoTokenizer`.

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#94]
**Describe the bug**
Invalid regular expression when loading `bigscience/bloomz-3b` with `AutoTokenizer`.

**How to reproduce**
Paste in brower console:
```js
await import("https://cdn.jsdelivr.net/npm/@xenova/transformers@1.4.2/dist/transformers.min.js");
let tokenizer = await AutoTokenizer.from_pretrained("https://huggingface.co/bigscience/bloomz-3b/resolve/main");
```

**Logs/screenshots**
```
tokenizers.js:872 Uncaught SyntaxError: Invalid regular expression: / ?[^(\s|[.,!?…。，、।۔،])]+/: Unmatched ')' (at tokenizers.js:872:31)
    at new RegExp (<anonymous>)
    at Function.pre_tokenize_text (tokenizers.js:872:31)
    at tokenizers.js:781:41
    at Array.map (<anonymous>)
    at Function.pre_tokenize (tokenizers.js:781:27)
    at tokenizers.js:1372:30
    at Array.reduce (<anonymous>)
    at Function.pre_tokenize_text (tokenizers.js:1371:32)
    at Function.pre_tokenize (tokenizers.js:783:27)
    at Function._call (tokenizers.js:794:21)
```

![image](https://user-images.githubusercontent.com/1167575/232677266-4491d12c-f1fc-44ef-959b-4bf527cf8e87.png)

![image](https://user-images.githubusercontent.com/1167575/232677448-22cbc51e-7b6a-46a1-aab2-ae66e22f14bd.png)

**Environment**
- Transformers.js version: 1.4.2

**Comment by xenova** [comment]
It should be simple to fix this - looks like I'm missing a call to `escapeRegExp` :)

**Comment by xenova** [comment]
Update: It is not as simple as escaping the regex... 😅 

I'm unable to parse that regex, even in python... I've also noticed that there is no python implementation of the BloomTokenizer in the transformers library (only a BloomTokenizerFast, which is implemented in rust).

I get the same error as you do (`re.error: unbalanced parenthesis at position 21`), in python and javascript.

**Comment by xenova** [comment]
Looks like it's a known issue: https://huggingface.co/bigscience/bloom/discussions/212

**Comment by xenova** [comment]
Here's an equivalent regex which seems to work:
` ?[^\s|.|,|!|?|\u2026|\u3002|\uff0c|\u3001|\u0964|\u06d4|\u060c]+`

**Comment by josephrocca** [comment]
Ah, okay, thanks for your investigation!! Sounds like this issue should be closed.

**Comment by xenova** [comment]
No worries :) If you'd like you can submit an issue to the transformers/tokenizers repo, since it does appear to be an issue faced by others. I imagine it hasn't been fixed yet because most people use it through the Rust library (which seems to parse it correctly).

For now, it's probably fine to just replace the regex with what I posted above (it works on my side).
