### ISSUE TITLE
v3 webgpu crash after upgrade to chromium 129

### ISSUE THREAD

**Issue by eyaler** [xenova/transformers.js#943]
### System Info

windows 64
tested with chrome 128,129,130beta and edge 128,129,130canary
transformers v3alpha3-15 (also compared to 2.17.2)

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

hi! i am running https://huggingface.co/Xenova/modnet with onnx-runtime web on webgpu (fp32 non-quantized model), with the following observations:
1. chromium 128-130 + transformers v2.17.2 = works with slow performance
2. chromium 128 + transformers v3alpha3-15 = works at ~ 10x(!) performance compared to above
3. chromium 129-130 + transformers v3alpha3-15 = crash with ORT error: `Failed to execute 'mapAsync' on 'GPUBuffer': A valid external Instance reference no longer exists.`

### Reproduction

You can see this in my following code. If necessary I can prepare a minimal example.

Compare the following with both transformers.js versions on both chromium 128 vs. 129/130 (approve the self-tab share and choose modnet from the dropdown)
1. (v2.17.2) https://eyaler.github.io/LordTubeMaster/#dQw4w9WgXcQ
2. (v3alpha15) https://oulipoh.github.io/LordTubeMasterDev/#dQw4w9WgXcQ

**Comment by gyagp** [comment]
We also hit this issue last Friday and the investigation is WIP. It looks like a regression in Chrome now. Stay tuned.

**Comment by gyagp** [comment]
After more investigation, we think it's a DXC (shader compiler) issue. You may find more details at https://issues.chromium.org/issues/368997517. A workaround in ONNX Runtime, which Transformers.js is based on, is under review at https://github.com/microsoft/onnxruntime/pull/21995.

**Comment by flatsiedatsie** [comment]
Could "range error - buffer allocation failed" be related to this? I'm seeing that error in Android Chrome after an update there.

**Comment by gyagp** [comment]
> Could "range error - buffer allocation failed" be related to this? I'm seeing that error in Android Chrome after an update there.
> 
> <img alt="Screenshot 2024-09-25 at 12 48 39" width="589" src="https://private-user-images.githubusercontent.com/805405/370679899-dd6bb52d-30f5-4548-ab18-7527dfe79dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODE4OTQsIm5iZiI6MTcyNzI4MTU5NCwicGF0aCI6Ii84MDU0MDUvMzcwNjc5ODk5LWRkNmJiNTJkLTMwZjUtNDU0OC1hYjE4LTc1MjdkZmU3OWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNjI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjkwYTgwMDFmNzRlNzQ3NzY3NzU1ZGJlNzQzZGEzOTY2ZWY0NGZiODdjZGUwYTUyZjc4YTVjZGI0MjA2ZWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YsXuv8tB6Cxf3-faKhSpeLJ-yPP3Njea8Bs4aVQWuBU">

Your issue looks like OOM, and it's not related to this one, which crashes the GPU process.
BTW, Google already fixed this issue in DXC, and the roll to Chrome will take place in a few days. We will ask if they could back port it to Chrome Stable.

**Comment by eyaler** [comment]
alpha17 fixes this for me. thanks!

**Comment by flatsiedatsie** [comment]
It seems fixed here too. Nice!

**Comment by DXXS** [comment]
I'm having this issue with the latest on OSX : 'Chrome Version 137.0.7151.120', and 'TensorFlow.js v4.22.0' / webgpu : after calculating for a fairly long time, it threw such a '...Failed to execute 'mapAsync' on 'GPUBuffer'...' error.

**Comment by SignOfZeta** [comment]
> I'm having this issue with the latest on OSX : 'Chrome Version 137.0.7151.120', and 'TensorFlow.js v4.22.0' / webgpu : after calculating for a fairly long time, it threw such a '...Failed to execute 'mapAsync' on 'GPUBuffer'...' error.

What model/example code are you running? I will try and see if I can reproduce the same issue on my macbook this weekend.

**Comment by DXXS** [comment]
I've put a copy of my tic-tac-toe reinforcement learning code, which encountered said error, as I was running it, at: https://computacor.com/WebGPU_TicTacToe_Ov7_GPUError.html

It hurled about 2/3 the way through learning the game, at:
"...
Ep 64000/100000 | Draws: 95.4% | P1 Wins: 2.4% | P2 Wins: 2.2% | ε: 0.010
Ep 64500/100000 | Draws: 96.4% | P1 Wins: 2.6% | P2 Wins: 1.0% | ε: 0.010
Ep 65000/100000 | Draws: 96.4% | P1 Wins: 2.2% | P2 Wins: 1.4% | ε: 0.010
Ep 65500/100000 | Draws: 94.6% | P1 Wins: 2.8% | P2 Wins: 2.6% | ε: 0.010
[06:09:37 PM] [UNHANDLEDREJECTION] AbortError: Failed to execute 'mapAsync' on 'GPUBuffer': A valid external Instance reference no longer exists."

**Comment by xenova** [comment]
> 'TensorFlow.js v4.22.0' / webgpu

Note that this is the repository for Transformers.js, not Tensorflow.js 🤗

But if it helps, that error usually means it ran out of memory, causing the GPU instance to crash and become unavailable. Possibly a memory leak in your code or tensorflow.js

**Comment by DXXS** [comment]
Yes, that's why I opened the new issue there & not here : https://github.com/tensorflow/tfjs/issues/8571

   This just happens to be where my web search found "Failed to execute 'mapAsync' on 'GPUBuffer'", which it seems to me that apparently both libraries pass along instead of more understandably translating as a memory issue!?

   FWIW, I've checked my system memory (OSX 'Activity Monitor') after such an occurrance, and it didn't show evidence of a significant problem (CPU-side anyhow).
