### ISSUE TITLE
[Feature request] Whisper with language support

### ISSUE THREAD

**Issue by jozefchutka** [xenova/transformers.js#95]
I am having hard times making whisper models (ie. base, not base.en) useful for any other language than English. Looking into sources I observed a few potentially related TODOs: 

- https://github.com/xenova/transformers.js/blob/main/src/models.js#L1606
- https://github.com/xenova/transformers.js/blob/main/src/pipelines.js#L753

Could these please be resolved?

I wonder if there is any other way in current transfromres.js to define input language.

**Comment by xenova** [comment]
Linked to https://github.com/xenova/transformers.js/issues/87

Will be added soon! :)

**Comment by xenova** [comment]
Coming soon... (https://github.com/xenova/transformers.js/commit/29bbfe5ab4adca24cc51238f2bf4f3f72ec7126d) ;)
