### ISSUE TITLE
TypeError: e.split is not a function

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#950]
### System Info

V3 Alpha 17

Mac  OS
Brave

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

<img width="520" alt="Screenshot 2024-09-28 at 23 26 43" src="https://github.com/user-attachments/assets/caf64313-45c3-4f51-b1b9-fac9b9fef257">

An issue applying template for Llama 3.2 it 3B. Most likely an issue in my code, but just to be safe / in case you want to harden against this.

Config / Tokenizer data: https://huggingface.co/BoscoTheDog/llama_3_2_it_3b_q4_k_m_chunked/tree/main

### Reproduction

It's happening consistently. I'll try loading tokenizer.json from another repo.

**Comment by flatsiedatsie** [comment]
I tried pointing to the ONNX Community repo, but that resulted in a different error.

<img width="521" alt="Screenshot 2024-09-28 at 23 41 02" src="https://github.com/user-attachments/assets/78708c45-339a-4512-9cd5-31fb3e551230">

**Comment by flatsiedatsie** [comment]
Third time's the charm. `alpindale/Llama-3.2-3B-Instruct` worked.

**Comment by xenova** [comment]
This is due to a new tokenizers format for v0.20.0 - where merges are stored as `[string, string][]` instead of `string[]`. I fixed it [here](https://github.com/xenova/transformers.js/commit/9a42cf32365fd47d42fbc514c3d807d18c5ea3be), and should work for alpha>=18
