### ISSUE TITLE
Confusing Error Message When Calling `apply_chat_template` Without `chat_template` Configuration

### ISSUE THREAD

**Issue by zhzLuke96** [xenova/transformers.js#964]
### System Info

windows 10

(This issue is not related to the system)

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

If a tokenizer is not configured with `chat_template` and `apply_chat_template` is called, the error message is incorrect and raises `TypeError: Cannot use 'in' operator to search for 'default' in null`.

Specific location:
https://github.com/xenova/transformers.js/blob/8891a142859782a6a4a622056741f1a5be55e93b/src/tokenizers.js#L3134-L3151

This is not a critical issue, but the error message is misleading.

### Reproduction

1. Use https://huggingface.co/Xenova/gpt-4o
2. @huggingface/transformers@3.0.0-alpha
3. Call `apply_chat_template`.

**Comment by xenova** [comment]
Hi there 👋 Can you provide the code used? I believe this should have been fixed in one of the recent alpha releases.
```js
// npm i @huggingface/transformers
import { AutoTokenizer } from '@huggingface/transformers';

const tokenizer = await AutoTokenizer.from_pretrained('Xenova/gpt-4o');
const tokens = tokenizer.encode('hello world');
console.log(tokens); // [24912, 2375]

const messages = [
    { role: 'user', content: 'Hello!'}
]
const prompt = tokenizer.apply_chat_template(messages);
console.log(prompt);
// Error: Cannot use apply_chat_template() because tokenizer.chat_template
// is not set and no template argument was passed! For information about
// writing templates and setting the tokenizer.chat_template attribute,
// please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating
```

**Comment by zhzLuke96** [comment]
ooops, my bad
I see. In fact, it's because I was using the code from the [@huggingface/transformers](https://github.com/xenova/transformers.js/tree/%40huggingface/transformers) branch, thinking it was the latest.

I've noticed that the latest code is in the v3 branch. Thank you for your reply! This issue can be closed.
