### ISSUE TITLE
OffscreenCanvas issue in image_utils.js

### ISSUE THREAD

**Issue by ldenoue** [xenova/transformers.js#97]
**Describe the bug**
*A clear and concise description of what the bug is.*

On Mobile Safari iOS, I get this error

ReferenceError: Can't find variable: OffscreenCanvas in `./src/image_utils.js` line 13
![image](https://user-images.githubusercontent.com/149561/233787979-79f42bf3-c05b-4bce-b849-236b656b9557.png)

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

go to https://xenova.github.io/transformers.js/ and try the Whisper model.

**Expected behavior**
*A clear and concise description of what you expected to happen.*

No error?

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: latest online as of April 22, 2023
- Browser (if applicable): Mobile Safari iOS
- Operating system (if applicable): iOS
- Other:

**Additional context**
*Add any other context about the problem here.*

**Comment by xenova** [comment]
Hmm that's strange. I thought iOS supported `OffscreenCanvas`: https://caniuse.com/?search=offscreencanvas. Perhaps it's necessary to call `self.OffscreenCanvas`? I unfortunately don't have a mac to do testing like this on, so, if you can report back to see if you can use `OffscreenCanvas` in some way, that would be great!

**Comment by xenova** [comment]
So, while updating to iOS 16.4.1 fixed that issue, it opened up a whole new can of worms. All output was completely wrong, and it appears to be a bug with onnxruntime-web itself. I filed a bug report (see [here](https://github.com/microsoft/onnxruntime/issues/15644)), and hopefully it is resolved soon).

**Comment by ldenoue** [comment]
Regardless of this related onnxruntime-web issue, would it be possible to write the lib so that if OffscreenCanvas isn't available, the lib doesn't error? Some models, such as Whisper, that people use transformers.js with do not need OffscreenCanvas, correct?

**Comment by xenova** [comment]
> Regardless of this related onnxruntime-web issue, would it be possible to write the lib so that if OffscreenCanvas isn't available, the lib doesn't error? Some models, such as Whisper, that people use transformers.js with do not need OffscreenCanvas, correct?

Sure - that's possible. I'll make it so that it only throws an error when trying to access the OffscreenCanvas

**Comment by xenova** [comment]
This is now fixed in the latest [prerelease](https://www.npmjs.com/package/@xenova/transformers) (2.0.0-alpha.0). Will make a full release soon after some more testing.
