### ISSUE TITLE
Module not found: Can't resolve './' in Next.js

### ISSUE THREAD

**Issue by weekenchen** [xenova/transformers.js#980]
### System Info

"@huggingface/transformers": "3.0.0-alpha.21"
chrome: 129
OS: mac os
node: v20

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Reference [example](https://github.com/huggingface/transformers.js-examples/blob/main/remove-background-webgpu/src/App.jsx) Startup Error

### Reproduction

 ○ Compiling /face ...
 ⨯ ./node_modules/.pnpm/@huggingface+transformers@3.0.0-alpha.21/node_modules/@huggingface/transformers/dist/transformers.js:32680:1
Module not found: Can't resolve './'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./pages/face/index.tsx
 GET /face 500 in 2539ms
 GET /face 500 in 2527ms

**Comment by geronimi73** [comment]
same here. how did you solve this?

**Comment by psychiatrichwj** [comment]
same here. how did you solve this?

**Comment by geronimi73** [comment]
Works! Thank you!
