### ISSUE TITLE
[Bug] Models not cached

### ISSUE THREAD

**Issue by jozefchutka** [xenova/transformers.js#99]
I ran into an issue where some models (i.e. /openai/whisper-base/speech2seq-lm-with-past/decoder_model_merged.onnx ) would not get cached in browser cache via `cache.put()`. 

I am able to reproduce on my PC:
1. play around with transformers whisper demo (customized to be able to use other version of whisper model) using various models and have app cache enough data (ie > 200MB in my case, you can check the amount in chrome dev tools / Application / Application / Storage / Usage)
2. run example using whisper-base model, notice Network tab downloading the necessary assets
3. once downloaded check dev tools / Application / Storage / Cache Storage / transformers-cache is missing decoder_model_merged.onnx which was previously downloaded (~80MB)
4. run the same example again with same model and see decoder_model_merged.onnx being downloaded again (b/c not being cached)

- Transformers.js version: 1.4.2
- Browser (if applicable): chrome 112
- Operating system (if applicable): win 10

This might be potentially be a browser bug, however I managed to resolve it by waiting for cahce.put to complete.
I modified https://github.com/xenova/transformers.js/blob/main/src/utils.js#L276 and changed into:

```js
await cache.put(request...
```

with this change in place, all the assets gets cached normally

**Comment by xenova** [comment]
Good catch! Fixed [here](https://github.com/xenova/transformers.js/commit/727c0d30b40958fb6efbb984cc43bd01beaf54ba).

I also added error-handling logic for situations where the quota is exceeded ([here](https://github.com/xenova/transformers.js/commit/86d3aa1d60842e55ae37cb6438b250b94adba68a)).

Will close the issue when merged into main.

**Comment by jozefchutka** [comment]
Cool, and thanks for a quick update.
